### ISSUE TITLE
Tip component doesn't display centered on a component

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1032]
When a Tip is displayed, it's not centered aligned on the target.
Also, if a Tip's target is a icon, it won't show up.

### Expected Behavior

Tip should be center aligned.

### Actual Behavior

Tip appears to be left aligned.

### URL, screen shot, or Codepen exhibiting the issue
I'd provide a CodePen, but Tip isn't defined in the template.  Here's a picture:

![image](https://cloud.githubusercontent.com/assets/14231471/20028226/32b2f646-a2e9-11e6-9eda-ae539e3475d6.png)

### Steps to Reproduce
 1. Make a Tip; target a Box
 2. Put something in the Box (icon, for example)
 3. Fire the tip.  Notice it's not centered.

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome Win10
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
I noticed that Icon does not support id so far. I will create a separate issue to allow Icons to receive id. In this case I would not put the id in the box because it will take the full width of the screen.

As soon as the icon can receive id I would move the target on Tip to be the icon.

See https://github.com/grommet/grommet/issues/1041

I'm closing this issue and will track the fix for the icon in this other ticket.

**Comment by pawelpicur** [comment]
I found that <Status/> still doesn't support id. Really similar to this case
![image](https://user-images.githubusercontent.com/28948842/28661650-aa7a9c58-72b7-11e7-8171-4fbc9764dfa4.png)
I tried putting Status in div and then targeting the div, but when my page shrinks on lower resolutions it looks bad (moving with the div, not the icon)
