### ISSUE TITLE
Disabled <Select /> allows modifications/search

### ISSUE THREAD

**Issue by maxleiko** [grommet/grommet#1038]
### Expected Behavior
It seems legit that the `<Select />` components that are disabled should **not** allow users to click on the dropdown icon which results in the search dropdown to show nor change the value of the input.

### Actual Behavior
The search dropdown does show even if the `<Select />` component is disabled using the HTML attribute `disabled` and the user is still able to change the value.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/leiko/pen/oYjpYr

### Steps to Reproduce
 1. Verify that the select works by changing the value
 2. Disable the `<Select />` component
 3. Verify that you still can change the value *(even if you should not)*

### Your Environment

* Grommet version: `1.0.1`
* Browser Name and version: `Google Chrome Version 54.0.2840.59 (64-bit)`
* Operating System and version (desktop or mobile): `Linux Mint 17.2 Rafaela 64-bit`

**Comment by alansouzati** [comment]
Thanks for your issue. Grommet custom components do not support disabled attributes. During our recent user studies we found that users will not know what to do in order to enable the field again. It is sort of an anti-pattern for our User Experience framework.

We do transfer properties to our components but in the case of the Select will not help much as the underlying component is not a native Select element. So doing this:

```
  <Select disabled ... />
```

will actually disable the input text inside the Select element.

I'm closing the issue as it is the expected behavior.
