### ISSUE TITLE
cannot pass context to Toast/Layer/Drop/Menu components children

### ISSUE THREAD

**Issue by kadinwu** [grommet/grommet#1054]
cannot pass context to Toast/Layer/Drop/Menu components children 

In Toast/Layer/Drop/Menu component, all use getChildContext method, and hardcode only some limit grommet context property can be passed to children, like history, intl, router, store...
if i want to pass my created context to all all children. then make it failed.
`example:
<MyComponent>
   <Layer>
      <MyChildComponent />
  </Layer>
<MyComponent>`

as above, I cannot pass MyComponent context to MyChildComponent, because MyChildComponent is child of Layer.

**Comment by jaitaiwan** [comment]
I spent a bit of time investigating this. Here's a JS Fiddle showing the funsies of react contexts: https://jsfiddle.net/69z2wepo/63782/

What this effectively shows is that as long as a _single_ root object provides context using the `getChildContext` function and specifying `childContextTypes` a theoretically infinite number of children would now have access to anything in context defined by that parent component.

Because grommet components redefine the getChildContext at every level and don't make allowances for extra context that may have been supplied by a parent component up the chain, any extra contexts are removed.

This one is a pretty easy fix where all that needs to be done is for grommet components to specify what context they might need (aka intl) and let a parent component pass down context. This means almost all grommet components can remove the `getChildContext` and `childContextTypes` definitions.

**Comment by kadinwu** [comment]
@jaitaiwan 
Thanks for your feedback, yes, the root cause its these components have getChildContext/childContextTypes function make i cannot pass context from parent component. I did search just found Toast/Layer/Drop/Menu these four components have this function, so could you fix it?
Thanks a lot.

**Comment by jaitaiwan** [comment]
@kadinwu I'll hopefully be fixing it when I do a pull request to make styling more modular. It just depends on whether or not I can get my head around how grommet's css is built.

**Comment by kadinwu** [comment]
@jaitaiwan any update for this issue, thanks

**Comment by jaitaiwan** [comment]
Hey @kadinwu at the moment the work is going on behind a local branch I have of grommet.

**Comment by jaitaiwan** [comment]
I haven't had the time to continue with my work on the project and Grommet has made several iterations since I first embarked on this. I'll have to take another go at it but I'm not sure when I'll be able to.
