### ISSUE TITLE
Meter size 'medium' is not working

### ISSUE THREAD

**Issue by kadinwu** [grommet/grommet#1062]
Set meter size to 'medium', it used 'large' style.

**Comment by tracybarmore** [comment]
Thanks for your feedback. We can't seem to reproduce the issue. Can you please provide more detail by filling out our issue form? Thanks!



### Expected Behavior


### Actual Behavior


### URL, screen shot, or Codepen exhibiting the issue



### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by kadinwu** [comment]
update grommet to version 1.0.1, then works fine. I was using 0.6.12.
