### ISSUE TITLE
Clicking on a menu causes a scroll to the top of the page.

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1071]
If a menu is clicked, the user is pushed to the top of the page.  This is only noticeable when the user's Y scroll value is greater than zero.

### Expected Behavior

Scroll position should not change.

### Actual Behavior

User is pushed to the top of the page.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/mcwagner10/pen/vXmAEE?editors=1010

### Steps to Reproduce
 1. Make a page that has a vertical scroll bar
 2. Add a menu to the page
 3. Scroll down slightly
 4. Click the menu.  Notice user is pushed to the top.

### Your Environment

* Grommet version: Stable
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10 desktop

**Comment by azmtbr** [comment]
I'm getting the same exact behavior when using the `Select` component. 
I was not able to recreate the issue in a codepen.

Not sure if this would have anything to do with this issue, but I'm also having problems using the `inline` and `multiple` props with the `Select` component.

**Comment by jaitaiwan** [comment]
@mcwagner10 Your issue is a result of html. By setting `href="#"` when you click the the link you're telling the browser to look for the anchor whose name is empty `<a name=""></a>` as a result of not finding the anchor it takes you to the top of the page. This is expected behaviour.

A simple fix is to add an `onClick` handler which calls `e.preventDefault()`. You can see alternative solutions in [this stack overflow](http://stackoverflow.com/questions/1601933/how-do-i-stop-a-web-page-from-scrolling-to-the-top-when-a-link-is-clicked-that-t).

If that fixes your issue please remember to close this thread.

@azmtbr Your issue is likely going to be something different. I'd suggest opening a separate ticket for yours and do your best to provide as much information as you can to help in a reproduction.

Thanks!

**Comment by mcwagner10** [comment]
@jaitaiwan Check out the description and codepen again. The user can't even see the menu links because clicking the drop down moves to the top of the page. The Anchor tags aren't the issue.

**Comment by jaitaiwan** [comment]
Gah. Thanks @mcwagner10. Completely misread it.

**Comment by jaitaiwan** [comment]
So after completely failing to read and correctly understand the problem I spent some time trying to root out the cause of the issue as penance. Definitely a fairly bizarre issue (to me at least). I think I've pinpointed it down somewhat to this line: https://github.com/grommet/grommet/blob/master/src/js/utils/Drop.js#L37

And the order in which the drop is rendered vs the anchor being scrolled to...

**Comment by tracybarmore** [comment]
Also see #1046

**Comment by codingInSpace** [comment]
This also affects at least the Layer and the DateTime component as well. Adding them to the codepen shows it. Does everyone have this issue? Why does it not apply to the Menu component on the docs page? https://grommet.github.io/docs/menu

**Comment by karatechops** [comment]
Just ran into this today. Created an example before I saw there was already an issue open, here's my [codepen](https://github.com/grommet/grommet/issues/1071) displaying the behavior. My app has a few Boxes stacked horizontally each with their own Menu component, the Menu has a tendency to jump around - particularly with y overflow.

**Comment by tracybarmore** [comment]
linking to #1071
