### ISSUE TITLE
"Logo Component" is too vague in documentation

### ISSUE THREAD

**Issue by jaitaiwan** [grommet/grommet#1073]
There appears to be no `Logo` component in grommet yet it is referenced as a type of component that can be passed into the `LoginForm` component and is shown in many examples in the `Header` component.

I suggest that:

- the Logo component is made available as part of this repo, OR
- the Logo component's location is documented better in the documentation, OR
- the Logo component is removed from examples and a better specification of what a Logo component is, is provided for the LoginForm documentation

**Comment by alansouzati** [comment]
Thanks for your feedback. I agree the term "logo component" is vague.

Implementation wise it is just a node. Often an SVG element that represents your logo.

We gladly appreciate pull requests. This I believe it is a good candidate for help.

The source code for the documentation is here:

https://github.com/grommet/grommet-docs

The component documentation for the LoginForm is here:

https://github.com/grommet/grommet-docs/blob/master/src/docs/components/login-form/LoginFormDoc.js#L52

Would you be kind enough to update the description of this pull request and send a pull request?

Otherwise we will eventually work on that.

**Comment by jaitaiwan** [comment]
@alansouzati I've created the Pull request as above.

**Comment by tracybarmore** [comment]
Pull request #180 reference.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-docs/commit/3c7be98435a3670d61c09db5954112643edfa202
