### ISSUE TITLE
Feature request: Color picker

### ISSUE THREAD

**Issue by mkv123** [grommet/grommet#1090]
Currently there is no Color picker component that I'm aware of in grommet. The addition of one would be very welcome. I'd personally prefer something like the chrome dev tools color picker, but the choices are many: https://casesandberg.github.io/react-color/

**Comment by ericsoderberghp** [comment]
With 556c503b123158ca255e2ebee242b3d8d8b2d8d1 we've ensured that we can handle <input type='color' /> inside FormField. We prefer sticking with the native version of this pop-up control rather than adding a separate custom one. You can see the native one in the 'input - color' field here: https://grommet.github.io/docs/form/examples?i-header=false&i-footer=false&i-all-types=true
