### ISSUE TITLE
Date-Time: Text-Masking

### ISSUE THREAD

**Issue by Matt-Butler** [grommet/grommet#1103]
Is there a way of doing text-masking?

### Expected Behavior
Text-Mask is visible while entering date
![text-mask](https://cloud.githubusercontent.com/assets/8146159/21369831/694e7726-c6ce-11e6-8a2a-a5e4ed57e058.gif)

### Actual Behavior
Text-Mask is not visible while entering date
![datetime](https://cloud.githubusercontent.com/assets/8146159/21369833/6dde0f2c-c6ce-11e6-96eb-891570efee24.gif)

**Comment by alansouzati** [comment]
Sorry for taking such a long time to get back to you on this.

Format date used to be a pattern in the past, but due to the UX complications it does not seem to be a pattern anymore. Grommet does not recommend doing this, this is why we don't have that built in. 

The reason we don't have date format, is the same as the reason for not doing format validation as the user type in the field. We prefer to let the user take full control of the form inputs and when they submit (which is a clear indication they are done filling it), then we apply formatting and validation.

If you take a look on known sites that are date-driven (like airbnb, expedia), they don't do date format, and I believe this is for the same reason as Grommet's.

I'm closing the issue for now but feel free to reopen it if you feel I'm missing something.
