### ISSUE TITLE
feature request: TreeView

### ISSUE THREAD

**Issue by msuiche** [grommet/grommet#1104]
It would be nice to have a TreeView component, in addition of the current portfolio of components.

**Comment by moizhb** [comment]
:+1:

**Comment by soju-cao** [comment]
Expecting

**Comment by tracybarmore** [comment]
Hi @msuiche, thanks for the issue. 

Grommet follows a Hub & Spoke navigational pattern to eliminate the need for a treeview navigation. Hub & Spoke is useful for multiple, distinct, linear workflows. Building task-based experiences stemming from a common start point helps ensure the items within an app correlate for a cohesive experience. 

You may notice that all the [Grommet showcase apps](https://grommet.github.io/docs/showcase) do not contain any treeview structures. This is due to our focus on mobile experiences. Treeviews in mobile become problematic since to include an appropriate touch target (at least 24px) to avoid accidental "fat-finger" selecting on an option, the treeview can become too large to fit within the mobile view window, resulting in the user needing to scroll both horizontally and vertically to select an option.

Other components to consider to create this Hub & Spoke approach is using a drilldown List or Tile view. Example would be: Home page contains top level navigation. Top level link is selected, home page is replaced by a list view (or tile view) of secondary level navigation... then keep drilling down. 

An decent example of this is [Ferret](http://ferret.grommet.io/dashboard). It's Virtual Machine page is a tile view and Activity page is a list view. 

Because of this UX guidance, we have added the no change label since a treeview is not a component or dev card we are planning to add to the grommet core repo. Grommet designers (such as myself) like to challenge use cases that a product feels they need a treeview, since we will normally ask to restructure the information architecture instead of creating a new Grommet component. 

So, if you have a specific example that you would like our designers to take a look at, please post to our #visualdesign channel to give us some work 👍

**Comment by tracybarmore** [comment]
Also, we plan to add more documenation around our Hub & Spoke approach. To follow that backlog item see #1031

**Comment by msuiche** [comment]
@tracybarmore A process viewer ! https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx What would be a better representation than a TreeView to visualize processes (with then parent process id, children process id etc.). I would love a visual alternative !
