### ISSUE TITLE
Component Select doesn't align dropdown to top

### ISSUE THREAD

**Issue by ArtemZag** [grommet/grommet#1173]
### Expected Behavior
Component **Select** should either align **Drop** component automatically (depending on the free space) or it should provide property "dropalign" (like **Menu** component does).

### Actual Behavior
The popup position is hardcoded.
See this line of code: https://github.com/grommet/grommet/blob/master/src/js/components/Select.js#L100

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/termitiai/pen/vgjdJE

### Steps to Reproduce
 1. Try to open the dropdown

### Your Environment
* Grommet version: 1.2.0
* Browser Name and version: chrome 55.0.2883.87 m
* Operating System and version (desktop or mobile): Windows 10 x64 (desktop)

**Comment by alansouzati** [comment]
Very good point. I would rather align the Drop automatically. the drop for the Select is special because it has the search box. If we align top, the contents of the drops needs to change ordering. For example, the search box should be at the bottom and the suggestion values reversed.

I will try to work on that change soon. Thanks for creating the codepen.

**Comment by alansouzati** [comment]
hey @ArtemZag could you please share a scenario where you are trying to render the Select at the bottom of the page?

I've tried fixing that but it brings a lot of UX concerns on the way we render things.

For example:

![screen shot 2017-02-06 at 11 59 49 am](https://cloud.githubusercontent.com/assets/1207250/22664025/c8c9fdd2-ec63-11e6-802d-1716640c281d.png)

If I press the `up` arrow, to get the most important item("one") I would have to press that 3 times instead of one. One possible solution would be to reverse the list where one will be the first. But the problem this brings is that you are reading in reverse order which seems wrong as our natural behavior is to scan things top-down.

I've tried to compare on how other frameworks solve that problem and I cannot find a decent solution that fits the Grommet UX guidelines.

Thoughts? If you can share you screen we can try to provide an alternate structure that does not use the select component.

**Comment by ArtemZag** [comment]
@alansouzati , I have a very specific UI. The page is not scrollable. And at the bottom I need some selector.
![image](https://cloud.githubusercontent.com/assets/1687370/22701408/41e39bd0-ed66-11e6-85fb-c97b0131d13f.png)

**Comment by alansouzati** [comment]
Visually does it make more sense to be at the Header? How is the reporting date different from "Filters" ? Could you bake that in with the other filters? Maybe even inline them with radio buttons ?

Would the "reporting year" affect the list on the left? If so, it makes sense to put them in the Header because it is a natural progression: you change something at the top that affects something at the bottom.

**Comment by ArtemZag** [comment]
@alansouzati , thanks for your answer. Probably you are right and we just need to change the UI concept. I will discuss it with my customer. If he doesn't agree than I will probably create my own combobox based on your code and styles.

**Comment by alansouzati** [comment]
Sounds good.

Sorry we could not help it further, we can "fix" it but we are worried about the UX repercussions of this change.

I'm closing the issue for now.
