### ISSUE TITLE
IE11 false loacle provided

### ISSUE THREAD

**Issue by Catx7** [grommet/grommet#1181]
In IE 11 using the following code 
`import {getCurrentLocale, getLocaleData} from 'grommet/utils/Locale';`
`getCurrentLocale();` returns only 'en-US' .It doesn't look for browser language.

It works fine in Firefox and Chrome.

**Comment by Catx7** [comment]
any solution?

**Comment by tracybarmore** [comment]
Hey @Catx7, thanks for bringing up this issue. We have another IE11 issue that we are looking in to so will combine efforts here. Stay tuned!

**Comment by alansouzati** [comment]
This is actually a limitation with ie11. As per their docs `navigator.userLanguage` will return the installed language. I tested it myself and it is not working as well. Locale utils is doing the job as documented by ie11.

Do you have access to your back-end? Can you make sure to set a Cookie with the accept-language?

See this: https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-tasks-dev.js#L89

If you don't have access to a back-end I recommend enabling a script that will do that for you, this is not optimal since you will have two requests.

See this issue for reference: http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

There is a script that is available that you can use `http://ajaxhttpheaders.appspot.com`. Although I would recommend changing your back-end to provide this header.

I'm closing this issue since there is nothing Locale util can do to fix this issue. Please feel free to reopen it if you have a solution to this problem.
