### ISSUE TITLE
Dependency usage - react-desc

### ISSUE THREAD

**Issue by sorin-davidoi** [grommet/grommet#1202]
I'm currently analysing the content of my Webpack bundles and I'm noticing that `react-desc` is being pulled by the Anchor component. It appears to be the only one using it. Since this is a development dependency, I don't think it should be shipped to the browsers.

### Expected Behavior

`react-desc` is not a dependency (at least not a production dependency) and is not shipped to the browsers.

### Actual Behavior
It is a required dependency.

### Your Environment

* Grommet version: 1.2.1

**Comment by ericsoderberghp** [comment]
Isn't it required since Anchor.js uses it? It needs to be in the grommet npm package since components importing Anchor will need it too.

I believe `react-desc` is just extending the basic PropTypes in react. It is a fairly small package, so I doubt it is contributing significantly to your bundled app size. But, I do like the idea of keeping the package footprint as lean as possible. @alansouzati has done the work on it and is currently away for a bit. When he returns we will revisit.

**Comment by alansouzati** [comment]
I understand your concern and I'm glad to hear that your analyzing the webpack bundle size.

As @ericsoderberghp said, `react-desc` is a very small package and it is currently being used in production to bundle the documentation of a given component. This is actually described in the react desc documentation:

https://github.com/grommet/react-desc#limitations

Unfortunately I did not have time yet to add the babel plugin to Grommet core. Would you mind sending a pull request to fix that?

I still believe `react-desc` will remain as a production dependency. But I would appreciate if you can investigate if adding the babel plugin will allow `react-desc` to be a devDependency.

This will be soon solved by webpack 2 with the three shaking capabilities.

**Comment by alansouzati** [comment]
Actually Grommet will stay with the propTypes in, so that we can use that in grommet-docs to show documentation. We recommend you adding that plugin in your babel config to remove propTypes from your app and your dependencies.

I'm closing this issue for now as I believe there is nothing to be done here. Feel free to reopen it if you have a better idea on how to solve this.
