### ISSUE TITLE
Don't force sass loader to allow using grommet

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1210]
I think that forcing importing a sass file is a wrong approach
`import 'grommet/scss/vanilla/index';`

as we know create-react-app is very popular but we [can't use it with grommet](https://github.com/facebookincubator/create-react-app/issues/1639)

we can solve it easily by adding a compiled css into grommet package
so we can just import a simple vanila css.

Thats good not only for  create-react-app but also for anyone that don't want to add sass loader
only for using grommet.

Thats one limitation we can just remove

**Comment by arabold** [comment]
I'd appreciate a pre-bundled CSS file as well. Using SASS complicates our deployment unnecessarily as we have to treat `grommet` different to other `node_module` components. We use server-side rendering on AWS Lambda (Node 4.3) together with hosting static files on S3. Due to the nature of this setup we cannot do any on-the-fly processing of ES6 or SASS (as it's done in sooooo many examples all over the web) but have to transpill _everything_ before deployment. The use of SASS in 3rd party components makes that a little bit more complex than it should be IMO. 

Here's the relevant excerpt from our Webpack config:
```js
// ...
module: {
  loaders: [
    {
      test: /\.(scss|css)$/,
      include : [ path.resolve(__dirname, 'node_modules/grommet') ],
      loader: ExtractTextPlugin.extract(
        'style',
        'css!sass?outputStyle=compressed'
      )
    }
  ]
},
sassLoader: {
  data: '@import "theme/_config.scss";',
  includePaths: [
    path.resolve(__dirname, './src'),
    path.resolve(__dirname, './node_modules/grommet/node_modules')
  ]
}
// ...
```

And then of course the include in the index page as already mentioned:
```js
// import styles
import 'grommet/scss/vanilla/index.scss';
```

**Comment by RyanCCollins** [comment]
Hey @shai32 and @arabold, thanks for your notes!

You are not forced to use sass when you use Grommet, but grommet is built on top of a sass and for the meantime that is a reality.  If you do not want to bother setting up the sass-loader, you can always include only the compiled css, either compiling yourself or linking to the [grommet.min.css](https://github.com/grommet/grommet/blob/stable/grommet.min.css) file included in the package.

By the way, the Grommet team has been exploring [css modules](https://github.com/grommet/grommet/issues/732) for quite some time.  If that's something you'd like to help with, maybe we can get there faster.

**Comment by RyanCCollins** [comment]
As far as I know, there is no hard dependency on sass.  Sass compiles into css before it's loaded into the bundle.  Grommet needs css in order to work, but it doesn't matter whether sass precompiles it using the webpack sass-loader, or if it's included via a precompiled css file.

One thing to be aware of, however, is that your bundle would likely be bigger due to the fact that you are pulling in all of the grommet themes.

**Comment by RyanCCollins** [comment]
@arabold, I have closed this issue, but please feel free to keep this conversation open.
