### ISSUE TITLE
Unknown prop `align` on <div> tag (App)

### ISSUE THREAD

**Issue by monte-hayward** [grommet/grommet#1245]
### Expected Behavior
proprietary attributes translated or removed

### Actual Behavior
attributes remain, e.g. "align"

```
Warning: Unknown prop `align` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by App)
    in App (created by HelloWorldApp)
    in HelloWorldApp
```

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/monte-hayward/pen/BWJNeK?&editors=0010

### Steps to Reproduce
 1. `import App from 'grommet/components/App';`
 2. `<App>{children}</App>`
 3. load page

### Your Environment
* Grommet version: 1.3.1
* Browser Name and version: Chrome Version 56.0.2924.87 (64-bit)
* Operating System and version (desktop or mobile): MacOs Sierra

**Comment by alansouzati** [comment]
App does not support `align` attribute, so I'm not sure what do you mean by "proprietary" attributes.

If you want to have the content of your app in the center of a page please use Box.

I've create a codepen for you: http://codepen.io/alansouzati/pen/yMvoeR?editors=0010

I'm closing this issue since I believe there is nothing to be fixed here. Please feel free to reopen if you think otherwise.
