### ISSUE TITLE
Meter series with more than 4 values not rendering as expected

### ISSUE THREAD

**Issue by bsjaffer** [grommet/grommet#1248]
I am using meter series with more than 4 values , when i have meter series more than 4 values then the bar size is becoming small, please find the code snippet and image attached. Is this an issue are i am missing something in configuration. ? 

```

class App extends Component {
  render() {
    return (<Meter size='large'
            vertical={true}
                series={[{"label": "Gen 7", "value": 50, "colorIndex": "graph-1"}, {"label": "Gen 8", "value": 1,  "colorIndex": "graph-2"}, {"label": "Gen 9", "value": 19,"colorIndex": "graph-3"}, {"label": "Gen 10", "value": 30,  "colorIndex": "graph-4"}]}
                    />);
  }
}

export default App;

```
With 5 values, 

![image](https://cloud.githubusercontent.com/assets/1895191/24086991/ea972682-0d3e-11e7-9c3c-beddeabc235e.png)

With 4 values rendering properly
![image](https://cloud.githubusercontent.com/assets/1895191/24087000/039f8ffc-0d3f-11e7-9822-09c7d07f7a87.png)

**Comment by alansouzati** [comment]
Thanks for this issue. I'm adding a codepen for folks that want to easily reproduce this:

http://codepen.io/alansouzati/pen/dvddbz?editors=0010

**Comment by dgennetten** [comment]
@ericsoderberghp it looks like this component is behaving as designed (though not as expected). Width is cased in the scss for up to only 4 bars?https://github.com/dgennetten/grommet/blame/master/src/scss/grommet-core/_objects.meter-bar.scss#L221.  Any thoughts on how best to resolve?

**Comment by ericsoderberghp** [comment]
I seem to recall there a few cases where Meter doesn't want more than four values in the series. I think circle, arc, and spiral all have this limitation due to constraints in available space. My recommendation is to update the documentation and add a console warning to indicate that Meter doesn't take more than four values in a series, when not stacked.

For more values as bar meters one can use a Box containing single value Meters to accomplish something similar.

**Comment by dgennetten** [comment]
Docs updated to detail current series-length limitations
