### ISSUE TITLE
Anchor animation causes scrollbar in Header

### ISSUE THREAD

**Issue by jozsi** [grommet/grommet#1254]
When hover an Anchor link with an animated icon, inside a Header, an unexpected scrollbar appears (I noticed it only starting the 1.3.x branch).

Codepen: http://codepen.io/anon/pen/OpvXBN
Screenshot:
![screen shot 2017-03-21 at 19 08 52](https://cloud.githubusercontent.com/assets/840815/24160319/21112ae2-0e6a-11e7-909f-78213edcf8f3.png)

**Comment by alansouzati** [comment]
I don't think there is a way out of this. Eventually you will run out of real state. I've fixed the way we animate icons so that you can disabled it if you wish.

Another possible solution is to add a small horizontal padding to give space for the animation. The following codepen does that:

http://codepen.io/alansouzati/pen/qrompj?editors=0010

I'm going to close this issue for now. Feel free to reopen it if you have a better idea on how to solve this issue.
