### ISSUE TITLE
Embedding HPE Fonts with Deployment (not use AWS)

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1268]
We build a product that is planned to be deployed in organizations that do not connect the deployment machines to the internet.
The default HPE fonts are fetched from AWS S3. We want to embed them with our deployment.

I've try to redirect `$hpe-fonts-path` to `node_modules/grommet/scss/hpe/font` but it causing the resulting SCC file to have the following font url in it: `http://localhost:3000/app08febe75cf58d264f16ca1fc3a2965c8.woff`.
Not the `app` the the beginning there is part of our application URL.

**Comment by psales** [comment]
Hi,
you could take a look into the file-loader:
https://github.com/webpack-contrib/file-loader

you can specify the destination folder to where the file will be generated as well as the name (instead of an md5 hash by default)

something like this:
`{ test: /\.(woff|woff2)$/, loader: 'url-loader?prefix=font/&limit=5000&name=font/[name].[ext]' }`

**Comment by alansouzati** [comment]
are you still facing this problem @ido-ran ?

**Comment by alansouzati** [comment]
can you add your `$hpe-fonts-path` to `/grommet/scss/hpe/font` ?

**Comment by ido-ran** [comment]
This problem has been resolved. It requires the addition of `url-loader` as well as `file-loader` and changing `$hpe-fonts-path`. I think it worth adding this information to the documentation.

**Comment by nickjvm** [comment]
@ido-ran can you share your webpack loaders config? I'm running into the same issue.

@alansouzati is this process documented anywhere?
