### ISSUE TITLE
NumberInput to include Units and Formatting fn

### ISSUE THREAD

**Issue by Sitch** [grommet/grommet#1269]
Would be great to be able to use the NumberInput with currency / other units.

Not sure what the preferred way would be but following the Value args:

`
<NumberInput value={25000} icon="$" displayFormat={::this.currencyFormat} />
`

This could be done without the `icon` attribute or could use `units` or just all done in the `displayFormat`.  The point is that it maintains the number type, but with a different display format.

**Comment by bjackson** [comment]
This would be great. I think all we need would be the ability to put the units on the left instead of the right.

**Comment by alansouzati** [comment]
Thanks for the suggestion and sorry for taking such a long time to get back to you on this.

I would avoid mixing currency with number. Currently NumberInput is just a tiny wrapper around the native `<input type="number" />`.

There are libraries that handles internationalization stuff like react-intl and they do have format for currency. We would have to handle scenarios like "1.000" vs "1,000" which definitely adds complexity to the NumberInput.

Here is a codepen that uses Grommet + React Intl

https://codepen.io/alansouzati/pen/ZymqEz?editors=0011

I'm closing this issue since I believe there is nothing to be fixed in Grommet. But feel free to continue the discussion, we can always reopen the issue if we identify something to fix.
