### ISSUE TITLE
Contents in Footer of Sidebar appear below bottom of screen in mobile browsers

### ISSUE THREAD

**Issue by mturley** [grommet/grommet#1270]
I am observing this issue in Ferret, but also in our application that uses a similarly structured NavSidebar component (`<Sidebar> ... <Footer><SessionMenu /></Footer></Sidebar>`).

I considered reporting this issue on the grommet-ferret repo, but since we are seeing it in our application too, i figured it is more likely to be an issue with grommet itself.

Visit http://ferret.grommet.io/dashboard on a mobile device (tried in Chrome on Android and in Safari on iPhone), then use the top-left menu to open the navigation sidebar menu.  The issue has to do with the height of the sidebar, which is affecting the position of the session (logout) menu.

### Expected Behavior

The session menu should appear at the bottom of the screen, and the navigation menu should not need to scroll vertically.

### Actual Behavior

The navigation menu appears to take up slightly more than 100% of the viewport height, and the session menu is not visible on the screen until the user scrolls down.  There is no indication that you should need to scroll down, so it may be confusing to find the logout option.

It seems that this happens on mobile browsers because the address bar is pushing the page down, and the amount you can scroll down is equal to the height of the address bar (when you scroll and the address bar is hidden, the menu takes up the full screen size.  I'm guessing that 100% height of the window is reporting as 100% of the device screen height.  I'm not sure how this could be fixed, but with such an important button placed somewhere that is offscreen on a mobile browser with no indication that it is there, this seems like a pretty big flaw in the mobile experience.

### URL, screen shot, or Codepen exhibiting the issue

http://ferret.grommet.io/dashboard

Screenshot without scrolling down (session menu not visible, no indication that you need to scroll to see it):

![screenshot_20170327-083230](https://cloud.githubusercontent.com/assets/811963/24357071/67eb0bae-12ca-11e7-8459-d925ed612dbd.png)

Screenshot after scrolling down (address bar hides, session menu visible):

![screenshot_20170327-083225](https://cloud.githubusercontent.com/assets/811963/24357115/93fa6226-12ca-11e7-86c2-9a841b4a8d28.png)

These screenshots are in Chrome for Android, but I am observing the same behavior in Safari on iPhone.

### Steps to Reproduce
 1. Visit http://ferret.grommet.io/dashboard on a mobile device
 2. Open the navigation menu
 3. Observe that the page can be scrolled and the session menu cannot be seen until you scroll down.

### Your Environment

* Grommet version: 1.3.3
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): Android 7.1.1

**Comment by dgennetten** [comment]
Seems to be working as expected on chrome, safari, edge and IE -  OSX and Win10

**Comment by tracybarmore** [comment]
Hi @mturley, I have also replicated this issue on Chrome browser on my Android device. It looks like if you hide the browser header, it works as expected. But, I would agree that isn't intuitive. I'm leaving this issue open to discuss with the team. Thanks!

**Comment by mturley** [comment]
@dgennetten, it's only an issue on mobile browsers.  I am able to reproduce it on Safari and Chrome on an iPhone, and in Chrome on and Android device.

@tracybarmore, thanks!

**Comment by karatechops** [comment]
This is a tough one and one I've encountered in apps I've worked on, not just Grommet. When we define a height to be `100vh` in Safari it does not include Safari's bottom navigation bar. The height of the browser's bottom nav is not deducted from the the height of the browser, this is intentional on Apple and Android's part. Please refer to this [blog post](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html#february-23rd-update) for more details.

There are workarounds you can use in your apps if you'd like to go that route but I would just suggest using a different style of layout instead. the workaround involves targeting specific browsers which use this sort of footer nav and adding a style override that looks like `style={{ minHeight: 'calc(100vh - 70px)' }}` - where 70px is the height of the browser's bottom nav. Again - I don't suggest using this in your app.

There's not much we can do in Grommet's core to fix this, the full box is doing its job at setting the height to 100% view height. Targeting specific browsers on specific devices is definitely not a rabbit hole I'd suggest going down.

I'm going to close this for now to keep Grommet's backlog clear. Feel free to re-open if someone comes up with a solution we can line into Grommet. In the case that someone does find a solution I will buy them a beer 😄

**Comment by lukaw3d** [comment]
Browsers have added lvh / svh / dvh units to solve this in the mean time
