### ISSUE TITLE
Disable Toggle buttons option for NumberInput

### ISSUE THREAD

**Issue by raphi011** [grommet/grommet#1277]
I would love an option to disable to +/- buttons on the NumberInput component because:

1. they take up a lot of space
2. if you have multiple NumberInputs you have to tab 3 times until the next numberinput gets focused

### Expected Behavior

Prop that disables the +/- inputs on NumberInput

### Actual Behavior

Currently not possible

**Comment by alansouzati** [comment]
Any reason why you are not using `<input type="number" />` they have controls that are way smaller. The hit target for those are terrible in my opinion, but it does has the features you are looking for.

Check this codepen:

http://codepen.io/alansouzati/pen/KmwgPr?editors=0010

I'm going to close this issue since I believe there is nothing we would want to simplify in the NumberInput. Feel free to reopen if you think otherwise.
