### ISSUE TITLE
Select doesn't use whatever is in the option's label as each dropdown item does

### ISSUE THREAD

**Issue by mandx** [grommet/grommet#1297]
I can provide options with React elements as labels and each dropdown item renders them perfectly. But when one of those items is selected, I can only see the `value` of the option, not the contents of the `label`.

### Expected Behavior
I should be able to see the same React elements in the select box I see in the dropdown item I just selected.

### Actual Behavior
I only see the option's `value` (an UUID in my concrete case, not very usable)

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/mandx/pen/evqWNr

### Steps to Reproduce
```javascript
// Codepen's content, in case it gets lost
const OPTIONS = [
  {value: 'value1', label: <span><Status value="ok"/>Value 1</span> },
  {value: 'value2', label: <span><Status value="warning"/>Value 2</span> },
];

class HelloWorldApp extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  
  render () {
    const { currentValue } = this.state;
    return (
      <App>
        <Title>Hello World</Title>
        <p>Hello from a Grommet page!</p>
        <Select
          options={OPTIONS}
          value={currentValue}
          onChange={event => { this.setState({ currentValue: event.option })}}
          />
      </App>
    );
  }
};

var element = document.getElementById('content');
ReactDOM.render(<HelloWorldApp />, element);
```

### Your Environment
* Grommet version: 1.3.2

**Comment by SuhairZain** [comment]
The reason is [this line](https://github.com/grommet/grommet/blob/cf3e5b4dbfc25ea2c0b964dee1e402f623d28d26/src/js/components/Select.js#L313) in the current 1.3.4 version which checks if the label is a string. This is needed because an `<input/>` component is used to display the selected option and we can only pass a string to it. You can thus display the label by using a simple string instead of a React element.

However, this has been changed in #1306 which uses the value if it exists and uses the label only as a fallback.

@aandr Any ideas on how to fix this? I too am of the opinion that it should be the option's label that should be displayed, not the value.

**Comment by mandx** [comment]
[This gist](https://gist.github.com/mandx/a48fbd37a4853fc1a47bb7d47eba27e2) shows what I'm using right now (ignore the changes on the `import` lines). Is far for complete, it works for my use case now, but here's the main idea: Render the label (which could be a React element) inside a span which has some styling to match the "input" box, and then use one hidden input[type=checkbox] to represent the selected value (or several, if `props.multiple=true`).

Another thing to consider is what text value should be used to search if the label is a React element.

**Comment by jmfadeley** [comment]
Any forward motion on this?

**Comment by aandr** [comment]
Apologies for the silence on my end. We no longer use Grommet in our
project and I won't be able to dedicate the time for a follow-up PR.

**Comment by alansouzati** [comment]
Here is a codepen that does what you are looking for. The underlying element of the select is an input hence the string requirement. 

https://codepen.io/alansouzati/pen/jwaOyB?editors=1010

The idea is to hold the displayValue in a separate property and use that for the `Select` value.

**Comment by mrboomer** [comment]
@alansouzati 

Using your method works, but then it doesn't append the appropriate classes to that particular option. In my case, I am allowing multiple options to be selected, and therefore need those classes to display the option as selected.

My issue currently only exists when only one item is selected, since I am doing something similar to your example, and applying a displayValue only when one item is selected.

**Comment by Primajin** [comment]
What is extra weird, is that [Sort](https://grommet.github.io/docs/sort) has a completely different behaviour. Here the label of the active option is used inside the Select (as desired in this issue here), while the dropdown lacks the class for the active option (as the [previous comment](https://github.com/grommet/grommet/issues/1297#issuecomment-312132477) states).

@alansouzati  Can't we have both? Dropdown with label as value **and** selected option highlighted in dropdown?

**Comment by Primajin** [comment]
I found out that this can be resolved if I not pass **either** the `value` or the `label` to the `value attribute`, but **both** in an object similar to the objects in the array that get passed to the `options attribute`_ - Must have overread that in the docs! Maybe with this we can also fix the behaviour of Sort to not only accept a `String` as a `value` but also a `label-value-pair-object`

https://github.com/grommet/grommet/issues/1601
