### ISSUE TITLE
Search suggestion scrolling

### ISSUE THREAD

**Issue by raphi011** [grommet/grommet#1302]
When scrolling a long suggestion dropdown the focused element gets out of sight.

### Expected Behavior
Suggestions should scroll to highlight the current active suggestion

### Actual Behavior
Suggestions don't scroll, highlighted suggestion is not shown

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/xdKVBo

### Steps to Reproduce
 1. Fill Search with many suggestions
 2. Scroll down with arrow keys

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Linux

**Comment by alansouzati** [comment]
Thanks for reporting this @raphi011.

Although the current structure behaves as expected. 

There are a lot of limitations with auto scroll to active suggestion. 

For example, we support multiple active suggestions and it is not clear which element we should scroll.

In terms of UX, I would limit the number of suggestion with the top 10 matches. If the user wants better suggestions he can always provide a more detailed text. This is our recommended pattern.

Also take a look at this codepen where I created something that might help you:

https://codepen.io/alansouzati/pen/GErJNm

I'm closing this issue because I believe there is nothing to be fixed in Grommet. feel free to continue the discussion here. We can always reopen the issue in case we feel something needs to be fixed.
