### ISSUE TITLE
min css not working

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1321]
### Expected Behavior
import 'grommet/grommet.min.css'  should give the right fonts 

### Actual Behavior
the font is wrong, sans-serif instead of "Work Sans"

### URL, screen shot, or Codepen exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/16700996/25371132/b33ebd92-2997-11e7-8ce5-218dabd5353b.png)

### Steps to Reproduce
 1. integrate grommet with create-react-app
 2. import 'grommet/grommet.min.css'; 
 3. add a grommet component to App
4. all fonts are wrong

### Your Environment
* Grommet version: 1.3.4
* Browser Name and version: chrome 57
* Operating System and version (desktop or mobile): desktop  Mac Sierra

**Comment by SuhairZain** [comment]
Hi @shai32,

I tried the steps you mentioned and I believe I have found the issue.

Are you using the Grommet App component as your root component? The Grommet styles are applied to the components only if they have an App Component as their parent. This is because the 'Work Sans' font is only applied to the class **grommet** and this is applied only for the **App** component. Check the screenshot for more details
![screen shot 2017-04-26 at 2 19 49 pm](https://cloud.githubusercontent.com/assets/5249794/25426299/4acb32e0-2a8c-11e7-98d7-b0b69bbcc198.png)

The minimal code that can get you the required styles is:
```jsx
<App>
  <Label>Hello?</Label>
</App>
```

**Comment by shai32** [comment]
@SuhairZain thanks it works.
whats worried me that I didn't notice it in the doc. it should be the first step in integrating Grommet App.
Do you have a doc link for App Component?

**Comment by SuhairZain** [comment]
Hey @shai32,
The documentation is available at https://grommet.github.io/docs/app/. In some way, it says that it should be the root component:
> This is the primary Grommet container outer. Typically it will either contain a Split or an Article.

**Comment by RyanCCollins** [comment]
I am going to close out this issue so that it's not appearing on the grommet team's backlog.  Please feel free to keep the convo going!
