### ISSUE TITLE
selenium test with PhantomJS on a page containing Accordion fails

### ISSUE THREAD

**Issue by thomas-romuald** [grommet/grommet#1336]
selenium test with PhantomJS on a page containing Accordion fails (works with Firefox and Chrome).
Works if the Accordion part is commented out. 

### Expected Behavior
Automated test with selenium on a page with Accordion.
Expected that panel containing Accordion appears.

### Actual Behavior
Works on real browser, but fail with PhantomJS. We got the message:
![image](https://cloud.githubusercontent.com/assets/13487830/25652591/d6046b5c-2fe0-11e7-9af9-678a1038ad6c.png)
Works if the Accordion part is commented out. 

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/13487830/25652753/a7a9faaa-2fe1-11e7-8321-dd19f0ab2032.png)

### Steps to Reproduce
 1. appears only with selenium test using PhantomJS on a page with Accordion.
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: PhantomJS 2.1.1
* Operating System and version (desktop or mobile): Jenkins

**Comment by thomas-romuald** [comment]
Hi @tracybarmore is there any news about this issue?

**Comment by alansouzati** [comment]
hey @thomas-romuald I'm trying to reproduce this issue. We don't use Selenium. It seems that the invariant 136 relates to trying to call `setState` when the component is already unmounted. By looking at the Accordion source code I cannot identify anything that could be causing this issue.

Here is the [source code](https://github.com/grommet/grommet/blob/master/src/js/components/Accordion.js) for the Accordion if you want to take an extra look. There is no setTimeout, or setInterval. I've seen cases where this problem happens if you forget to unassign these listeners inside `componentWillUnmount`.

**Comment by thomas-romuald** [comment]
Hi @alansouzati  yes the component has the ``componentWillUnmount()`` specified.

This issue was present only while using **phantomJS**, but it's fine with selenium running on real browser (Chrome, Firefox). Before having accordion in a page test could run successfully on **phantomJS**.

So we stopped to use **phantomJS**.

**Comment by karatechops** [comment]
Closing this for now, it sounds like this is resolved as you've moved away from phantomJS. [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) seems like it would be a really good option here. I see a lot of strange behavior with phantomJS and React.
