### ISSUE TITLE
Please provide clear documentation on how to apply brand colors

### ISSUE THREAD

**Issue by ravenberg** [grommet/grommet#1364]
Over here at the Learn/color https://grommet.github.io/docs/color page it is stated that; 

> It is expected that applications will define their own brand color scheme.

But there are no guidelines on how to override these defaults. Please provide some documentation on this.

**Comment by dgennetten** [comment]
@alansouzati @lozzi I propose we address this by documenting-while-creating a grommet-alt theme.

**Comment by RyanCCollins** [comment]
We just recently added theming to the Grommet CMS and were talking about doing custom themes.  Let me know if you need any help with this!  I'd be happy to help.

**Comment by alansouzati** [comment]
Fully agree. We need a better documentation for that. We are in the works for Grommet 2.0 and we will be changing the way we do things regarding theming and SCSS. So we will provide documentation for that once we have Grommet 2.0 out!

I'm closing this issue because we have already one open to track this:

https://github.com/grommet/grommet/issues/704

I'm looking forward to releasing Grommet 2.0 soon along with proper documentation on how to create customizable themes.
