### ISSUE TITLE
TableRow component not hoverable?

### ISSUE THREAD

**Issue by JohnDevitt** [grommet/grommet#1368]
I've noticed that the cursor doesn't seem to change when hovering over a table row even when onClick callback is provided.

Not sure if this is a bug or expected behaviour(someone suggested it may be expected so that users can copy the text from a table row easier). Seems a bit odd because everything else that can be supplied with an onClick prop is hoverable(Box etc). Seems to be the case for both chrome and firefox. 

Here's an example of a table(that isn't hoverable) and a box that is: http://jsfiddle.net/69z2wepo/79491

**Comment by adamroldfield** [comment]
See the docs for Table, there's a selectable and onSelect property there that will do what you're looking for.

**Comment by alansouzati** [comment]
thanks @adamroldfield you are exactly right. 

The idea behind the `onClick` prop name for Box is: often times you click on it to go somewhere else. 

On the other hand, the intent for Table is for you to select it and do some operation like delete, specially during a bulk operation mode. That's why we have different names for these two components. Hopefully it makes sense.

I'm closing this issue as I believe there is no action item here.
