### ISSUE TITLE
Format is not a function

### ISSUE THREAD

**Issue by csethanhcong** [grommet/grommet#1371]
After upgrade `grommet@1.4.0` to `1.4.1`, I got this error:
> dateObj.format is not a function .....

I found out that the root cause come from this line: `https://github.com/grommet/grommet/blob/master/src/js/components/Timestamp.js#L107`

Maybe something wrong at the `dateObj` assignment before, we should cast `date` to Date object like previous version. Ref: `https://github.com/grommet/grommet/blob/master/src/js/components/Timestamp.js#L107`

**Comment by alansouzati** [comment]
Thanks for reporting this and for going the extra mile to investigate the problem. I've pushed a fix for this here:  https://github.com/grommet/grommet/commit/abbdae96be5965233c13e6c17c2af9abfb5fb614

In the meantime, you have two options:

1) Convert your date to String before calling Timestamp.
2) Using Stable branch in Grommet with the fix for it (it will be soon part of 1.4.2). we just release 1.4.1 yesterday.

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
