### ISSUE TITLE
Menu stays jammed on double click

### ISSUE THREAD

**Issue by przytrzask** [grommet/grommet#1382]
### Expected Behavior
Menu dropdown should close itself on click outside or second click itself
### Actual Behavior
If menu drop-align is "bottom" and one drop is already opened and you clik twice on other menu it jams on second click and stays in this behaviour forever.

### URL, screen shot, or Codepen exhibiting the issue
The first and third are with drop-align: "bottom" and will break while the second one element will behave normally.
https://codepen.io/przytrzask/pen/OgXMBv

### Steps to Reproduce
 1.  click on the second menu once
 2.  then click on the first menu twice
 3. click the second and then first twice

### Your Environment

* Grommet version: 1.4.0
* newest chrome/firefox
* windows 10  / linux

**Comment by alansouzati** [comment]
Very weird, thanks for identifying this. I was able to reproduce this issue. Let me try to fix it

**Comment by alansouzati** [comment]
This is actually a Chrome bug. I cannot reproduce it in any other browser.

I added a work-around for this issue in this commit: https://github.com/grommet/grommet/commit/c31d7d106f2f5c580bcf5370320a703b68014342

The problem was even though we are calling `removeChild`, Chrome seems to execute that successfully but does not remove the child for some weird reason :(
