### ISSUE TITLE
pt-BR is being unnecessary imported

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1397]
### Expected Behavior
only english should be imported as default language

### Actual Behavior

Two languages are being imported\
https://github.com/grommet/grommet/blob/dbdbaed72e3e9e32e1d28f4c8465c264efb8f87f/src/js/components/App.js
![image](https://user-images.githubusercontent.com/16700996/27357337-71ab9bc0-561a-11e7-8e5a-d8cd8962b799.png)
causing my client bundle to be larger
![image](https://user-images.githubusercontent.com/16700996/27357366-988b2418-561a-11e7-936b-46cf8780f665.png)

### Your Environment
node 7
grommet 1.4.1

**Comment by alansouzati** [comment]
Agreed we will revisit this for Grommet 2.0. 24kb is not the end of the world and removing this now could lead to breaking changes for existing apps.

I will leave this issue open and close it after releasing Grommet 2.0

**Comment by shai32** [comment]
Thanks

**Comment by adamroldfield** [comment]
@shai32 what tool produces that diagram? Thanks!

**Comment by shai32** [comment]
@adamroldfield source-map-explorer

**Comment by roytz** [comment]
Can we remove this default import?

**Comment by shai32** [comment]
now that 2.0.0-alpha.0 is rolling out, can we make this issue active again.
It's a simple fix really, just removing the redundant require

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by alansouzati** [comment]
This is already fixed in 2.0.

We cannot remove this in 1.x as it will lead to breaking changes.

I'm really sorry that you have to have these extra peaces in there. In the bright side, it is only 24kb without gzip, so the difference in the final bundle size should not be that big.

I'm closing down this issue since it is already fixed in 2.0 and it will not be removed in 1.X.

Feel free to continue to discussion here.
