### ISSUE TITLE
dynamicly import languages

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1398]
I am using the latest webpack that support dynamic import 
so I am trying to add dynamic import to languages (my app should support many languages)
in order to do that, I created an helper: 

```
import { getCurrentLocale, getLocaleData } from 'grommet/utils/Locale';
import { IntlProvider, addLocaleData } from 'react-intl';

async function getLocaleDataAsync() {
    const locale = getCurrentLocale();
    const translations = await import(`./translations/${locale}`);
    const localeData = await import('react-intl/locale-data/${locale}');
    addLocaleData(localeData);
    return getLocaleData(translations, locale);
} 
```

the problem is with this line 
    `const localeData = await import('react-intl/locale-data/${locale}');`
the files inside locale-data is en.js, ar.js, ro.js while local is ar-jo, en-us, ro-mo
so there are different, how can I import the right file when I Have the local value?

**Comment by alansouzati** [comment]
interesting concept. it is the first time I see **await** being used for webpack, so thanks for sharing that.

Yeah the way react-intl `addLocaleData` function works is by receiving the language, not the locale. Although, they have the locale specificity inside the object returned by `import('react-intl/locale-data/${locale}')`.

To solve this mismatch in the file names I would do a string replace. getCurrentLocale is just returning whatever the browser configuration is.

For example:

```
  const locale = getCurrentLocale();
  const language = locale.replace(/\-.*/i, '');
```

`en-US` would be replaced to `en` to get the language.

Hope it helps.

I'm closing this issue since I believe there is nothing to be changed in Grommet. Please feel free to reopen if you disagree.
