### ISSUE TITLE
Select with Search is unusable on mobile

### ISSUE THREAD

**Issue by justinglibert** [grommet/grommet#1401]
When you provide a "onSearch" function to Select, the component is unusable on mobile. Focusing the text area brings the keyboard at the same height and you can't select any option in the list

### Expected Behavior
The dropdown should be on the **top** of the component
### Actual Behavior
The dropdown is behind the virtual keyboard

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/anon/pen/gRRELg?&editors=0010

### Steps to Reproduce
 1.  Use a Select Component
 2.  Add a onSearch function
 3.  Open the dropdown on mobile

### Your Environment

* Grommet version: v1.4.1
* Browser Name and version:Chrome on Android (latest)
* Operating System and version (desktop or mobile): Android Nougat

**Comment by alansouzati** [comment]
I tried it on few android devices and it does come on top but as soon as you type they set the focus again in the search field. I'm afraid there isn't anything we can do in our end to fix that. Thoughts?

**Comment by justinglibert** [comment]
It really depends on the situation, in a modal it doesn't open on the top of the element (which is really annoying)

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alansouzati** [comment]
I don't think we can control that in our end. Do you have any suggestions? 

One solution would be to use another component like the native select specifically for mobile. The problem with the select is that it is not a native control and I cannot figure out a way that it would work for you, unless you have something in mind.

Checkout our responsive utils that allows you to know if a Grommet app is in a mobile context.

https://grommet.github.io/docs/responsive/

I'm going to close this issue because I believe there is nothing to be done in the grommet side of things. Feel free to reopen it if you got a solution in mind.
