### ISSUE TITLE
[Feature Improvement] LoginForm Component reuse

### ISSUE THREAD

**Issue by sclanc** [grommet/grommet#1407]
It would be nice to have a buttonText prop on the LoginForm component so I could change the 'Log in' text on the submit button to say 'Create account' Everything else would stay the same, I tried figuring it out on my own but things get a little hairy in there.  Here's what I changed, if you could tell me what I missed that would be great. 

in LoginForm.js:
 I added a line between 162 -163 that read `buttonText = _buttonText`
Then changed 210 to be `var login = _react2.default.createElement(_FormattedMessage2.default, { id: 'Log In', defaultMessage: _props.buttonText });`

in my App.js: 

I added the buttonText prop to the LoginForm component which spurred an error which indicated that buttonText was not a valid property, so I reverted the changes. 

Thanks a bunch for your help.

**Comment by alansouzati** [comment]
Thanks for raising this issue. LoginForm component should not live inside Grommet core components just because of the reasons your outlined here. It is a very high level component that can lead to these needs for customizations. We will be moving LoginForm to `grommet-addons` project, this repo will host components that will both serve as a reference that you can copy, but also a ready-to-use component in case the design matches with your needs.

The idea behind these components will be to have some flexibility but not a lot of that, in case you need something very specialized you can copy the component source code and change it to match your needs.

In your case I believe you need a Signup component which will be semantically different than the LoginForm. It looks odd to have a `LoginForm` component that has a button that says 'Create Account'.

I'm closing this issue because I believe you will need a separate component anyways.
