### ISSUE TITLE
Icon change in many components

### ISSUE THREAD

**Issue by Slumber86** [grommet/grommet#1413]
We are trying to change the icon in the the select component. The problem is that the icon is hardcoded in the component. It would be nice to pass the the icon element as a child or as a property to allow more customization of the framework whitout forking it or without ugly CSS hacks

With a quick search the hardcoded icons are found in:

- Select
- NumberInput
- Search
- SocialShare
- AccordionPanel
- CirclePlayIcon
- DateTime
- Carousel
- Menu

If i'm missing any component please let me know.

**Comment by alansouzati** [comment]
Thanks for this issue.

Where it makes sense we will allow for the icon to be changed, for example Menu does support the icon prop https://grommet.github.io/docs/menu.

Search is an example of a component that we will not allow changing the icon because we cannot see a reason for that. If we allow this we will open for this kind of things: `<Search icon={<BackIcon />} />` . This is definitely dangerous. Another use case that is exposed with this kind of thing is having two search components in the same application with different icons, which can leave to inconsistencies in your UI.

I agree some of our icons look rather big, we may add support for properties like `size` which in this case will allow the icon in the corresponding component to change the appearance a little bit.

Hopefully it all make sense. I'm closing this issue for now but feel free to continue the discussion. We can reopen the issue if we decide to support `icon` prop across the board.

**Comment by Slumber86** [comment]
Hi Alan,
thanks for the answer. I think that the problem is not well uderstood. 
The base problem is not to use a different icon chosen beetween the grommet icon set, but our customer asks for custom design of some standard components (specifically the select and accordion arrows) that don't match exactly with grommet default design, so we want to use custom icon components.
The icons are not skinnable via CSS, so we have two choices: fork the framework to replace svg paths or use some dirty tricks with CSS to hide the default icons and replace them with ours.
Obiously fixing this without using props is a breaking change, and can be done in many ways:

- Exporting the icons as peerDependancy
- Placing the paths in CSS
- ..suggestions?

If you have a better solution to solve this problem, please let me know.
