### ISSUE TITLE
NumberInput Box allows all characters [IE specific]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1418]
Numberinput box allows all the characters in the box, except for "e" all the other characters should not be allowed, this behavior is only present in IE
### Expected Behavior

Except for "e" all the other characters should not be allowed, this behavior is only present in IE
### Actual Behavior

Numberinput box allows all the characters in the box, except for "e" all the other characters should not be allowed, this behavior is only present in IE
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/number-input

### Steps to Reproduce
 1. just open this link in IE
 2. 
 3. 

### Your Environment

* Grommet version: Current
* Browser Name and version: IE 11.0.9600.18697IS
* Operating System and version (desktop or mobile): Desktop Windows

**Comment by alansouzati** [comment]
This is not bug. Check this page:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Grommet NumberInput is just an `<input type='number />` with extra style (like the plus and minus buttons).

I would recommend subscribing to the onChange if you want the content of this form input to be number only. 

I believe the best experience is to let the user type anything he wants and add a form validation when the user submits the form.

I'm closing this issue because I believe there is nothing to be fixed in Grommet.

**Comment by agrawalPratik** [comment]
okkk thanks @alansouzati, I will let you know if I have further queries on this.

**Comment by agrawalPratik** [comment]
Hi @alansouzati,

My team tried to use onchange event to solve this issue as per our product requirement,

Solution works for all the browsers except for IE11

The problem in IE is when the input box doesn't have a default value box even after handling through onchange event user can still enter characters and when input box have default value handling done is successful and user can't enter characters.

Below is the codepen link, issue is reproducible when NumberInput does not have any default value,
https://codepen.io/anon/pen/zdxQpq

But, when NumberInput has default value, user can not enter characters, below is the codepen,
https://codepen.io/anon/pen/ayOOWd

This issue is observed only in IE.

Please suggest on this.
