### ISSUE TITLE
Table#onMore not called in nested Splits

### ISSUE THREAD

**Issue by tvojtech** [grommet/grommet#1428]
On big screen in layout with two nested `Split`s `Table#onMore` does not get called on blank screen.

Maybe related to https://github.com/grommet/grommet/issues/1427 but probably not.

Caused by commit https://github.com/grommet/grommet/commit/bfc03b1b18c4e579e997766d007ecd45a256ad72 added to 1.5.0 release. `document` does not get to result of `DOM.findScrollParents`. Because of condition in https://github.com/grommet/grommet/blob/master/src/js/utils/InfiniteScroll.js#L56 that never passes, initial `onMore` call does not occurr.

### Expected Behavior
`Table#onMore` should be called on blank screen to load data.

### Actual Behavior
`Table#onMore` does not get called and spinner is displayed forever. 

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/blaf/pen/zzbWBB

### Steps to Reproduce
 1. See the codepen. Window must be wide enough to show both splits.

![image](https://user-images.githubusercontent.com/1427446/28228928-dae32ef4-68e0-11e7-80fd-3f2d31e69392.png)
 
### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): Mac OS Sierra

**Comment by karatechops** [comment]
I'm not able to replicate this issue and the Codepen seems to be functioning correctly in OSX / Chrome / Grommet 1.7.0. As I believe this to be fixed in 1.6.0 I'm going to close the issue.

**Comment by tvojtech** [comment]
Still not fixed (Grommet 1.7.0). I double checked it in latest Chrome and and Safari (Version 11.0 (12604.1.38.1.7)) and didn't work. Just submit the url and do not touch the page. You should see endless spinner. Once you scroll or resize viewport (e.g. open chrome console) `onMore` gets called.

**Comment by jfiala-cz** [comment]
@karatechops Please reopen this defect. Try the Codepen example again - the spinner won't disappear until you cause a rerender or scroll the screen. It is broken across all browsers - behaves exactly the same in FF, Chrome, Edge...

The defect can even be (rarely) noticed in the grommet documentation, which means there do not even need to be two Split components for this bug to appear.
![image](https://user-images.githubusercontent.com/34236839/33776443-a9926cfa-dc41-11e7-89f1-c957e7373769.png)
(more items will not load unless I scroll/resize the page)

**Comment by karatechops** [comment]
I'm still not able to reproduce this but maybe someone else can. @jfiala-cz or @tvojtech are you able to create a PR with a fix?

**Comment by jfiala-cz** [comment]
I'll try to fix it next week.

**Comment by L0ZZI** [comment]
@jfiala-cz any update on this?

**Comment by jfiala-cz** [comment]
We have 'a' solution we use in our project (patching grommet during build), but I was hoping to come up with a better one before submitting it here.

Our current solution is removing the `if` condition around `result.push(document);` in `findScrollParents()` ( https://github.com/grommet/grommet/blob/master/src/js/utils/DOM.js#L38 ).

The problem is not just about nested Splits. On Windows, this codepen example does not work correctly in Chrome and Firefox (it only works in Edge suprisingly). Only when resizing the window are more items loaded:

https://codepen.io/anon/pen/MQKaWv

You can uncomment our fix in the codepen example. It works with all browser and I am not aware of any side-effects, but I am sure there is a better way to fix this (didn't get the time to investigate this further yet).

Can anyone comment on our fix?

**Comment by L0ZZI** [comment]
Super weird. I'm seeing it in Chrome. Odd thing is when I shrink the browser window down to a smaller size the rows load but only for a second. I'd need someone at a higher pay grade to check it out. Maybe @alansouzati, @karatechops, or @ericsoderberghp can take a look.
