### ISSUE TITLE
LoginForm Does Not Render and throw error, NEED HELP

### ISSUE THREAD

**Issue by Hackbyrd** [grommet/grommet#1429]
### Expected Behavior
Render LoginForm successfully

### Actual Behavior
When I try to render LoginForm, I get this error
<img width="1680" alt="screen shot 2017-07-16 at 1 41 42 am" src="https://user-images.githubusercontent.com/1607004/28245006-92b113dc-69c9-11e7-9cef-6ec48a5ae295.png">

### Steps to Reproduce
 1. Install react-boilerplate
 2. npm install grommet --save
 3. add "import 'grommet/grommet-hpe.min.css';" to app.js
 4. import LoginForm from 'grommet/componets/LoginForm'
 5. It fails when page loads   

### Your Environment
Lastest version as of 7/16/2017

**Comment by tusharkhatiwada** [comment]
@Hackbyrd Can you share your code too?

**Comment by Hackbyrd** [comment]
I only changed 4 files from the react-boilerplate repo after installing grommet

1. app/containers/homepage -- tried to import and render LoginForm (Failed)
2. app/app.js -- added import 'grommet/grommet-hpe.min.css';
3. package.json -- npm install grommet, and added "grommet" to "dllPlugin"
4. internals/webpack.base.babel.js -- added '.json' to resolve.extensions

<img width="633" alt="screen shot 2017-07-16 at 3 13 38 pm" src="https://user-images.githubusercontent.com/1607004/28250555-72aee5da-6a39-11e7-8627-c00ea9741de3.png">
<img width="320" alt="screen shot 2017-07-16 at 3 13 23 pm" src="https://user-images.githubusercontent.com/1607004/28250557-72b0542e-6a39-11e7-9ea6-93090a42a795.png">
<img width="459" alt="screen shot 2017-07-16 at 3 13 08 pm" src="https://user-images.githubusercontent.com/1607004/28250556-72aefeee-6a39-11e7-94ac-b66b2bb3fcce.png">
<img width="898" alt="screen shot 2017-07-16 at 1 43 11 am" src="https://user-images.githubusercontent.com/1607004/28250558-72b0a8fc-6a39-11e7-9132-8915038a535a.png">

**Comment by Hackbyrd** [comment]
@tusharkhatiwada I posted my code above

**Comment by karatechops** [comment]
@Hackbyrd, thanks for filing this issue. Are you still encountering this issue or was it resolved? If you are still encoutering an issue please submit a [Codepen](http://codepen.io/pen?template=gaEGPY&editors=0010) displaying the behavior, screenshots can be very difficult to read.

**Comment by karatechops** [comment]
I'm going to close this as no testable code has been provided. Judging by the error this is going to stem from how you're exporting/importing the component. @Hackbyrd please feel free to re-open the issue when a gist or Codepen is provided.

**Comment by panigrah** [comment]
I think I may know what your problem is @Hackbyrd  - but I do not know how to resolve.

GrommetFormattedMessage puts a wrapper on `react-intl.FormattedMessage`. `react-intl.FormattedMessage` needs the textComponent to be available in the context. But this textComponent property is always null in the context. Thats the error message. 

I have not worked out yet why the context.intl object that should get initialized in the `LanguageProvider` component does not make the `textComponent` property available.

If you change the `GrommetFormattedMessage` to always use `span` then the error goes away and the app renders the LoginForm. 

BTW you will have this issue in many other components - anywhere the FormattedMessage is used.

@karatechops any idea why the textComponent would be missing from the intl context?

**Comment by panigrah** [comment]
@Hackbyrd I think I worked out how to fix. 

Upgrade your react-intl package to the latest 2.4.0 in the react-boilerplate. The version of react-intl you have likely does not setup a default value for the `textComponent`. 

2.4.0 sets the default value for the textComponent and the error goes away.
