### ISSUE TITLE
Tile without Tiles ancestor sometimes throws exception 

### ISSUE THREAD

**Issue by drewlustro** [grommet/grommet#1435]
When a `<Tile>` has no `<Tiles>` ancestor, grommet 1.5.0 has an uncaught exception.

### Expected Behavior

The documentation does not note consequences to using `<Tile>` without a `<Tiles>` parent, so this exception should be guarded against.

### Actual Behavior

Grommet throws an exception when trying to access ancestor `tiles.scrollWidth`

#### Relevant code: compiled `Tiles.js`

```js
 key: '_layout',
    value: function _layout() {
      var direction = this.props.direction;


      if ('row' === direction) {
        // determine if we have more tiles than room to fit
        var tiles = (0, _reactDom.findDOMNode)(this.tilesRef);

        // 20 is to allow some fuzziness as scrollbars come and go
        var newState = {
          overflow: tiles.scrollWidth > tiles.offsetWidth + 20, // <-- EXCEPTION THROWN
          overflowStart: tiles.scrollLeft <= 20,
          overflowEnd: tiles.scrollLeft >= tiles.scrollWidth - tiles.offsetWidth,
          scrollWidth: tiles.scrollWidth
        };
    }
    // ....
  }

//...
```

#### DevTools Screenshot

<img width="1158" alt="screen shot 2017-07-20 at 12 46 31 pm" src="https://user-images.githubusercontent.com/194885/28429100-8274dc5a-6d49-11e7-9c2c-60d095ae1846.png">

### Steps to Reproduce

Can't seem to repro consistently, but happens when Grommet attempts to determine if it should render the "next" + "previous" arrows that normally paginate through many `<Tile>`'s.

I assume that grommet `1.5.0` assumes there is a `<Tiles>` ancestor with a `ref` set.

Something like:

```jsx
<Tiles ref={(ref) => this.tilesRef = ref}>
```

### Your Environment

* Grommet version: `1.5.0`
* Browser Name and version: Chrome 59.0.3071
* Operating System and version (desktop or mobile):  macOS 10.12.5 / desktop

**Comment by RyanCCollins** [comment]
Hey @drewlustro!  Thank you very much for reporting this.  To me, this seems like a great opportunity for you to contribute, if you are interested!  It would seem to me that the more exception handling we can add to safeguard against confusion, the better.  If you are able to, go ahead and open a PR with a proposed fix.  Otherwise, I will keep this issue open for the grommet-core team.

Thanks again!

**Comment by drewlustro** [comment]
@RyanCCollins – I'm already a contributor! ;)

I would love to help out more, but Grommet takes forever to build on `gulp`. Any tips for getting it to build faster on my machine?

![screen shot 2017-08-17 at 1 36 56 am](https://user-images.githubusercontent.com/194885/29397498-96a0094e-82ec-11e7-8170-fc8bfd58273c.jpg)

**Comment by alansouzati** [comment]
yeah I agree that our current build time sucks :)

The good news is that Grommet 2.0 builds much faster, and we are not using gulp.

I also agree that if we depend on Tiles be present as a parent we should at least make it more clear in the documentation. Let me take a look inside Tiles source code to determine if we should require that. I will keep you posted.

**Comment by alansouzati** [comment]
I believe this problem is related to a timeout problem. That's why it is an intermittent behavior. I tried to reproduce this but I was not able to. I added a commit that I believe will fix the problem by clearing the timeout when component unmounts, here is the commit:

https://github.com/grommet/grommet/commit/029d0491d968bfb0ecc0bcebb753802bc072cbc9

I'm closing the issue for now. We can reopen if the problem persists. Thanks for reporting this.
