### ISSUE TITLE
Firefox alignment issue in key-value pair [Firefox specific only]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1445]
There has been UI glitch noticed in firefox browser wherein if the value string length is more instead of left aligned it gets centered aligned in the container
### Expected Behavior

Value should be left aligned and should be wrapped if container is not big
### Actual Behavior

Value gets centered aligned and creates visual clutter in the Key- Value pair section
### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/geetaverma/pen/vJYXop

### Steps to Reproduce
 1. Please use codepen and open it in firefox
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: Firefox 54.0.1
* Operating System and version (desktop or mobile): Desktop, Windows

**Comment by karatechops** [comment]
Hey @agrawalPratik I've reviewed the issue and need some clarification. I see you set the Box basis to `1/2` but you also set a size to the box as `small` - which behavior are you expecting from the box, `1/2` or `small`? Additionally in this scenario I would absolutely avoid using flex boxes within tables. If you'd like to use a table use table's accepted html tags (`tr`, `th`, etc) to create your layout instead of Boxes. 

I created a fork of your [Codepen](https://codepen.io/anon/pen/QMewZg?editors=0010) which I believe fixes your issue by explicitly setting the Box's `align` property. I also noticed you may be running into an issue with words being too long, this can be solved by the `word-wrap` css property as you see in the Codepen.
