### ISSUE TITLE
Revisit how Heading, Headline, Label, Paragraph, and Title work together

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1502]

**Comment by ericsoderberghp** [comment]
Currently, I'd like to propose removing Title and Headline and doing everything with Heading, Label, and Paragraph

 I'd also like to re-use our t-shirt sizing approach for Heading as follows: `tag` would be used for semantic and accessibility purposes. `size` would be used for styling purposes. This would allow the page to have an smaller h1 but larger h2 or h3 tags for stylistic emphasis. Thus, Title and Headline would be folded into Heading.

I'd also like to see a few more stylistic options with Label so it can be used more. Today, I've seen Paragraph get used for what semantically should be a Label just because of the styling.

Thoughts?

**Comment by linde12** [comment]
@ericsoderberghp I like the idea of removing Title and Headline and use Heading instead. I'm always confused with which one i should use.
