### ISSUE TITLE
Should I use grommet v1.x?

### ISSUE THREAD

**Issue by lugrugzo** [grommet/grommet#1510]
Hello

I'm thinking about switching from material design to Grommet, it looks so good. However I saw you are preparing to create v2. 

Should I use v1.x? I know coding process for v2 will be long process but the application I will be switching is large and would like to stick with 1.x or wait for next release.

Thanks for great library.

**Comment by alansouzati** [comment]
I would recommend checking this wiki page: https://github.com/grommet/grommet/wiki/Why-Grommet-2.0%3F. Especially the "What is going to break?" section.

I understand that you would like to avoid two big refactors in a short span. But if you follow what is described in this Wiki I believe your second refactor will be very small.

I'm going to close this issue since I believe there is nothing to be fixed in Grommet. But feel free to continue the discussion. Welcome to Grommet
