### ISSUE TITLE
TextInput does not show suggestions on first user's input

### ISSUE THREAD

**Issue by Gehbrial** [grommet/grommet#1549]
### Expected Behavior
TextInput's suggestions should always show up when the user types something

### Actual Behavior
The suggestions list does not show up on the first user input.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/Gehbrial/pen/jLVpdz

### Your Environment
* Grommet version: 1.6.0
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Windows 10

**Comment by karatechops** [comment]
Hey @Gehbrial, thanks for filing this issue. It looks like TextInput is expecting an array with length instead of a 0 length array on the initial render. I've [added an empty string to your initial suggestions array](https://codepen.io/karatechops/pen/PKgEeK?editors=0010) and that seems to fix the issue. I'm going to take a deeper look at fixing this within Grommet but for now you can use that fix in your app.

**Comment by alansouzati** [comment]
Thanks for fixing this @karatechops

**Comment by Gehbrial** [comment]
Thank you very much! :)
