### ISSUE TITLE
Checkboxes and radio buttons don't have a "name" attribute in the Select component.

### ISSUE THREAD

**Issue by jlevesque** [grommet/grommet#1553]
This is more a suggestion than an issue.
It's not required by any official web guideline, however it can be very useful for form validation or serialization. It's mostly used for POST and GET request, but it is also useful in JS. Since the Select component creates a group of input, the name attribut can be the same. At least for the radio, I'm not sure the checkbox. 

### Expected Behavior
Checkboxes and radio buttons have a "name" attribute when rendered in a Select component.

### Actual Behavior
Checkboxes and radio buttons don't have a "name" attribute in the Select component.

### URL, screen shot, or Codepen exhibiting the issue
![screen shot 2017-08-09 at 9 53 17 am](https://user-images.githubusercontent.com/6978875/29125057-b8bb8dd2-7ce8-11e7-8897-4db8b73d9b33.png)
![screen shot 2017-08-09 at 9 54 03 am](https://user-images.githubusercontent.com/6978875/29125058-b8be2498-7ce8-11e7-86e2-33085340db4f.png)

### Your Environment
* Grommet version: 1.6.0

**Comment by karatechops** [comment]
Hey @jlevesque, thanks for filing this issue. I don't see why we couldn't just use the same attribute for the `name` property as the `id` property. The IDs for the radio buttons are automatically generated so the `name` property would be something like `${selectId}-${optionValue}` - would that fit with what you're looking for?

Are you using React/Grommet more in the form of widgets rather than in the context of a full Javascript application? Generally the tracked form's state is being submitted to an API rather than using the default HTML event so I'm curious to hear about your use case.

**Comment by karatechops** [comment]
Closing this as no additional information was provided.

**Comment by jlevesque** [comment]
@karatechops  Sorry, I was out of the country for a while. The use case I had was doing a serialize on a form. Usually, the serializing methods take the input's name has a reference. I've noticed that currently the checkboxes and the radio button are not serialized. I think it's more a suggestion than a issue.

What do you think? Using serialization for a frontend validation.
