### ISSUE TITLE
window.scrollTo(0,0) is broken

### ISSUE THREAD

**Issue by Slumber86** [grommet/grommet#1586]
### Expected Behavior
`window.scrollTo(0,0)` should make the page scroll to the top

### Actual Behavior
Nothing happens

### URL, screen shot, or Codepen exhibiting the issue
http://ferret.grommet.io/dashboard

### Steps to Reproduce
 1. Going to http://ferret.grommet.io/dashboard scroll to the bottom
 2. type `window.scrollTo(0,0)`and press Enter

### Your Environment
* Grommet version: 1.7
* Browser Name and version: Chrome and Firefox latest versions
* Operating System and version (desktop or mobile): Windows and OSX

**Comment by RyanCCollins** [comment]
Hey @Slumber86, since the split element creates it's own scrollable region, it's logical that `window.scrollTo(0,0)` would not scroll the split.  I think you're looking to scroll the split element to the top, in which case you could grab the dom element and set its [`scrollTop`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop).

I'll post a giphy to illustrate this.

**Comment by RyanCCollins** [comment]
@Slumber86 in an effort to help clear up the Grommet team's backlog, I am going to close this issue.  Please feel free to keep the convo going if you have any further concerns.  Thanks!

**Comment by Santiago8888** [comment]
Hi @RyanCCollins, I could not make it work.

But even if I could I was expecting to use the smooth property.

I ended up using anchor tags, instead.

It would be nice to have the native scrollto implementation.
