### ISSUE TITLE
Wrong SocialShare Email mailto: Link

### ISSUE THREAD

**Issue by Kaitsh** [grommet/grommet#1628]
The mailto: link in the SocialShare email component is wrong. Therefore the "to" email address is put into the body of the email.

### Expected Behavior

The provided email address should not be in the "to" field of the email client.
### Actual Behavior

The provided email address appears in the email body

### Your Environment

* Grommet version: 1.7.0
* Browser Name and version: Firefox Nightly (57.0a1) and Chrome Beta (62.0.3202.18)
* Operating System and version (desktop or mobile): linux 4.12 Kernel (desktop)

### Solution
The mailto link should be:
```javascript
href = 'mailto:'+encodedLink+'?subject=' + (encodedTitle + '&body=' + encodedText);
```

**Comment by karatechops** [comment]
Hey @Kaitsh, thanks for filing this issue. I've created a [Codepen](https://codepen.io/karatechops/pen/OxNJoV?&editors=0010) displaying SocialShare's mail behavior. Just to clarify - when a SocialShare email opens the `to` field is appending with data instead of the message body? Can you submit a screen shot of how your email client handles the Codepen's mail share? I'm not able to replicate the issue with either desktop mail clients (Postbox, Outlook on OSX) I use.

**Comment by Kaitsh** [comment]
Hi @karatechops, 
Thanks for your reply.
I'm sorry, it was a wrong configuration in my email client. So the issue was on my side.
