### ISSUE TITLE
React dependencies as peer dependencies

### ISSUE THREAD

**Issue by anpieber** [grommet/grommet#1635]
I was just trying to use grommet with react 16 (beta) and discovered that the included deps on react 15 are creating some troubles. On the risk of saying something really stupid, but wouldn't it be an option using react as a peer lib?

**Comment by karatechops** [comment]
I'm actually on board with this however it will potentially open the floodgates with issues. This would definitely need to be slated for Grommet 2.x. @alansouzati @ericsoderberghp, what do you guys think?

**Comment by alansouzati** [comment]
Good point. I've been using peer dependency for some of the gulp packages that I've written. For example `gulp-jest`. This use case seems to be the standard for gulp libs since gulp is just a tiny wrapper around the underlying lib.

On the other hand, Grommet + React relationship is a much stronger linkage and having that as a peer dependency seems to relax that boundary which seems risky as we rely on the React lifecycle functions. Using the caret (e.g. `^15.6.0`) seems like the right solution. Thoughts?

FYI, I'm in the process of updating Grommet 1.X and evaluating if there is any breaking change to it. If there is a breaking change we will be forced to wait to move to React 16 when we release Grommet 2.0.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/bc7f04bb54a1ddead0fd436bb6635f6056dd649e
