### ISSUE TITLE
Why Form and FormField is not included in Grommet by default?

### ISSUE THREAD

**Issue by vojtasvoboda** [grommet/grommet#1717]
I'm getting this error: `'grommet' does not contain an export named 'Form'.`

### Expected Behavior
It should import Form and FormField to create basic form.

### Actual Behavior
It throws `'grommet' does not contain an export named 'Form'.`.

### Steps to Reproduce
 1. create-react-app my-app; yarn add node-emoji; yarn add gommet;
 2. To App.js add `import { Form, FormField, RadioButton } from "grommet";`
 3. To App.js add `<Form><FormField>...</FormField></Form>`

### Your Environment
MacOS, npm 5.5.1, gommet 2.0.0-alpha.3, react 16.0.0.

**Comment by atanasster** [comment]
"Currently, Grommet 2.0 does not provide Form or FormField components"

https://v2.grommet.io/form

**Comment by alansouzati** [comment]
Thanks @atanasster, you are exactly right.

If you are using v2, please refer to the [temporary site](https://v2.grommet.io) for reference.

I'm closing this issue since I believe there is nothing wrong here.

If you are curious to understand why we don't have form, the reason is that we believe you can achieve the same using Grommet v2 Boxes.

See this [codesandbox](https://codesandbox.io/s/github/grommet/grommet-site?initialpath=form&module=%2Fscreens%2FForm.js) for reference

**Comment by mjsevilla** [comment]
@alansouzati I'm trying to view the code sandbox on the v2 Grommet website and I'm getting an error saying it cannot be found? [Link](https://codesandbox.io/s/github/grommet/grommet-site?initialpath=form&module=%2Fscreens%2FForm.js) What gives? I've been trying to make a simple form in Grommet in for the last 3 weeks and no one has been helpful whatsoever. The v1 docs on forms are useless (especially if forms are phased out in v2) and the v2 docs are still in development.
