### ISSUE TITLE
Latest grommet alpha package from npm missing Tabs/Tab etc.

### ISSUE THREAD

**Issue by kavink** [grommet/grommet#1721]
I just did a fresh install of grommet and seems like 2.0.0 alpha is missing Tabs package in component from npm, Maybe im doing something wrong ?

**Comment by alansouzati** [comment]
The latest official release is 1.8.3 and it does include all the components described in https://grommet.io.

If you want to explore Grommet v2, you can refer to this temporary site: https://v2.grommet.io.

We still do not have Tabs as part of Grommet v2.

I'm closing this issue since I believe there is nothing to be fixed here. Feel free to continue the discussion  here.
