### ISSUE TITLE
Forms could use with more vertical space

### ISSUE THREAD

**Issue by donkeybonks** [grommet/grommet#1753]
Tested on Safari Mac OSX and Safari iPhone 6

Controls look great, but some combinations of controls feel inconsistent when used together.

Spacing between headers and paragraphs is too small and feels off grid.
Spacing between headers and form controls is too small and feels off grid.

More white space is needed so that it is easy to distinguish the relation between headers and their corresponding block content. At the moment I am associating headers with individual fields due to lack of white space.

For an example of on-grid spacing see Sassline.

**Comment by donkeybonks** [comment]
![edb5d83b-2784-4bdc-b7b8-5771d6a138ec](https://user-images.githubusercontent.com/1356959/33227672-4a6a6506-d1fc-11e7-8aff-9ff090c46458.jpeg)

Spacing consistency is lacking here too

**Comment by donkeybonks** [comment]
![4d372a85-4d49-4b46-9559-9408e9245090](https://user-images.githubusercontent.com/1356959/33227688-cf63aab0-d1fc-11e7-8b31-21a0d3425c24.jpeg)

Doesn’t align with grid here.

**Comment by L0ZZI** [comment]
Thanks for the feedback. The Indent with the icons is due to the viewBox being larger than the icon so there is a larger click target for the element. Without offsetting controls like icons, we use the indentation to help parse the information semantically. It also gives us a nice pad when highlighting items in lists or menu component like this case. 

As for the button spacing below the form, you can can control the spacing between which can be found here, http://grommet.io/docs/padding

let me know if this answers your questions.
