### ISSUE TITLE
Text input inside Select component is not customizable

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#1972]
It would be nice if the "searchable" Select component accepted a React Element as a prop that wrapped the text input to allow for customization.

**Comment by ericsoderberghp** [comment]
Can you provide an quick description of the kinds of customization you have in mind? I just want to make sure we are understanding the request.

**Comment by alansouzati** [comment]
currently we do not expose a way to extend the styles inside the Select search. for example: using plain text input instead of the default one that has border. I think we have a couple of options:

1) Have a prop called `searchProps` in `Select`. I don't like this option a lot since it does not scale well (not very themeable). 

2) Inside the select vanilla theme we could expose an option to use a custom TextInput, similar to what we do with the icons.

```
class MyCustomSearchInput extends Component {
  render() {
    return <TextInput  plain={true} .../>
  }
}

{
   select: {
      searchInput: MyCustomSearchInput,
   }
}
```

Thoughts?

**Comment by alansouzati** [comment]
The current situation is that we have to clone the Select entirely just because we could have a custom style for the search text input.

**Comment by ericsoderberghp** [comment]
My current inclination on this is to add a `header` property and let the caller include whatever they want in it, similar to `header` on AccordionPanel.

**Comment by alansouzati** [comment]
well. the search has a lot of implications for select. I feel if we do the `header` approach, we will have some weird things like "don't use `onSearch` if you are passing header". Plus, for every search used we have to remember to use the `header` prop. This does not feel very "themeable" to me.

My preference is still the `searchInput` inside the theme. If you are ok with that I can craft a PR for this.
