### ISSUE TITLE
Themes - possibly no dependencies on styled-components

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1974]
Possibly better to not have styled-components dependencies in the themes and keep color names instead. 
Avoid issues like FormField, that was using the border color in code, and ease future migrations

**Comment by atanasster** [comment]
Another downside of styled-components in themes is that it will require some javascript (and styled-components) knowledge from theme designers.

**Comment by alansouzati** [comment]
I don't think it is possible to remove styled-components from the vanilla theme. Let me explain you why (and I'm open to suggestions if you have a better idea on how to solve the problem).

Take for example the [Menu](http://v2.grommet.io/menu), we want to allow developers to use a different icon as opposed as the default FormDown from grommet-icons. There are few ways to solve this:

1) **Pass an `icon` prop to Menu**. Problem here is that you would have to pass this prop to all menus in your app. or create another component just for the sake of hosting the extra icon property.
2) **Configure the menu icon prop in the theme**. This allows all Menu instances to inherit this icon. This feels more natural and [this was the approach we took](https://github.com/grommet/grommet/blob/NEXT/src/js/themes/vanilla.js#L466).

To achieve the level of dynamism that we envision for grommet v2 theme, we don't see it as a regular object, otherwise we would have named it `vanilla.json`. There is a reason for vanilla to be a javascript module.

If you want a custom theme, it is expected that you will need to know CSS in JS, or in our case, styled components. We already expose `extend` and this is a concept ported from `styled-components`. This was similar in v1, you want a custom theme we would need to know SASS.

I'm going to close this issue because I believe there is nothing to change here.

Thanks for bringing this up.
