### ISSUE TITLE
v2 Improve Button docs for "plain" prop

### ISSUE THREAD

**Issue by goodmorninggoaway** [grommet/grommet#2088]
### Expected Behavior
The docs for Button's `props.plain` should include the fact that you must pass `children` exclusive of `props.label` and `props.icon`.

### Actual Behavior
It's implied in #2019 but not included in the docs.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/goodmorninggoaway/pen/ERRpJK?editors=0011

### Steps to Reproduce
See CodePen

### Your Environment
* Grommet version: grommet@2.0.0-beta.3 
* Browser Name and version: Chrome 67
* Operating System and version (desktop or mobile): MacOS 10.13.5

I can submit a PR next week if it's not already done.

**Comment by alansouzati** [comment]
hey thanks for reporting this.

Actually with the latest grommet this will not be required anymore. 😄

I'm working on a new release for v2. I'm closing this issue since I believe there is nothing to be changed.

But in case you see an improvement to the plain description you can do so [here](https://github.com/grommet/grommet/blob/NEXT/src/js/components/Button/doc.js#L61)
