### ISSUE TITLE
V2 - Button font color changes when setting color

### ISSUE THREAD

**Issue by mvilrokx** [grommet/grommet#2258]
According to the v2 documentation the color property on the Button component controls "Fill color for primary, border color otherwise", however, setting the color property for a primary Button also sets the font color (to "#444" it seems).  The normal font color for the primary button is "white".  Why is the font color changed from "#FFF" to "#444"?

### Expected Behavior
The font color of a primary button should stay as is ("#FFF")

### Actual Behavior
The font color of a primary button changes to "#444" when using the color property

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/8ryoym1y0

### Steps to Reproduce
 1.  Use Button component and set primary=true
 2. On same Button component, add color property
 3. Notice fontColor change from white to #444 (regardless of what color is set to)

### Your Environment
* Grommet version: 2.0.0-beta.5
* Browser Name and version: Chrome 68.0.3440.106 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS High Sierra 10.13.6

**Comment by mvilrokx** [comment]
For whatever reason, the codesandbox link above doesn't seem to be working for me so in case it's not working for anybody else, this is what I had in there:

```
import React from 'react';
import { Button } from 'grommet';
import SandboxComponent from './SandboxComponent';

export default () => (
  <div>
    <SandboxComponent>
      <Button primary label='White Text' onClick={() => { }} />
    </SandboxComponent>
    <SandboxComponent>
      <Button primary color="#000" label='Why No White Text?' onClick={() => {}} />
    </SandboxComponent>
  </div>
);
```

**Comment by atanasster** [comment]
@mvilrokx I see there was no follow-up on your issue and will jump in trying to help.
The problem is that `Button`, when a color is supplied calculates the text color depending on the background behind the button (which is light in this case), not based on the background color for the button as it should. So it thinks its a white background and applies the corresponding text color (blackish). 

If its a pressing issue for you, here is a sample with a temporary fix (swaps temporarily the light/dark text colors in the theme):
https://stackblitz.com/edit/grommet-demo-avshee?file=index.js

**Comment by alansouzati** [comment]
I will try to take a look at this early this week.

**Comment by ericsoderberghp** [comment]
This was an issue with our color parser not handling short hex values. `#000000` would work. We are updating grommet to handle `#000` though.
