### ISSUE TITLE
Warning: Failed prop type: Invalid prop `weight` supplied to `Text`.

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2302]
Incorrect warning being displayed in the console.

### Expected Behavior
No warning.

### Actual Behavior
Grommet shows a warning when adding a weight property to the Text component.

### Steps to Reproduce
 1. Create a text component with a weight propery

### Your Environment
* Grommet version: beta6
* Browser Name and version: Chrome 69.0.3497.100
* Operating System and version (desktop or mobile): MacOS Desktop

**Comment by ericsoderberghp** [comment]
I can't seem to reproduce this. If I have `<Text weight="bold">TEST</Text>`, I don't see any warning in the browser console, using storybook.

**Comment by atanasster** [comment]
https://stackblitz.com/edit/grommet-demo-2ck9qv
`<Text weight ='700'>Test</Text>`

**Comment by ericsoderberghp** [comment]
From https://v2.grommet.io/text, that should be `<Text weight={700}>Test</Text>`

**Comment by atanasster** [comment]
There are more pressing bugs in v2 and I was just helping to reproduce the issue, however i will add that the documentation is *definitely* not clear that it should be {700}, but i concede that most of the v2 documentation is also inadequate.

**Comment by alansouzati** [comment]
I agree we could improve there.

it is not clear that `normal` and `bold` are actually `string` instances, and number is actually a type.

`<Text weight="bold" />`
`<Text weight="normal" />`
`<Text weight={700} />`

We need to improve the documentation.

I will create a separate issue for that in grommet site since it affects more components.

Thanks for the feedback @atanasster
