### ISSUE TITLE
Is it possible to customize font size settings?

### ISSUE THREAD

**Issue by twelve17** [grommet/grommet#2326]
I saw in https://github.com/grommet/grommet/issues/704 some info on how to create a new theme.  I've been trying to follow the pattern on that issue somewhat, to customize the font sizes.  

I found, in the grommet-core scss folder, that there is a [`_settings.font.scss` file](https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_settings.font.scss), which has some font size variables defined.  

I created a `index.scss` file in my project:
```
@import 'mytheme.defaults';
@import "mytheme.settings.font";
@import '~grommet/scss/grommet-core/index';
```

`mytheme.settings.font` contains some font definitions (with the `!default` removed just in case):

```
$brand-font-family: Helvetica, sans-serif;
$brand-large-number-font-family: Helvetica, sans-serif;
$code-font-family: Consolas, Menlo, 'DejaVu Sans Mono', 'Liberation Mono', monospace;

$text-font-weight: normal;
$text-strong-font-weight: 600;
$control-font-weight: 600;

$content-font-size: 13px;
...
```

It does not seem to affect the font sizes at all, though.  Perhaps I'm attempting to override the font settings in an incorrect way?

### Your Environment
* Grommet version: 1.11.0
* Browser Name and version: Chrome 69.0.3497.100
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
Today our font-size calculation with v1 is based from `$inuit-base-font-size`. Take a look [here](https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_base.grommet-only.scss#L26). You could override this value. But still the following calculation will be applied.

`($inuit-base-font-size / 16px) * 1em`

You can also override that manually.

In your `mytheme.settings.font` you would do: 

```
.grommet {
  font-size: ...;
  line-height: ...;
}
```

Since you may be starting with Grommet now. I want to bring to your attention grommet v2. https://v2.grommet.io. We are releasing it soon (currently in beta). I would recommend starting with that instead of v1.
