### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by murbanowicz** [grommet/grommet#2446]
Hello,
This is not really an issue, but kind of question/request.
I came across `grommet` yesterday and I love it already, however, 2.0 is still missing quite a few components etc.
Do you have or can you prepare and publish any roadmap, please?
It would help with 2 key questions: **what can we expect** from grommet in the coming time and **how can we contribute** :)

**Comment by alansouzati** [comment]
Fair enough. What sort of components you think it is missing?

Our approach with v2 is to be somewhere in between native HTML5 components and fully opinionated component libraries.

Think it like a lego where you can combine pieces to create something richer.

For example, in v1 we used to have a `Card` component. It was very opinionated and hard to reuse in other companies. Card is not a component in v2 and that's intentional. We feel that you should be able to create any card pretty easily with our Box component.

**Comment by alansouzati** [comment]
Regarding roadmap, we are in the process of figuring out how to operate now that we have v2 out. Our backlog of issues is open and when we are working on something we make them as `in progress`. We are trying to do a better job marking issues that are "good first issue".

We are planning to release hot fixes very often.

For new components and features we will have a minor release and the cadence will be on a need basis.

We are not anticipating any major breaking change, since we have just released v2.

**Comment by murbanowicz** [comment]
I understand this approach and it somehow makes sense. It allows creating additional packages by people with additional components build on top of Grommet.

About the missing components, first of all, I think time picker in one or two versions should be present in the core.

Have you thought about going mono-repo and scoped packages to make it cleaner? 
We would then have `@grommet/core`, `@grommet/icons` etc. Just an idea :)

**Comment by alansouzati** [comment]
I'm open to mono repos. I've started to use it in a few projects. I feel this is more like a v3 thing. We just released v2 and I'm wanting to avoid having breaking changes like this. Hopefully this makes sense to you.

**Comment by ShimiSun** [comment]
RoadMap issue is tracked on #3271, feel free to comment/post your comments.
