### ISSUE TITLE
Would be nice to customize/disable the animation in Layer

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2578]
Also reference #2387 
### Expected Behavior
It would be nice if you could control the animation when the Layer appears.

**Comment by RobertGary1** [comment]
Customized animation seems to be make sense but for my needs I just need to disable it.

**Comment by oorestisime** [comment]
The animation disable has been merged. are there any other actionable items here? Should the layer support different kind of animations like the Box? which is looking something along the following

```
const ANIMATION_TYPE = PropTypes.oneOf([
  'fadeIn',
  'fadeOut',
  'jiggle',
  'pulse',
  'slideUp',
  'slideDown',
  'slideLeft',
  'slideRight',
  'zoomIn',
  'zoomOut',
]);
const ANIMATION_SHAPE = PropTypes.shape({
  type: ANIMATION_TYPE,
  delay: PropTypes.number,
  duration: PropTypes.number,
  size: PropTypes.oneOf(['xsmall', 'small', 'medium', 'large', 'xlarge']),
});
``` 

imho it doesn't make much sense for the layer component but ...

**Comment by ShimiSun** [comment]
I agree with you @oorestisime. I'd like to hear @ericsoderberghp thoughts

**Comment by ericsoderberghp** [comment]
I think some of those, combined with `position`, probably don't make sense. How we've tended to approach topics like this is wait for a design or request to show up that seems like a good thing to add, rather than adding things because we can. We are always trying to keep a little negative pressure against growing the API surface and amount of code wherever possible. But, if there's a few interesting animations that seem valuable, I'm open to exploring.

**Comment by RobertGary1** [comment]
I only suggested customizing the animation because it has an animation now that you can’t change but for me I just wanted to turn it off.

**Comment by ShimiSun** [comment]
Thank you. 
since we addressed the main issue of disabling the animation, I'll be closing this request.
Feel free to file a new issue with requests for more animation options that we can explore, in case you find it valuable.
