### ISSUE TITLE
Anchor should have a pad property

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#2595]
### Expected Behavior

Anchor should have a pad property
### Actual Behavior

Anchor has only support for margin

**Comment by shai32** [comment]
I want the entire Anchor will be clickable, if the padding will be with a Box. all the padding space is not part of the Anchor and it will not be part of the link

**Comment by shai32** [comment]
@ShimiSun nice solution, I can use it.
but still, I think if Anchor support margin, it should support padding as well

**Comment by ShimiSun** [comment]
@petercpwong thank you for the feedback, we'll discuss and consider.

**Comment by ShimiSun** [comment]
We haven't seen community enthusiasm to support this feature, and we are keeping in mind that Anchor is not a component that is intended to drive Layout so `pad` shouldn't be necessary. 
I'll be closing this issue unless an interest will rise.

**Comment by issogno** [comment]
Saying that there is no "community enthusiasm" on a fairly unkown framework, does not feel right.

I started experimenting with grommet for a new website I am working on, and just one week after I am already falling into this issue and encountering a "lack of enthusiasm" on listening to your users. 

This is not a good sign for a new framework with a small user-base.

**Comment by jcfilben** [comment]
Hi @issogno just wanted to give some context on why this enhancement was passed over. We try to evaluate enhancements based on usefulness and interest from the community. We try to balance adding new features with not bloating the repository with too many props and making it more difficult to maintain and use. (Side note: this is an interesting [podcast episode](https://kentcdodds.com/chats/02/09/erik-rasmussen-chats-with-kent-about-maintaining-open-source-libraries) with Kent C. Dodds and Erik Rasmussen related to this topic)

For this specific feature it felt like adding an additional prop wasn't necessary since Anchor shouldn't be driving the layout and the desired behavior can be achieved in another way. We also didn't see +1's or requests from the community for this besides the initial author. However, that being said even if we close an issue and then interest arises in it later, we are always willing to revisit and discuss. The door is alway open :)

**Comment by mrmagcore** [comment]
I'm with this very old thread.  Why does anchor have margin if it doesn't have pad?  Even wrapped in a box with pad="none", it still sets a large pad around the anchor.  Either don't add a pad around the anchor or allow us to set pad.

**Comment by mrmagcore** [comment]
Sorry, looks like anchor only has a pad around icons, not text.  Still weird that it has margin at all if it doesn't have pad.

**Comment by mrmagcore** [comment]
If that's your philosophy regarding pad, that's fine, but it seems inconsistent that Anchor puts a pad around icons.

This produces a pad around the icon:

   <Anchor icon={<Icons.Edit/>} />

This does not:

   <Anchor label="Edit" />

**Comment by jcfilben** [comment]
Good comment, the reason we include extra padding on Anchors and Buttons with icons only is so that the click target is large enough to meet accessibility requirements

**Comment by mrmagcore** [comment]
That's fine as a default, but I feel like I should then be able to adjust that pad within the grommet system without having to address it by adding a class/css or inline style.  It breaks the pattern of keeping most of that styling within grommet.

**Comment by jcfilben** [comment]
Hey @mrmagcore just wanted to give an update. I chatted with other members of the grommet team and we are open to having the `pad` prop on Button. It feels like there are cases where it is helpful to be able to adjust this, especially for icon only Buttons. We are thinking we won't support having `pad` on Anchor and instead encourage people to use Button for situations where they would use and icon only Anchor.

**Comment by mrmagcore** [comment]
Thanks for considering my input!
