### ISSUE TITLE
Pagination control

### ISSUE THREAD

**Issue by Rakshaki** [grommet/grommet#262]
Is there a Pagination control built using Grommet? Can you give us an example?

**Comment by alansouzati** [comment]
Hi @Rakshaki good question. Can you describe more on what you are trying to achieve with the pagination component.

I'm guessing you are trying to add long list with paging capabilities. If this is the case, have you considered doing infinity scrolling? 

[grommet-index](https://github.com/grommet/grommet-index) offers a set of components that helps with rendering mass quantities of data. Check the [List](https://github.com/grommet/grommet-index/blob/master/src/js/components/List.js) component for reference implementation in the infinity scrolling.

We are working on adding proper documentation for grommet-index so that you don't have to poke into the code to see what's going on.

**Comment by bryanjacquot** [comment]
Pagination control is not currently planned.  We continue to recommend infinite scrolling with rich search and filtering.
