### ISSUE TITLE
[DataTable] customize groupBy property

### ISSUE THREAD

**Issue by yuriyKovalchuk** [grommet/grommet#2661]
When groupBy property is used, would be great to have an ability to collapse only rows which have duplicate value.
### Expected Behavior

When groupBy property is set, would be great to collapse only rows with duplicated value (which chosen in the groupBy property)

### Actual Behavior

When groupBy property is set, all rows in a table are collapsed. 
### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/zw26jw243m

**Comment by ShimiSun** [comment]
@jensy @L0ZZI @MikeWalrath we need some design inputs here :)

**Comment by L0ZZI** [comment]
Thanks @yuriyKovalchuk for the feedback! Are you looking for a `prop` that would automagically group and collapse the rows with identical content or specific column data?

I don't know if this would be generic enough to have at the component level as I see a bunch of ways this could be interpreted. The reason I was asking if it was a specific column is if you're keying on that and the other columns are more secondary then you could have a pattern that would make sense to your users, otherwise without seeing a more detailed example it will be hard to ascertain how to make this more extensible for everyone else and also how to help solve this. 

Have seen an example of this in another framework? Keep us updated.

**Comment by lanzeron** [comment]
Hey @L0ZZI, thanks for your reply.
Actually, my point was about grouping rows by specific column, but only rows which have identical content in a specific column, which I set in groupBy property, not all rows.
For example, I have rows:
![image](https://user-images.githubusercontent.com/13054851/53194046-30aa6100-361b-11e9-8091-e110e93dc838.png)
in this case if I put 'name' column in the groupBy property would be great if only first two rows are grouped, because they have identical value 'Rob', other rows should be not grouped, something like that:
![image](https://user-images.githubusercontent.com/13054851/53194876-170a1900-361d-11e9-8912-a422729f3631.png)

Please let me know if this case needs more clarifications here,
maybe you know some other way how I can implement this behaviour without groupBy property

**Comment by dgennetten** [comment]
@lozzi @yuriyKovalchuk  What is needed here is more generic -- and I believe warrants a new prop.  The idea is to not hide groups where there is only one element.  

That is, for this table ('Simple DataTable' in Storybook):
![image](https://user-images.githubusercontent.com/3402646/56427552-8f860280-6279-11e9-8a4d-c41cd2106209.png)

Rather than this collapsed view:
![image](https://user-images.githubusercontent.com/3402646/56427595-b2b0b200-6279-11e9-954d-ec8820a90f8c.png)

It would be more generally useful to show this view:
![image](https://user-images.githubusercontent.com/3402646/56427633-d673f800-6279-11e9-9648-2db53f1ed32b.png)

I would like to move ahead with this prop if no objection.  Not sure what the prop name should be. Any suggestions?

**Comment by ShimiSun** [comment]
Just to make a side note, I published this issue on grommet-slack, Thursday, April 4th and we didn't receive any additional feedback or votes on this issue. https://grommet.slack.com/archives/C04LMHN59/p1554433031094300

**Comment by ShimiSun** [comment]
@dgennetten, @yuriyKovalchuk can this issue be closed?

**Comment by ShimiSun** [comment]
Got a confirmation fro @dgennetten! Thank you for your contribution!! 💯 ❤️
