### ISSUE TITLE
Calendar displays -1 day with zero hours.

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2685]
On Calendar, one minus day gets selected when passing date with zero hours. 

### Expected Behavior
With `date="2018-11-04T00:00:00.000Z"`, Nov. 4 should get selected.

### Actual Behavior
With `date="2018-11-04T00:00:00.000Z"`, Nov. 3 gets selected.

### URL, screen shot, or Codepen exhibiting the issue
<img width="1333" alt="screen shot 2019-01-23 at 10 13 30 am" src="https://user-images.githubusercontent.com/8532807/51616460-23089b00-1ef8-11e9-9df0-2efd94b4c232.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by srockk** [comment]
This might be expected behavior? Workarounds are:
1. `date="2018-11-04T05:00:00.000Z"` add offset hours
2. `date="2018-11-04T00:00:00.000"` local

**Comment by ShimiSun** [comment]
@srockk can you attach the link for your codesandbox example?

**Comment by RyanCCollins** [comment]
@ShimiSun on the east coast, we see:
![screen shot 2019-01-23 at 4 11 25 pm](https://user-images.githubusercontent.com/13810084/51637374-9d054800-1f29-11e9-9bf8-35384ab9638b.png)

It might be a difference caused by your local timezone.  You can try using the [TimeShift](https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj?hl=en) chrome plugin to change your browser timezone to EST to see the issue.

**Comment by ShimiSun** [comment]
@RyanCCollins sounds good, thank you.

**Comment by ShimiSun** [comment]
I agree with @srockk and this behavior is expected.

I suggest you either use the local-time as your date format (emit the Z) to avoid timezone confusion, or in the case that the clients are located on different timezones, feed the calendar with the proper offset to mark the correct date 
e.g. for MST use `date={'2018-11-04T00:00:00.000-07:00'}`. 

let me know what you think @RyanCCollins, @srockk

**Comment by ShimiSun** [comment]
feel free to reopen if you still think we can help.
