### ISSUE TITLE
theme documentation audit 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#2690]
Theme documentation across all grommet components

Complete theme documentation 

Currently incomplete. Component theme audit below. 

Theming documentation needed on:

- [x] accordion
- [x] announcecontext
- [x] carousel
- [x] chart
- [x] checkbox
- [x] clock
- [x] collapsible
- [x] datatable
- [x] diagram 
- [x] distribution
- [x] drop
- [x] dropbutton
- [x] form
- [x] formfield
- [x] grid
- [x] grommet
- [x] heading
- [x] maskedinput
- [x] meter
- [x] radiobutton
- [x] rangeinput
- [x] rangeselector
- [x] select
- [x] skiplinks
- [x] table
    - [x] tablecell
    - [x] tableheader
    - [x] tablebody
    - [x] tablefooter
- [x] tabs
    - [x] tab
- [x] video

### Steps to Reproduce

Review each of the above components on https://v2.grommet.io/components. Notice the missing theme documentation.  

### Your Environment

- Grommet version: 2
- Browser Name and version: all
- Operating System and version (desktop or mobile): all

**Comment by atanasster** [comment]
This really is a time-consuming and error-prone exercise (documenting the themes in such a way by manually looking up methods and hard-coding them into strings) and pretty much impossible to maintain. I would suggest for a future v3 to change the styling implementation into for example a 'subscription' style API (each component subscribes into which styles it will use, and then only use style functions from the subscribed ones, instead of hard-coding style imports ie `import { focusStyle, inputStyle, placeholderStyle } from '../../utils';`). 

Anyway, just from a quick overview, the following components (that have a themeDoc already) also use focusStyle:
`Button`
`TextInput`
yet only `Anchor` and `TextArea` have 
`'global.focus.border.color': { ...`

The list of such inconsistencies can go on, and then there is also the still 'undocumented' components.
Here is a custom rest API that I use to quickly find issues with the theme docs: http://grommet-nextjs.herokuapp.com/api/theme (and parse as JSON)

**Comment by oorestisime** [comment]
I am not sure i understand how you find the issues you talk about (focusStyle). the json seems to list where each part of the theme is used but I am not sure how you found that Button does not have the `focusStyle` in themeDoc. 

If you have a semi automated way to list inconsistencies it is probably worth it to have that run on the CI have the pipeline take appropriate actions (i.e fail on already documented components and maybe)

**Comment by atanasster** [comment]
The json lists which components do use global.focus.border.color (Anchor and TextArea at this momen). I know that a lot more components do use focusStyle, so i just searched in the componenets folder for components thta have already implemented themeDoc in their doc file and have focusStyle in their Styledxxx file - in this case Button and TextInput.

It is not an automated way unfortunately and thta is why i proposed a solution (styles subscription API) for v3, where each componnet will maintain a list of the styles that it uses (and the tests will break if the componnet tries to use styles that it has not registered since styles will not be exported individually but only as part of the subscription ApI). Just something a bit more stable, the current manual/hard-coded way breaks many coding good practices and that is why it already has many bugs.

**Comment by oorestisime** [comment]
Ok i guess i will try and automate this and open issues. we can maybe open one issue per component with what is missing from the themeDoc (if there are any). Can you please point me to the code generating that json?

I see what you are proposing as a solution and it probably needs a separate issue to be discussed although it seems this can not be an immediate change. I am just curious to see if we can improve the current state of things in an automated way :) two of them are independent!

**Comment by atanasster** [comment]
A small improvement would be to add some docUtils helper functions ie withFocusStyle(description) - at least reduce the number of times the same theme props are being hard-coded as string, types and defualt values. 

The code for the theme api is here https://github.com/atanasster/grommet-nextjs/blob/73c2ace463e7b0df3f5d812352971cdc75c15d70/server/server.mjs#L54 - but its simply iterating over the examples API and grouping the components by theme props

Even somehow automating a little more will not avoid issues like even small changes in styling will result in breaking those theme docs. This is simply the wrong implementation for the problem at hand. All that is needed for v2 is a couple of advanced articles on theming and v3 could work on some more reliable solution
