### ISSUE TITLE
FormField is hard to customize

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2765]
### Expected Behavior
FormField is fully customizable

### Actual Behavior
FormField is not passing `className` down to the container, to it is impossible to make `styled(FormField)` work.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/n1k6kl413l

### Steps to Reproduce

1. Open sandbox link
2. notice the custom formfield overrides are not working

### Your Environment

- Grommet version: latest
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by a-type** [comment]
I'd like to piggyback on this and request more customization around FormField in general, beyond styling. Right now it is both useful because of the Form magic, but also opinionated about styling, [forcing children into `plain` mode](https://github.com/grommet/grommet/blob/master/src/js/components/FormField/FormField.js#L115). I think making inputs in a form look entirely different from inputs everywhere else in the app is confusing (I'm also not a fan of the 'single line' look, to me it just looks like the controls are missing and there's a random dividing border; there is no invitation to click that empty space).

Really I think a component should never map and modify children as a default behavior. By convention, as a user, I generally expect that if I pass children to a component, they should be rendered inside that component the same way I passed them in. Tweaking their props is a dangerous game and should be used very sparingly for internal state management only IMO.

In the meantime, at least Formik basically does this stuff anyways, so all I really need is to write a small visual Field component of my own to do the labels and such.

**Comment by AlbertoTonegari** [comment]
> I'd like to piggyback on this and request more customization around FormField in general, beyond styling. Right now it is both useful because of the Form magic, but also opinionated about styling, [forcing children into `plain` mode](https://github.com/grommet/grommet/blob/master/src/js/components/FormField/FormField.js#L115). I think making inputs in a form look entirely different from inputs everywhere else in the app is confusing (I'm also not a fan of the 'single line' look, to me it just looks like the controls are missing and there's a random dividing border; there is no invitation to click that empty space).
> 
> Really I think a component should never map and modify children as a default behavior. By convention, as a user, I generally expect that if I pass children to a component, they should be rendered inside that component the same way I passed them in. Tweaking their props is a dangerous game and should be used very sparingly for internal state management only IMO.
> 
> In the meantime, at least Formik basically does this stuff anyways, so all I really need is to write a small visual Field component of my own to do the labels and such.

I don't know why this issue was closed. I agree with what @a-type said.  I think it's extremely confusing that the FormField component is modifying the styles of its children. Right now, in the project that I am working on, this implementation is destroying the design because the components that goes inside the FormField looks completely different than outside of the FormField.
