### ISSUE TITLE
Allow more options for menu item rendering

### ISSUE THREAD

**Issue by gregtalarico** [grommet/grommet#2769]
Menu items are rendered in a Box aligned to the start with 'small' padding. It would be nice to be able to set the alignment and padding or even pass a function that would get the item as an argument.

https://github.com/grommet/grommet/blob/master/src/js/components/Menu/Menu.js#L184

**Comment by talarico43** [comment]
the same would be nice for the main menu label as well
https://github.com/grommet/grommet/blob/master/src/js/components/Menu/Menu.js#L119

**Comment by oorestisime** [comment]
* well for the menu label you can customize however you want by providing a child. imho the `justifyContent` shouldn't be there in the first place. otherwise we would need like a `padLabel`, `alignLabel` etc which could bloat for not much benefit the menu. 

* For the items i am thinking to add a renderChild method that is called after the button (which sets the selection etc). This way you could style the items how you want (within the button though).

@ShimiSun @ericsoderberghp your thoughts?

**Comment by ericsoderberghp** [comment]
I would like to explore some enhancements to Button that would work for Menu as well. For instance, I find myself often having to use a child render function for things like sidebars.
I think this is also related to https://github.com/grommet/grommet/issues/2554, and possibly
https://github.com/grommet/grommet-theme-hpe/issues/3.
A combination of easier to theme and extend but also make it easier to use in typical situations, like sidebars and Menus.

**Comment by oorestisime** [comment]
ok fait enough i am un-assigning myself till you update on your findings :)

**Comment by markjackson02** [comment]
I would like to use the Menu component as a hamburger menu in my header, but I don't see a way to provide an `href` property so when I hover over the Menu item, user can see where the link is going. It doesn't seem this is possible currently?

**Comment by ericsoderberghp** [comment]
The `items` property of Menu takes all Button properties: https://v2.grommet.io/menu?#items , which includes `href`.
