### ISSUE TITLE
Chart theme docs - color

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2775]
The new Chart theme doc are lumping all colors together: 

https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/doc.js#L154

The correct way (well, Box is also buggy, since it does not list most of its used colors like `border`) would be list the actually used colors like `<Box />`

https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Box/doc.js#L354

**Comment by ShimiSun** [comment]
Thanks for the feedback, I tend to agree but my thought was to display all the possible options for chart colors. Unlike box, it's not just for the text, it will impact different chart display colors, and I wanted the user to know what are the options since there is no default color on the theme for Chart. I'll take a second look at it to see if and how I can improve it.

**Comment by atanasster** [comment]
@ShimiSun Box is also not just the text, the Box docs are just buggy and only list Text as a theme color,

**Comment by atanasster** [comment]
I think the correct way would be to list all the colors affecting a component (like Box started with text, but has some issues listing all the options). Otherwise lumping together the options will be useful (I am currently working on a tool to find bugs in themes and that how I came across the Chart theme doc issues)

**Comment by ShimiSun** [comment]
feel free to reopen or file another issue if the PR doesn't solve the issue.
