### ISSUE TITLE
Chart opacity issues with code and docs

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2776]
Chart uses its own logic for color.opacity:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/Chart.js#L198

inconsistent with its doc:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/doc.js#L24

the new theme doc for Chart is using the wrong logic when documenting:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Chart/doc.js#L197

Box and Meter are more consistent (although best to use backgroundStyle for all components, currently its a bit of a wild west)
Box:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Box/doc.js#L359

Meter:
https://github.com/grommet/grommet/blob/86e086a210481a61ed7f6dc93003e89730037e4c/src/js/components/Meter/doc.js#L85

**Comment by ShimiSun** [comment]
```

**Comment by ShimiSun** [comment]
Let's focus on the Chart docs, Chart.js uses the following logic for opacity:
```
    const opacity = color.opacity
      ? theme.global.opacity[color.opacity]
      : undefined;
```
In case the `color` prop has an opacity value (i.e. 'weak', 'medium', 'strong') the Chart will derive it from the theme `global.opacity`. since we don't have a default prop for opacity the defaultValue is `undefined`. Can you suggest a better way to document it?

**Comment by atanasster** [comment]
@ShimiSun - the theme doc is correctly describing the functionality. Its the functionality that is wrong (so in the title I mentioned its both code and docs issue):

The Chart doc suggests it can also be a boolean (in which case the medium opacity will be used):
https://github.com/grommet/grommet/blob/9eed6e5954e2997c4191b079d5ff6d604db178a9/src/js/components/Chart/doc.js#L24


The Chart doc (possibility for opacity to be a boolean) is also in accordance with the Box And Meter code, where the

1. Box uses utils.background.js:
https://github.com/grommet/grommet/blob/9eed6e5954e2997c4191b079d5ff6d604db178a9/src/js/utils/background.js#L81

2. Meter uses its own implementation of the background, also with the possibility for opacity to be a boolean:
https://github.com/grommet/grommet/blob/9eed6e5954e2997c4191b079d5ff6d604db178a9/src/js/components/Meter/utils.js#L10

**Comment by atanasster** [comment]
btw, up to you guys if you want to create a new issue to clean up the code and consolidate background styling code, so all of (Box, Meter, Chart and any others in the future) use the same code for better maintenance and consistency.

**Comment by ShimiSun** [comment]
@jcfilben Please take a look and let me know what you think should be the action items for this issue. It's been a while since the issue was filed and Chart had gone through many changes/enhancements during this time, so it might no longer be relevant -- but please confirm.

**Comment by jcfilben** [comment]
This issue is still relevant. Currently the opacity prop for Chart is defined in the docs as: 
``` javascript
opacity: PropTypes.oneOfType([
      PropTypes.oneOf(['weak', 'medium', 'strong']),
      PropTypes.bool,
    ]).description(
      `What opacity to apply to the visuals. Supercedes 'color.opacity'`,
    ),
```
The opacity can either be a string value of 'weak', medium', or 'strong'. Or it could be a boolean value of true or false.

Box and Meter opacity both have similar documentation. When opacity is set to true in Box or Meter the opacity defaults to the "medium" value. As shown in this [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-xzzi4?file=/index.js), when opacity is set to true in a Chart, the value is being ignored and a console warning  is shown: "Received `true` for a non-boolean attribute `opacity`".

**The action item** for this issue is to change Chart to align with the documentation and accept a boolean value for opacity and when `opacity={true}` default to the "medium" value.
