### ISSUE TITLE
<Text /> margin styles inefficiencies

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2794]
Can we optimize `<Text />` repeating the margin styles (4 lines instead of just one line)

https://github.com/grommet/grommet/blob/9188fc854f08c467e99819c6512e8d15bb87431c/src/js/components/Text/StyledText.js#L10

![screenshot791](https://user-images.githubusercontent.com/6075606/53046962-47a45400-345f-11e9-97f7-4cbdd722a823.jpg)

**Comment by atanasster** [comment]
probably should try to consolidate using https://github.com/grommet/grommet/blob/44f033a304331db6e9edca98fe281c2b0cfb8ff1/src/js/utils/styles.js#L30

**Comment by spencerkordecki** [comment]
@atanasster I did some digging into this and the first margin property is being set from the `${genericStyles}` call in `StyledText.js` which means that any margins set on the text property are going through both `${genericStyles}` and `marginStyle()` in `StyledText.js`. The call to `${genericStyles}` utilizes `edgeStyle` so there wouldn't need to be logic added to `StyledText.js`

I've taken out all of the margin logic in `StyledText.js` and everything works as expected from what I can tell, let me know if that's the approach that you want to take and I can open a PR that would remove `marginStyle()` in `StyledText.js` and the props check in the same file since that will already be taken care of in `${genericStyles}`

**Comment by atanasster** [comment]
@spencerkordecki fantastic - that's what I had in mind indeed

**Comment by oorestisime** [comment]
@spencerkordecki yes go ahead open the PR :)

**Comment by spencerkordecki** [comment]
@oorestisime @atanasster PR opened, let me know if there's anything that needs to be changed.
