### ISSUE TITLE
global.colors.active not functional

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2853]
the `activeStyle` helper is using the `hover` color instead of the `active` color:

https://github.com/grommet/grommet/blob/ef9432a308f89304908e8f40d56e84c1053cf0af/src/js/utils/background.js#L127

as far as I can see, the active color is not used anywhere, even though its defined in base.js theme:

https://github.com/grommet/grommet/blob/4032b2e0e164fa0afc830eb59320089e53ccebf5/src/js/themes/base.js#L53

I would propose to effectively implement the active color

**Comment by oorestisime** [comment]
It is used for the Button https://github.com/grommet/grommet/blob/master/src/js/components/Button/StyledButton.js#L111

**Comment by atanasster** [comment]
you would think so :)
activeStyle itself does not use the `active` color - check the link to `background.js` that I posted above.

**Comment by oorestisime** [comment]
Yeah i meant to say that activeStyle is used there. (so the one who fixes this adds a test)

**Comment by oorestisime** [comment]
So i came back at this again,
it uses `props.theme.global.hover.background` which points to active color.
```
hover: {
        background: {
          dark: {
            color: 'active',
            opacity: 'medium',
          },
          light: {
            color: 'active',
            opacity: 'medium',
          },
        },
        color: {
          dark: 'white',
          light: 'black',
        },
      },
```
this seems right to me unless i miss something

**Comment by atanasster** [comment]
activeStyle should not be using the hover color, which in turn redirects ro active in base theme only. The active color should be used directly for activeStyle,or it makes no sense to have an active color at all.

**Comment by ericsoderberghp** [comment]
FYI, https://storybook.grommet.io/?path=/story/button--sidebar now shows the button active state when clicking.

**Comment by vavalos5** [comment]
It looks like in the theme we define `hover `as `active`. Do we have to have a` hover` prop defined as the same color as we do for `active`?

**Comment by ShimiSun** [comment]
@vavalos5 , that is correct, currently, both colors are defined the same way, and due to the backward compatibility of the theme, we do not have the flexibility to change those at the moment.

That being said, we have extended the `active` and `hover` theme props per component so components will have the flexibility to custom these colors as fit. 
The base theme is also supporting the following colors for extra customization alternatives, and it's being used across the app:
```
 'active-background': 'background-contrast',
 'active-text': 'text-strong',
```

Also, with the new 'kind' button concept, the user is able to define the hover/active behavior and colors per type of button, which allows the customizability of applying different colors for different use cases.

I'll be closing this issue since I think we have done what we can with the current backward compatibility constraints.
