### ISSUE TITLE
Add CheckBox label position prop

### ISSUE THREAD

**Issue by nikitavoloboev** [grommet/grommet#2865]
Currently [CheckBox](https://v2.grommet.io/checkbox) has `label` prop but it will only be displayed on the left or right side of the checkbox. But I wanted to show the label at the top of the label.

I think it would be nice to add support of configuration position of label to either bottom or top.

**Comment by ShimiSun** [comment]
thanks for the suggestion! Can you please share an example or a design of the use case?

**Comment by nikitavoloboev** [comment]
I have this now

![2019-03-02 at 07 01](https://user-images.githubusercontent.com/6391776/53677996-1aef0880-3cb9-11e9-8b37-8571ff616bf3.png)

But `Jitter` text is a div. I still need to align it with CheckBox. Ideally the label would make `top` and `bottom` align by center with the checkbox too.

**Comment by ShimiSun** [comment]
Do you use it inside of a Form? can we see the wider design idea? I'm trying to understand what type of design will do justice to the label on top/bottom rather than left/right. I hope my request makes sense.

**Comment by ShimiSun** [comment]
@L0ZZI do you think this is a valid use case to have?

**Comment by nikitavoloboev** [comment]
I have solved this issue with some CSS. So it's not really relevant for me and I agree with what @ShimiSun. I think this can be closed.

**Comment by ShimiSun** [comment]
@nikitavoloboev thanks for the update, glad you were able to work it out.
We are looking to constantly improve, so if @L0ZZI our designer thinks it's a valid use case, I think we should allow your idea to be consumed out of the box.

**Comment by ShimiSun** [comment]
After talking about this issue with the team, we are interested to understand how this scenario will be handled in a responsive way when the text will be too long. for example, one may want the checkbox to be aligned centered while others won't. so it drives some layouts questions on the implementation. 
I addition, although this behavior is not allowed using a prop at the moment, it could still be achieved using JSX for a customized layout. 
we will welcome contributions from the community in case this issue is relevant for more folks. thank you for filing an issue. I'll be closing it as you suggested, feel free to reopen if needed.
