### ISSUE TITLE
Support target on Layer component

### ISSUE THREAD

**Issue by wirtzdan** [grommet/grommet#2877]
Currently, Layer's don't support the target property (How its used in the Drop Component) and therefore can't be positioned relative to an element. 

### Expected Behavior

With target on a layer, it would be possible to add something like the Google Calendar popup for event creation. The background has an overlay similar to what the Layer already offers, what's missing though is the possibility to target the element. Therefore its only possible to align the Layer in the middle or on the side of the page. 

![image](https://user-images.githubusercontent.com/18514829/53721335-4d3c6980-3e63-11e9-9248-827b7d753e0f.png)

**Comment by oorestisime** [comment]
I gave this a second look and what you are trying to achieve could be done with the Drop component.
Have a look at the this example https://storybook.grommet.io/?selectedKind=Drop&selectedStory=Progressive&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

Let me know if this is what you might be looking for

**Comment by wirtzdan** [comment]
But I'm not seeing a dark overlay in the given example of the Drop component. This is what's missing for me.

**Comment by oorestisime** [comment]
True but that's just adding an overlay, i wonder whether we should add an option for drop to render like an overlay. lets wait to see what others think!

**Comment by oorestisime** [comment]
@MikeWalrath maybe to discuss this at some point, i think it might be a good idea to expose the Overlay as a component. So that people could use it and for this case combine the drop with the overlay to reach the desired UI instead of changing the way layer works to support more positions.

**Comment by ericsoderberghp** [comment]
For a general overlay, you could use Stack with `interactiveChild` to control where the interaction happens. But, you'd still need a way to position a drop/layer as requested. For the scenario mentioned, I'm not sure how the blue box on the left would be positioned, as that appears to be above the overlay, presumably positioned directly over the event on the calendar grid underneath. That's a bit of tricky alignment that can't be done with Drop or Layer in grommet today. But, I think the blue box is sort of necessary from a design standpoint to anchor the drop/layer visually.

I'm trying to find another example of Drop + overlay. Layer + overlay seems OK because the Layer is not connected tightly to an underlying component, just the center, side, or corner of the overall window. Drop, on the other hand, is tightly connected to the target element, but without an overlay, so the target element connection is easily visible.

Anyone have any other examples?

**Comment by ShimiSun** [comment]
@wirtzdan, @oorestisime any other examples or inputs, or can we close the issue?

**Comment by wirtzdan** [comment]
We can close this!

**Comment by ShimiSun** [comment]
This issue is fixed and will be available on any release later than 2.11.1.
Thank you for reporting and for your patience.

**Comment by LeComptoirDesPharmacies** [comment]
Hi @ShimiSun @wirtzdan  @oorestisime,

We tried to use 'Layer' component with this new 'target' feature but it does not behave as we expected.
We were thinking that positioning would be like a Drop with global overlay (Drop is located next to the target).

But in our side, we have an overlay that is limited to target boundaries and Layer position is located into the target instead of next to him.

![image](https://user-images.githubusercontent.com/25615113/128844337-fa06a336-dac3-4bd0-9f6e-d5f6d8a0e7b2.png)

Is there something that we did not understand ? Is there any plan to export global Overlay as a standard Grommet component ?

Yours faithfully,
LCDP

**Comment by ericsoderberghp** [comment]
The Layer `target` was implemented to indicate where the modal translucent background should extend to and where the Layer itself should be positioned relative to. If I understand you correctly, you are wanting the latter without the former. If I'm correct, that isn't how it works at the moment.

I am trying to think how we might approach providing that. I think you will want `align` from Drop but with `modal` from Layer.  I'm wondering which direction to take that. I think doing it with Layer feels a bit better to me, since Drop doesn't want to obscure the target in any way. Perhaps something like `<Layer align={{ target: ..., align: { ... } }} />`?
