### ISSUE TITLE
Improve references to examples/templates/blogs...

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#2896]
Let's discuss on the right design to place the links to our resources of examples, templates, blogs...

Options to consider:
* README on github
* Add a link to grommet-site getting started
* Add a wiki page with the content and link to it.

Please share thoughts, we'll be discussing it next week.

Great, in the meanwhile, I’ll summarize it all up for quick access:
1. Basic code sandbox playgrounds for each of the grommet components https://codesandbox.io/s/github/grommet/grommet-sandbox
2. Storybook examples, some simple and some are advanced for each component:  https://storybook.grommet.io/
3. Templates and pattern ideas  https://codesandbox.io/u/grommetux/sandboxes feel free to share ideas for new patterns on the #pattern-ideas channel
4. E2E projects shared by the grommet community on the #i-made-this channel.
5. More info on filing issues and different types of contributions https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md

**Comment by ericsoderberghp** [comment]
A few thoughts ...

I think our per-component linkages are OK, both Storybook and CodeSandbox are already there. 
However, I think CodeSandbox is a bit too heavy for what we need. I would recommend removing the CodeSandbox link and just relying on the inline editor on the component pages in v2.grommet.io instead of using grommet-sandbox.

Given the frequency of questions about patterns, I think something should be linked from v2.grommet.io. I think it would help to have a separate index page on v2.grommet.io cataloging the patterns and projects. Perhaps "good examples of grommet in use", "grommet in use", or ?

**Comment by ShimiSun** [comment]
Thanks for sharing.
Codesandbox currently provides a React context that the built-in editor on the site doesn't provide, (e.g. components that need state in order to function doesn't work on the built-in editor), so IMO sandbox is still needed, I do agree it might be too heavy, but it does provide helpful functionality.

**Comment by ShimiSun** [comment]
reopening, we still want it on the grommet-site as well :)

**Comment by ShimiSun** [comment]
we'll be continuing the discussion on #3887
