### ISSUE TITLE
Grommet Theme Icon size override does not work

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet#2971]
After trying to follow the example here: https://github.com/grommet/grommet-icons
The theme size overrides do not work, but color overrides do for icons.

### Expected Behavior

1. Adding a new size type like "xxmall" gets accessed via Size prop in Icon component (Enhancement?)

2. Overriding existing values for "size" in custom theme should be accessible in Icon component

### Actual Behavior
Size overrides and additions are not accessible in Icon components

### URL, screen shot, or Codepen exhibiting the issue
Here is a example showing 2 menus, one without theme, one with custom theme. Only color gets passed down.

https://codesandbox.io/embed/m5qqrvw3k8

### Steps to Reproduce

Open / Close menu

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): desktop, windows 10

**Comment by oorestisime** [comment]
I think the problem is in grommet-icons.

This seems wrong https://github.com/grommet/grommet-icons/blob/master/src/js/StyledIcon.js#L47-L50 or at least is not in accordance with this https://github.com/grommet/grommet-icons/blob/master/src/js/StyledIcon.js#L47-L50 (way to access theme).

I think this is wrong as well https://github.com/grommet/grommet-icons/blob/master/src/js/StyledIcon.js#L47-L50

**Comment by ShimiSun** [comment]
@oorestisime we need to figure out what is the right approach for this one. I think we should change grommet-icons to point to global.icons. thoughts?

**Comment by oorestisime** [comment]
yes i agree that grommet icons need updating to point to `global.icon`

**Comment by alansouzati** [comment]
i don't think we intended to add `global.icon` in the first place. it is a problem in the README. the right property is `theme.icon`.
