### ISSUE TITLE
Why simple props like onBlur is not available on Components like TextField?

### ISSUE THREAD

**Issue by midnightcodr** [grommet/grommet#2983]
I don't know if this is a design intention but I find it hard to believe that form components like `TextField` lack props such as `onBlur`. This is just another reason that I can't use Grommet for my projects as I am using [Formik](https://github.com/jaredpalmer/formik) to handle my forms.

Also if you try this [modified example](https://v2.grommet.io/textinput?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHJNxANxVEAJ34hDSQgeoAeACr5UUAJJhsIKJeqI8c-AAs4uAAm+IbiAERQAJ7Y+Ii+IfhhHtRsHPjiZKmcAL7JiAgARhyhZLRgdAH48rhwAOaEmkWm+IE6uZ6eCADCvuhgtelk+Cz4YIziAHy8-EJphMOjUPJqhgNLWfjE7Z4A9BMGehTZQA), in which I was able to add

```
onblur={console.log('blured')}
```
note the lower case `b`. But the event fires on change, not blur, very odd isn't it?

**Comment by oorestisime** [comment]
They are available as part of the intrinsic elements of the field. We don't expose them because we don't use them. So you can use them without any problem.
I modified your example [to fix your issue with onChange](https://v2.grommet.io/textinput?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHJNxANxVEAJ34hDSQgeoAeACr5UUAJJhsIKJeqI8c-AAs4uAAm+IbiAERQAJ7Y+Ii+IfhhHtRsHPjiZKmcAL7JiAgAQhyhZCQSAHw09AH48rhwAOaEmgBGxfiBOrmenggAwr7oYA3pZPgs+GCM4pV8gsJE45NQ8mqGIytZ+MTdngD05QZ6FNlAA) As with the onChange event handler it expects a function. More information [here](https://reactjs.org/docs/handling-events.html)

Also have you seen the formik pattern? https://codesandbox.io/s/y331zzorz

**Comment by midnightcodr** [comment]
Ok my bad, I actually did try `onBlur` before your comment @oorestisime  but it didn't work maybe I didn't type it right. Thanks!

**Comment by dhfuzari** [comment]
I have the same problem. In the @oorestisime example, he used grommet 2.4.0, but on grommmet 2.9.0 it didn't works. Maybe that's why we can't solve our problem @midnightcodr.

**Comment by oorestisime** [comment]
hey @dhfuzari sorry not sure i understand. is the onBlur event not firing on 2.9? and for which component? might make sense to open a new issue with a reproduction if this is the case.
