### ISSUE TITLE
Menu on Open - DropButton Icon

### ISSUE THREAD

**Issue by rjain15** [grommet/grommet#2984]
When you open the Menu, the DropButton Icon is same as the MenuIcon (or Menu icon). 

Code sandbox for the menu https://codesandbox.io/s/l7nyp5697 (when you have responsive behavior, and change the size to small) 

Suggestion: I don't know exactly which code to change, if it is Menu.js and the DropButton component, where I can specify the Icon? If yes, I would like to submit a PR. 

(https://github.com/grommet/grommet/blob/master/src/js/components/Menu/Menu.js)

**Comment by oorestisime** [comment]
Hello,

are you maybe looking for https://v2.grommet.io/menu#menu.icons.down ?

**Comment by rjain15** [comment]
I don't think so, maybe I am wrong.. 

I have this in my code, but I want to change the icon from MenuIcon to Cross, when the menu opens up. 

Where do I set the menu.icons.down, and how does this impact the behavior on Open. 

          <Menu
            dropAlign={{ right: "right", top: "top" }}
            icon={<MenuIcon/>}
            items={[
              { label: "Activity", href: "#" },
              { label: "Utilization", href: "#" },
              { label: "Virtual Machines", href: "#" }
            ]}
          />

**Comment by oorestisime** [comment]
You set this in the theme. Have a look at this codesandbox https://codesandbox.io/s/216vvpmlqj and specifically the way it overrides the theme (the theme.js file)

**Comment by ShimiSun** [comment]
@rjain15 I agree with @oorestisime that the icon is controlled by the theme, I added to the theme.js file the following:
```
  menu: {
    icons: {
      down: Add
    }
  },
```
so the menu will show the '+' icon instead of the usual menu down icon. https://codesandbox.io/s/rjx8lpw09q

If I understand right, you are also requesting that the icon will be switched when closed vs open? this functionality currently doesn't exist and sounds like a fun enhancement. you pointed to the correct file of Menu.js, and to be more line specific https://github.com/grommet/grommet/blob/5bd6c2c41731e4b29565e867ca47c7ec315a853a/src/js/components/Menu/Menu.js#L114
The content on line#117 will need to have the icon adjusted according to the state open/close of the menu.js, not sure if we have the right flag for open/close yet, but feel free to explore.
The base.js file, should be changed along these lines as well to include the open icon option:
```
  menu: {
    icons: {
      down: Add,
      open: undefined
    }
  },
```
@oorestisime feel free to jump in and let me know if I missed anything,
Thank you for your interest in contributing to Grommet! feel free to let us know if you need more guidance.

**Comment by ShimiSun** [comment]
@rjain15 can you please confirm my thoughts and the overall approach? is this the functionality you are seeking?

**Comment by rjain15** [comment]
I am staying with the default Menu behavior, the change is trivial but I am not sure if this is the right thing for community. I can submit the change PR if it makes sense and doesn't break any tests.
