### ISSUE TITLE
Can't remove margin from EdgeControl of the RangeSelector component

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2993]
Can't remove margin from EdgeControl of the RangeSelector component

### Expected Behavior
A way (either through theme or prop) to fully customize the edge controls of the range input

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/3v0kmv31v6

### Steps to Reproduce
Inspect controls of the range selector from the code sandbox above and check that there's a margin applied to them

- Grommet version: 2.6.5
- Browser Name and version: Chrome (latest)
- Operating System and version (desktop or mobile): MacOS Desktop

**Comment by ShimiSun** [comment]
Hi buddy, thanks for raising the issue. while allowing to customize the margin may help as a workaround, there was still a fundamental alignment issue with the way margin was used on the edge-controls that caused the problem you raised.
This alignment issue was fixed on #3066 along with the enhancement of allowing custom nodes of edge controls. 
I believe that your issue is fixed; you won't need to use custom margin in order to fix the alignment problem, and in case you do decide you want to have a margin you can always use a custom node. Please let me know if there is anything else you'd like us to address on this matter. bests.
