### ISSUE TITLE
Support onMouseOver,onMouseOut event in Select component

### ISSUE THREAD

**Issue by joehandzik** [grommet/grommet#2997]
I'm porting a React application from React Semantic UI to Grommet, and one stumbling block I've encountered is to find something analogous to React Semantic UI's [Popup component](https://react.semantic-ui.com/modules/popup/). In an attempt to emulate that, I found [this](https://storybook.grommet.io/?path=/story/drop--tooltip) Storybook entry, which relies on the onMouseOver and onMouseOut events. Initial tinkering works as expected with the TextInput component (even though it's not documented to support onMouseOver), but no such luck with Select.

This request is specifically for the Select component, but to be fully competitive with Semantic UI you'd want to support some mechanism to build a Tooltip component for any component, I'd think.

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: 60.2.2esr (64-bit)
- Operating System and version (desktop or mobile): CentOS 7.6

**Comment by oorestisime** [comment]
Hello,

I haven't tested this but generally speaking we forward all the events to the component. This is why we are not documenting these props. 
I don't think grommet will provide a component for tooltips since those kind of components tend to be quite opinionated. 
Where are you trying to add the tooltip? I mean is it on mouse over of an option or the select itself? And when you say no luck with Select, did you get an error or anything? (Trying to classify this as a bug or not)

**Comment by joehandzik** [comment]
@oorestisime That makes sense, and is good to know going forward. I'm not to the point of actually adding the tooltip, I just added a method for onMouseOver to echo some text into the browser console when the event method gets called. I was seeing events on on InputText component but not on my Select component.

**Comment by atanasster** [comment]
Not directly related to this topic, but I would suggest to not use statements like:
"I don't think grommet will provide a component for XXX since those kind of components tend to be quite opinionated. Instead we will provide usage templates that do XXX", where XXX is Tooltip (promised by Alan a year ago), Header, Sidebar, Toolbar and a few other components that are part of most other react UI libraries and used in pretty much every web app.

1. Those statements are absolutely not true - there are way more "opinionated" components in v2, like Clock, Calendar, Diagram, WorldMap etc.
2. At one point or another, v2 team member claimed various components were "opinionated" just to add them a few months later with great fanfare.
3. Much better to collect a list of the requested v2 components to be added and see which ones are the most often requested by users, so once v2 is stabilized such components can be added (or re-introduced as some of them like Tooltip did exists in grommet v1).

**Comment by oorestisime** [comment]
Well i stated my personal opinion not anybody else and i don't see why i shouldn't say my opinion! Didn't mean to sound like it was the team's opinion sorry if it sounded like this. Not talking about other components but tooltip for me is quite opinionated and almost always you end up customizing the look of it. If the idea is to provide a tooltip which just adds a drop I personally think it is of no great value! (again my opinion not the team)

I agree that there are some existing components that are opinionated (some of those you mention) and I would personally argue (once again me not the team) that they shouldn't be in the core components but that is not relevant here.

**Comment by atanasster** [comment]
Strangely enough, its word for word a repeat of someone else’s ‘opinion’ since v2 development started 2 years ago. This message here is just the last in a series that i saw repeating this same ‘opinion’ in the last month or so about various component requests.

Its the word ‘opinionated’ that makes me cringe - it does not have any definition and is purely speculative - a way of looking like some of the missing pieces in v2 are ‘by design’ and shooting down any discussion about it. 
If your opinion is that Tooltip specifically should not be part of a react UI library, then say so.

**Comment by oorestisime** [comment]
My experience with tooltips from other libraries is that i tend to heavily modifying them, and its almost always more painful to modify than probably start one from scratch. i am no native english to know but i understand that this is the definition of opinionated. I don't say it should not be part of any UI library. I guess that for libraries that follow specific designs then it probably makes sense. I am saying that (imho) it shouldn't for a package tending to be generic and modular.

In any case can we leave this issue relevant to the bug it describes? it can be a discussion on slack or another issue if you want.

**Comment by atanasster** [comment]
Tooltip definitely does not fit your definition.

grommet v1 does have a Tooltip component and you can check how many requests there had been for any style change/modifications. 

Or requests for ‘heavily modifications’ in any other librray’s Tooltip component. 

Slack is fine to continue the discussion (tag me as i am not following as much) - feel free to  show me your own ‘heavily modified’ versions of tooltips and why you had to modify them so heavily.

**Comment by IanKBovard** [comment]
I could be wrong, but I belive this is possible, using refs and the drop component. If so, this issue can be closed.

**Comment by jcfilben** [comment]
Yes, I think this issue can be closed. The Tip component was added recently which could also be used to accomplish this.
