### ISSUE TITLE
Select button breaks if html suppllied to `icon` prop

### ISSUE THREAD

**Issue by MaxMillington** [grommet/grommet#3017]
Currently, there is an icon prop that you can supply to the `<Select />` component to provide a custom icon instead of the normal arrow. However, if you provide an html element instead of a grommet icon, the component fi

What should happen is that grommet should render anything I provide in the icon prop. I have a design requirement like so, and I want to just provide a custom built circle to satisfy it.

![Screen Shot 2019-04-11 at 2 16 54 PM](https://user-images.githubusercontent.com/11064595/55993643-7c18dd00-5c64-11e9-8ccb-2d6f2d49fac6.png)

Instead, the component just breaks.

### Steps to Reproduce

This code will recreate this issue:
```
    <Select
          multiple={true}
          value=1
          onChange={() => { console.log('changing')} }
          options={[1,2,3]}
          icon={<div>hey</div>}
        />
```

### Your Environment

├── grommet@2.6.5
├── grommet-icons@4.2.0

**Comment by ShimiSun** [comment]
I like the generic approach, I'll take a look at it.

**Comment by alansouzati** [comment]
I think there is a use case to render a custom box that mimics an icon. I sent a pr that allows for that (changing the proptypes for Select). I've changed this issue back to an enhancement since `icon={<div>hey</div>}` is an invalid prop for icon.

FWIW, in your case I would still do `<Select icon={false} />` and render the badge inside the select value. In your case I don't believe you want to render the icon but a badge that relies on the value of the Select. But, of course, the decision is on you.
