### ISSUE TITLE
RadioButtonGroup radio buttons don't lose focus state when user clicks on page

### ISSUE THREAD

**Issue by djm158** [grommet/grommet#3115]
I noticed that radio buttons in a RadioButtonGroup component seem to hold focus for too long.

### Expected Behavior

I expect them to gain focus on selection, but then lose that focus when other parts of a page are clicked.
 
### Actual Behavior

Radio buttons hold focus even when clicking around a page. Arrow keys will move multiple radio buttons if they are focused on the page.

https://codesandbox.io/s/grommet-v2-template-54rxo

**Comment by crashuniverse** [comment]
I'll break this down to number of problems you mentioned:
1. RadioButtonGroup component seem to hold focus for too long
2. lose that focus when other parts of a page are clicked
3. Radio buttons hold focus even when clicking around a page
4. Arrow keys will move multiple radio buttons if they are focused on the page

4 can be solved. You have duplicate `name` for `RadioButtonGroup` components. Semantically these groups need to have separate names because that is sort of unique ID for these components (and also if you were using plain html elements ). So some changes at https://codesandbox.io/s/grommet-v2-template-xqhyx (a fork of your example) resolves that.

I believe 1, 2, 3 represent that same problem that focus stays on even if we click outside, for example a focussable element like Button. This is indeed a problem.

**Comment by IanKBovard** [comment]
Im unable to replicate this in the current version of grommet. I believe we can close this issue.
