### ISSUE TITLE
Using shorthand properties for input padding produces wrong and huge padding

### ISSUE THREAD

**Issue by dimitrisnl** [grommet/grommet#3124]
### Expected Behavior

```js
const myTheme = {
  global: {
    input: {
      padding: "20px 10px"
    }
  }
};
```

Using this configuration, I would expect my input to have a vertical padding of `20px` and a horizontal one of `10px`

### Actual Behavior

Instead, the padding generated is `2009px`

![Screen Shot 2019-05-28 at 1 29 05 PM](https://user-images.githubusercontent.com/4951004/58471699-297c7d00-814d-11e9-9d03-982d429a4c2f.png)

Sandbox: https://codesandbox.io/s/grommetsandbox-s9u7z

**Comment by crashuniverse** [comment]
I wouldn't consider this as a bug. The documentation for Input (https://v2.grommet.io/textinput#global.input.padding) suggests `padding` accepts only 1 value that it applies as `padding: 12px`. It doesn't support complete css variants of providing 1, 3, 4 values. The original intention seems to enforce 1 value of padding of text written inside input horizontally and vertically.

@dimitrisnl Was one value only at documentation an oversight or does your original post intend on correcting the behavior as more expected in future too?

Although I understand that if the values arrive incorrectly, it should default to maybe 0 instead of 2009px. Discussing this to determine a correct course of fix by discussing it with contributors and @dimitrisnl

**Comment by oorestisime** [comment]
problem is at the parse metric as number. 
```
export const parseMetricToNum = fontAsString =>
  parseFloat(fontAsString.replace(/[^0-9/.]/g, ''), 10);
```
this was probably needed to avoid px values etc. if anybody feels like adding a warning in development if the fontAsString value is not numeric then go ahead :)

**Comment by crashuniverse** [comment]
@oorestisime Edit: It never returns 2009px, it returns 2010. Apologies for misleading message.

I created a pull request and added as much precise information as I understood. Kindly take a look.
