### ISSUE TITLE
Diagram to add animation prop

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3210]
I wonder if we should build this into Diagram? We could add `animation: true|false|draw|pulse` to both Diagram as a whole but also to individual objects in `connections`.

_Originally posted by @ericsoderberghp in https://github.com/grommet/grommet/pull/3208_

**Comment by ShimiSun** [comment]
This is a good issue for someone who wants to get familiar with adding new prop

**Comment by sanji11** [comment]
Hi, I am working on this issue and I have some questions. I can see `pluse` is default if I don't specify `customTheme`. Right now, I am passing "animation" prop from `Animated.js` to `Diagram.js`.  If it is there, then the theme is set to `customTheme` which shows the animation in `draw`; otherwise, `pulse`. My question is how I am gonna incorporate true and false there? Do we need two separate props because if it is true, what style the animation is going to show?

**Comment by ShimiSun** [comment]
The API should be:
```
            <Diagram connections={connections} animation />
```
The Animated.js shouldn't use the custom theme hack to apply the animation, the animation should be driven from the `animation` prop and not from the theme.

**Comment by sanji11** [comment]
Yes I have the above line in Animated.js
```javascript
<Diagram connections={connections} animation />
```
I moved customTheme to Diagram.js and set the theme to customTheme there:
```javascript
// for draw animationStyle
const customTheme = deepMerge(grommet, {
  diagram: {
    extend: `@keyframes
  example {
    to {
      stroke-dashoffset: 0;
    }
  }
  path {
    stroke-dasharray: 500;
    stroke-dashoffset: 500;
    animation: example 3s linear forwards;
  }`,
  },
});

return (
    <StyledDiagram
      ref={svgRef}
      viewBox={`0 0 ${dimensions.width} ${dimensions.height}`}
      preserveAspectRatio="xMinYMin meet"
      theme={animation && customTheme}
      {...rest}
    >
      <g>{paths}</g>
    </StyledDiagram>
  );
});
``` 
Did I misunderstand something?

**Comment by ShimiSun** [comment]
customTheme shouldn't be placed on Diagram.js. Diagram should handle animation similarly to how Box is handling it.

**Comment by sanji11** [comment]
Thanks for the hint ☺️ I will investigate more.
