### ISSUE TITLE
How to 'preset' a RangeInput value?

### ISSUE THREAD

**Issue by mixdev** [grommet/grommet#3347]
When using RangeInput control, you can surely set the 'value' to some number and it will display the control according to the value. 

But if you hardcode the 'value', the rangeinput control is no longer 'slidable'. Even if this behaviour is desired in some applications, there has to be a way to preset but also be able to change the value sliding. 

Check an example: https://codesandbox.io/s/jolly-leavitt-4d7uu

How to set an initial 'preset' value which won't stop me from sliding?

-Browser: Chrome latest on Mac

**Comment by britt6612** [comment]
@mixdev can you double check the code sandbox link ? I get the hello code sandbox when I open it.

**Comment by mixdev** [comment]
> @mixdev can you double check the code sandbox link ? I get the hello code sandbox when I open it.

Apologies. Fixed it.

**Comment by britt6612** [comment]
> > @mixdev can you double check the code sandbox link ? I get the hello code sandbox when I open it.
> 
> Apologies. Fixed it. (didn't think CSB creates everything private and you got to settings to change it)

No problem I will take a look now!

**Comment by britt6612** [comment]
Hey there @mixdev ! So it seems that the issue here is that after you initially define your value, you are not providing a way for that value to be updated. Because of this, when you’re dragging the range selector, nothing is moving because your code is saying “always stay at the initial value”.

If you want to have a preset value and allow the slider to move afterwards, you’ll want to use React’s state feature which allows you to set an initial value and update it later on. By setting the onChange prop to onChange={event => this.setState({ value: event.target.value })}, you’re telling your app that “when the slider is dragged, update the value”. Hope this helps!

https://codesandbox.io/s/rangeinput-0k564

Please let me know if there is anything else or if this answers your question! 👍

**Comment by ShimiSun** [comment]
hi @mixdev, I think we can close this issue, let me know if you think otherwise.

**Comment by ShimiSun** [comment]
Feel free to reopen or share more comments if needed, thanks for reporting.
