### ISSUE TITLE
Problem with the grid system

### ISSUE THREAD

**Issue by mikhaelangelo** [grommet/grommet#3460]
### UPDATE (10/13/19)

I discovered what i was doing in wrong: the gridArea only works as a Box's property. So, i removed the gridArea from the NavbarTop component and move it into the Box component, inside NavbarTop

### Expected Behavior

The NavbarTop component should be positioned on the right side, at the first row and the second column.

### Actual Behavior

The NavbarTop component arent respecting the grid system and still on the wrong side of his gridArea

### URL, screen shot, or Codepen exhibiting the issue

<Grid
columns={["auto", "medium"]}
rows={["small", "auto"]}
gap="small"
areas={[
{ name: "navbar", start: [1, 0], end: [1, 0] },
{ name: "main", start: [0, 1], end: [0, 1] }
]}
>
<NavbarTop gridArea="navbar" handler={this.changeState} />
<Box
gridArea="main"

[https://codesandbox.io/s/grommet-and-grid-system-jbvd4?fontsize=14](url)

![image](https://user-images.githubusercontent.com/15060020/66711023-2d0a4c80-ed5a-11e9-9397-7eabfce2fb7b.png)

### Your Environment

- Grommet version: 2.7.9
- Browser Name and version: Chrome v77.0.3865.120 | 64 bits
- Operating System and version (desktop or mobile): Windows 10 Home Single Language (original) | 64 bits. Desktop.

**Comment by ShimiSun** [comment]
Hi buddy, thanks for reporting.
The codesandbox you sent is broken with failures  https://codesandbox.io/s/grommet-and-grid-system-jbvd4?fontsize=14
![Screen Shot 2019-10-14 at 11 33 11 AM](https://user-images.githubusercontent.com/6320236/66771073-7cde3600-ee76-11e9-881d-7d014dba019c.png)
Mind getting it to work so we could have a look?
Also, a common way to troubleshoot Grid issues is making sure you are not mixing up the row and column order, so make sure you are referring to it as [column, row], rather than the other way around.

**Comment by mikhaelangelo** [comment]
i found what were happens wrong and updated the post with the solution ^_^ thank you for the attention! also, i  dont know why you are getting those errors in the codepen. Works fine here =(

**Comment by ShimiSun** [comment]
@mikhaelangelo great, can we close the issue?

**Comment by mikhaelangelo** [comment]
@ShimiSun sure, please <3
