### ISSUE TITLE
hoverIndicator not working

### ISSUE THREAD

**Issue by nortonglitz** [grommet/grommet#3567]
### Expected Behavior
Should change the background color and other stuffs while the mouse is on the Box

Example:
https://codesandbox.io/s/condescending-cdn-plrid?fontsize=14&hidenavigation=1&theme=dark

**Comment by ShimiSun** [comment]
Hi buddy, thanks for your patient, this fix is available on grommet 2.8.1 that was released today, I double-checked it with your sandbox and it works as expected https://codesandbox.io/s/clever-darkness-wq5iy
I'll be closing this PR, feel free to shoot us questions if needed

**Comment by ssolari** [comment]
I have been trying to get the hoverIndicator to work on a Box.    I can not seem to make it work at all.   I looked at your sandbox and absolutely nothing happens on hover over?   Should anything happen?   If so what?   

On my side, I upgraded to Grommet 2.9.0.   I looked through #3330 (which I agree with, the docs are extremely hard to understand).   In that issue there is another sanbox that works for a button:
https://codesandbox.io/s/buttonhoverindicatorprop-l8zvk
I tried to simply replace the button with a box using the same hoverIndicator (I expect this to work since onClick is included).   It does not work. 

I do not see how the box hoverIndicator is working?   This issue should be open, or could someone help provide an example where a mouse hovering over a box changes its background/color some how.
