### ISSUE TITLE
Typescript error with type Colors

### ISSUE THREAD

**Issue by rodrigopavezi** [grommet/grommet#3593]
```
Failed to compile.

.../node_modules/grommet/themes/base.d.ts
TypeScript error in .../node_modules/grommet/themes/base.d.ts(34,3):
Property ''accent-1'' of type 'string | { dark?: string | undefined; light?: string | undefined; } | undefined' is not assignable to string index type 'ColorType'.  TS2411

    32 |   
    33 | type Colors = typeof colors & {
  > 34 |   'accent-1'?: ColorType;
       |   ^
    35 |   'accent-2'?: ColorType;
    36 |   'accent-3'?: ColorType;
    37 |   'accent-4'?: ColorType;
```
### Expected Behavior

Compile Successfully 

### Actual Behavior

Failed to compile.

### Steps to Reproduce

yarn start

### Your Environment

- Grommet version: 2.8.1
- Typescript version: 3.7.2
- React Version:  16.8.6

**Comment by ShimiSun** [comment]
Hi buddy, can you provide more information? I started a codesandbox of React+TypeScript+Grommet, and I wasn’t able to reproduce the issue https://codesandbox.io/s/reacttypescriptgrommet-dq6tg (clean of warnings and errors), feel free to add to this codesandbox any code that will help us reproduce the problem you are experiencing.

**Comment by luski** [comment]
I have the same problem on create-react-app

**Comment by rodrigopavezi** [comment]
Issue has been fixed after upgrading the project to the latest create-react-app. Cheers

**Comment by ShimiSun** [comment]
Thi issue is related to storybook ts config.
https://github.com/rajeshnaroth/cra-ts-grommet-storybook/pull/1/commits/3e095bb3bef752938a06471ee8bcb5f3511a1879

Find more info on this thread https://grommet.slack.com/archives/C04LMHN59/p1575615061265900

**Comment by jackielfu** [comment]
was running into the same issue here:

`TypeScript error in /app/src/App.tsx(17,20):
Type '{ global: { colors: { brand: string; focus: string; placeholder: string; control: string; }; font: { family: string; size: number; }; input: { weight: number; padding: string; }; edgeSize: { small: string; }; }; ... 6 more ...; textArea: { ...; }; }' is not assignable to type 'ThemeType'.`

turns out, we hadn't added a typescript loader to our app. app now runs after following the instructions here: https://ricostacruz.com/til/babel-typescript
