### ISSUE TITLE
Design change focus color.

### ISSUE THREAD

**Issue by CR1AT0RS** [grommet/grommet#3656]
I think the focus color is very inconsistent with the design. It does not work on all mobile device UI as well. We should make it optional and take it off as default. 
### Expected Behavior
It makes a faded color border/shadow around the object on focus. As you can see in screenshot below a rectangular border on a curved button is just very awkward to look at especially with a bright green color. 

Proposing two changes:
1. Focus should be turned off as default
2. Focus shape should be consistent with button shape. Look at component button.
<img width="480" alt="Screen Shot 2020-01-12 at 11 00 28 PM" src="https://user-images.githubusercontent.com/4299288/72237521-9daa4a80-358f-11ea-865c-a277286c0bd6.png">

Focus property should be optional and not enabled by default. 
### Actual Behavior
Focus is always turned on on all buttons

### URL, screen shot, or Codepen exhibiting the issue

![](https://files.slack.com/files-pri/T04LMHMUT-FSJQ14M5J/screen_shot_2020-01-12_at_5.13.11_pm.png)
<img width="184" alt="Screen Shot 2020-01-12 at 5 13 11 PM" src="https://user-images.githubusercontent.com/4299288/72237543-b1ee4780-358f-11ea-93d1-35683fe3749d.png">

**Comment by ShimiSun** [comment]
https://grommet.slack.com/archives/C04LMHN59/p1579046718193200
Overall, I don’t think Grommet should support removing focus behavior globally as it will open users to accessibility issues. The outline color can be customized globally using the theme https://storybook.grommet.io/?path=/story/theme--focus, and as @srallen mentioned, if the outline is not your best solution, you may want to consider other style options to make sure the app is still accessible. I’m curious to hear what others are thinking as well.

**Comment by srallen** [comment]
Focus styles should not be turned off by default as they are necessary for accessibility: https://a11yproject.com/posts/never-remove-css-outlines/

Making the default false will create issues, many that might be unknown to devs that do not have experience with design and developing to specifically meet accessibility guidelines.

The primary use is for keyboard interaction, but they're useful for users that might not necessarily be using a screen reader as it can create a visual cue to move attention or help with contrast. 

The only accessible option Grommet should consider is trading the current focus styles for a different set of styles, but do not disable them. However, this could potentially create a lot more work and maintenance. Outline is the built in standard, the default cross-browser, and a predictable behavior for users.

**Comment by iMerica** [comment]
The bug here is that this outline appears as you click on items AND after. It should display when tabbing items only, and other styles can be applied onClick (e.g active property which changes button color or box shadow).

The prop option is called `focusIndicator`, but it's currently leaves an outline for 3 types of events: tabbing, on click, after click.

The solution is to break these up into separate controls and make the "on/after Click" default to false and tab outline focus default to true.

Currently Grommet is encouraging a bad accessibility practice because it leaves developers with only one choice for removing outline on/after click: setting `focusIndicator` to false. This disables everything, including the color while tabbing.

**Comment by srallen** [comment]
The click event triggers the focus pseudo-class, and focus is on that HTML element, so a focus outline is appropriate for the "on" instance. 

Doing a double check, though, I did think the focus outline persistence after click on a button was a bug because I did think browsers removed it after the click event, but I am incorrect... check out the native behavior on buttons:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

The focus outline appears on click and persists.

There is a [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) pseudo-class, but it's not fully cross browser supported and even then, again, a bad idea to have inconsistent behavior between mouse and keyboard:

> It may not be obvious as to why the focus indicator is appearing and disappearing if a person is using mixed forms of input. For users with cognitive concerns, or who are less technologically literate, this lack of consistent behavior for interactive elements may be confusing.

**Comment by ShimiSun** [comment]
This issue id duplicated to #3642. we can continue the discussion there.
Please check out my comment there https://github.com/grommet/grommet/issues/3642#issuecomment-574814825

**Comment by iMerica** [comment]
For anyone arriving here via Google, Slack, here is a temporary fix:

```css
button {
  outline: none !important;
  box-shadow: none !important;
}
```
