### ISSUE TITLE
Button focus persists after clicking it and retains an unfinished animated state

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3706]
### Summary
Very strange button behavior. The animation is not completed until you click elsewhere. Which suggests buttons implicitly have "state". 

### Expected Behavior

I expect for buttons to never surprise me, maybe an animation on click or a color change on hover. Once you start trying to reinvent the wheel with surprising animations and finite state machines, buttons become too surprising and frustrating to use.

⚠️ **Clicking one button should not animate another button**  🚨

### Actual Behavior
Total confusion about something that is supposed to be dead simple.

### URL, screen shot, or Codepen exhibiting the issue
![weird](https://user-images.githubusercontent.com/487897/73498613-63102280-4383-11ea-936a-d18d5e760072.gif)

### Steps to Reproduce

```jsx
            <Button
              hoverIndicator={false}
              label={'A'}
              plain={true}
              focusIndicator={false}/>
            <Button
              color={'dark-1'}
              plain={false}
              primary
              focusIndicator={false}>
              B
            </Button>
```

- Click Sign up.
- Observe the awkward behavior that occurs: theres two aimations hovering and clicking.
- Clicking one button, animates the other

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version: Chrome  79.0.3945.130 
- Operating System and version (desktop or mobile): macOS

**Comment by iMerica** [comment]
Temporary Fix:

https://gist.github.com/iMerica/c1112b61509ddef1693b0abecf9726c7

**Comment by ShimiSun** [comment]
Regardless of the related fix for this issue, I'm wondering if we can add a control to the `transition` i.e. animation of the Button. According to StyledButton, the transition is hardcoded (unless using plain). would that be something you'll be interested in?

**Comment by larshisken** [comment]
@ShimiSun 

I know this is still a discussion. But I'd very much like to use this feature. Therefore I already created a PR.

**Comment by ShimiSun** [comment]
@larshisken, yes! really nice follow-up, I'll get your PR in after the feedback is incorporated,  hoping you'll be able to use it soon!

**Comment by jcfilben** [comment]
Looks like #3828 only solved part of the issue. When you click on a button and the move your mouse away and then hover on the button the hover styling doesn't get applied unless you click elsewhere before hovering https://codesandbox.io/s/grommet-v2-template-forked-b74uv?file=/index.js

**Comment by taysea** [comment]
I think part of what is happening is that after Button B is clicked, it is the active element in the DOM (we don't show focus indicator when mouse is used to click the button but it does still receive focus so if the user were to begin using the keyboard it would start from there). That being said, when an element has focus, we don't also apply the hover animation, which is why you don't see the hover animation until you click somewhere else (remove focus from the button) and hover again.

Wondering if we should be allowing hover behavior to occur even when an element is in focus?

**Comment by felisio** [comment]
Hey guys, like @jcfilben wrote in the comment above the issue still happening, so any idea when that is gonna be fixed? 
Or we should open another issue to resolve that?
Thanks. 

![b-gromm](https://user-images.githubusercontent.com/647676/159544719-e7df7a19-95e3-42bb-9d69-e5259ef2f63d.gif)

**Comment by jcfilben** [comment]
Hi @felisio I think a new issue could be created for this since the title and description for this current issue is really a separate issue that has already been solved. Would you be willing to file a new issue for this? Also if you are interested you can take it a step further and file a pull request for this. For more info checkout the [contributing guide](https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md).

**Comment by felisio** [comment]
Hey @jcfilben thanks for the feedback, I'll open a new issue for that, also I'll take a look into the contributing guide to see how can I help with that issue. 😎

**Comment by jcfilben** [comment]
Thanks for opening a new issue! I will go ahead and close this one.
