### ISSUE TITLE
Select Component: Selected value is not displaying

### ISSUE THREAD

**Issue by salman-trimulabs** [grommet/grommet#3919]
### Expected Behavior

Selected item should display in holder

### Actual Behavior

Selected item is not displaying

### Codesandbox

https://codesandbox.io/s/fancy-sun-q4374

- Grommet version: 2.12.0
- Styled Components: 5.0.0

**Comment by myktra** [comment]
I added `valueKey` and made sure your value is set to the value of that key.

Would that work for you?

```
      <Select
        labelKey="name"
        valueKey="id"
        placeholder="Select"
        options={data}
        value={value}
        onChange={({ option }) => setValue(option.id)}
      />
```

**Comment by ericsoderberghp** [comment]
Thanks @myktra, that's correct.

The way the code is in the sandbox, the `options` are objects, and the `value` being set in the `onChange` corresponds to the `labelKey`. But, `Select` isn't able to map the supplied `value` to any of the `options` because it is comparing a `value` like "Value 6" with the options and `"Value 6" !== { id: "6", name: "Value 6"}`.

**Comment by salman-trimulabs** [comment]
Thanks @ericsoderberghp, after adding `valueKey` things are working as expected.
Bit background: I was using version `2.8.0` previously and thing working without mentioning `valueKey`. After updating the version to `2.12.0` i got this unusual behaviour.
