### ISSUE TITLE
Select field value propagation broken in version 2.11.3

### ISSUE THREAD

**Issue by chris-grandinetti** [grommet/grommet#3934]
When version 2.12.0 was installed, several integrators found an issue with select component which resulted in null values being passed through forms.  This was caused by a change that passed string as values rather than objects in the onChange.

This commit shows the changes that caused the regression:
https://github.com/grommet/grommet/commit/28e0c7c5a9e1246942258941992229b95b72e2b5#diff-19aa4813d5217c4120837104c9b593ffR87

### Expected Behavior
When objects are passed as values, the onChange should pass the value rather than null

NOTE:  An email with details on this, including screenshots were sent to @ShimiSun 

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Thanks for filing a github issue, it will help us track and communicate the progress of the issue better. 
In the future, it will help us provide quicker attention and understanding of the issue if you can provide reliable code reproduction of the problem outside of its local ecosystem.

For better transparency of the issue, and see if other users from the community experienced anything similar, I'll post the full information I got on this thread:

Hi Chris,
  In one of Grommet's own storybook examples, they show this example code using Select component:
 

 
And we can see that code works one way in 2.10 (with data a list of Objects), and differently in 2.12 (with data as an array of Strings).
 
2.10:
![image](https://user-images.githubusercontent.com/6320236/78721208-501a5100-78e4-11ea-92ac-dbb46c3e7691.png)

 
2.12:
![image](https://user-images.githubusercontent.com/6320236/78721214-54466e80-78e4-11ea-9e03-3c10801ad70f.png)

 
This is an example of what broke for us.
 
Yuiry has coded a fix for us that works in both 2.10 and 2.12, but it is still probably a good idea at this point for our team to have a task for reviewing our uses of Grommet and make sure we are in alignment with their latest documentation (since what we originally coded against, may not be best practice anymore -- even if it is still in their own examples).
 
(Yuriy:  Please jump in to correct/improve on this if I misrepresented anything here.)
 
Thanks,
-Matt

**Comment by RyanCCollins** [comment]
Hey Shimi,

Here is a codesandbox example showing the issue: https://codesandbox.io/s/keen-ptolemy-wr0so

**Comment by ericsoderberghp** [comment]
The tricky part with the existing API is that there isn't a way to indicate what `valueKey` is to be used for.

scenario 1: `valueKey` indicates what field in the `options` objects should be used for testing equality between `value` and `options` items. In this case, `value` and `onChange(({ value }) => {}` have both `value` and `options` being objects. This was the prior behavior, which should have been preserved.

scenario 2: `valueKey` indicates what field in the options objects should be used to generate the `value` property. In this case, `value` and `onChange(({ value }) => {}` contain the result of applying the `valueKey` to the `options` objects. This became the new behavior based on the existing documentation:

**Comment by RyanCCollins** [comment]
@ericsoderberghp I like that solution! Thank you for looking into this.

**Comment by RobertoSnap** [comment]
Also had problem with this, looking forward to the next release.

For any other, if you are getting `Cannot read property 'function valueKey`
![image](https://user-images.githubusercontent.com/4772930/79432147-ba5d8080-7fcb-11ea-85c5-8fb742f7cbcc.png) i think its related to this.

Use version 2.11.2 or release after 2.12.0.

**Comment by ShimiSun** [comment]
Fix available on 2.13.0. thanks for reporting!
