### ISSUE TITLE
Accordion Panel does not expand when rendered in a child component

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#3960]
### Expected Behavior
The AccordionPanel should be expandable when used in a child component

### Actual Behavior
When nested in a child component, the AccordionPanel does not expand after version 2.11.4 of grommet.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/elastic-goldstine-zfifk?file=/src/App.js

### Steps to Reproduce
See the codesandbox above.  Try to open one of the accordion panels in the first example. In the second example, you will see that if you did not have a child component and nested the AccordionPanel directly under you will see that the accordion panels expand.

Also, notice that in version 2.11.3, the accordion works (you can change the version of grommet in codesandbox). 

### Your Environment

- Grommet version: 2.11.4
- Browser Name and version: Any
- Operating System and version (desktop or mobile): Any

**Comment by YuriyKovalcuk** [comment]
Please feel free to contact me for some details as well
I am also in Grommet slack channel @Yuriy Kovalchuk

**Comment by ShimiSun** [comment]
@YuriyKovalcuk & @RyanCCollins , Thanks for reporting! This issue is fixed on the stable branch, feel free to try it out by pointing your grommet package.json to "grommet": "https://github.com/grommet/grommet/tarball/stable" and let us know if it works as expected.
The fix will be officially available on our next official grommet release. Keep us posted.
