### ISSUE TITLE
FormField is leaking `size` into the DOM.

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4003]
When applying FormField label styles (see #3998), for example`size`, the prop is being leaked to the DOM while it shouldn't. 

_Originally posted by @ericsoderberghp in https://github.com/grommet/grommet/pull/3998_
```
Not part of this review per-se, but we shouldn't be leaking `size` into the DOM.
```

**Comment by MikeKingdom** [comment]
Seems to be an issue for the Text component in general.

styled-components takes the props for Text and uses @emotion/is-prop-valid to decide whether to include them on the resulting element (label in this case.) Since 'size' is valid for some elements (input and select) it includes it on the label (it's not picky.)

styled-components 5.1 has an option to provide a shouldForwardProp function which can filter out certain properties from getting to the target element.
