### ISSUE TITLE
margin aren’t scaling for Tabs as they do for Box.

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4025]
I have been testing on Small and large screen, apparently on small screens margin='large' doesn't value the same on Tabs than on Box.

### Expected Behavior

I think the expected behaviour is that the value of margin="large" is the same on Tabs than on Box if both are at the same screen size/page.

### Actual Behavior

On small screens, comparing Tabs and Box components with margin "large" and being on the same page, box margin is 24px and Tabs margin is 48px.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-ec7on?file=/index.js

### Steps to Reproduce

Not sure if there is a specific scenario, but as simple as the codesandbox you can test. Also not sure if other components does the same or not.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac

**Comment by IanKBovard** [comment]
Before I attempt to fix this. @ShimiSun was this an intentional choice?

**Comment by ShimiSun** [comment]
@IanKBovard I'm not sure it was, I would like to understand first why does Tabs isn't acting as responsive by default, and whether it is a side effect of intentional in the code.

**Comment by jjalonso** [comment]
Also the tab title (Button > div) itself has a tiny 12px margin, is that intentional too? or it should be 0px ?

I say this because even aligning left a Tab, and just down a Box (Like the example) still the tab has a 12px margin and doesn't align perfectly with the box.

**Comment by IanKBovard** [comment]
Here's what I found so far.

Here are the generated classnames for the Tabs Box
![Screen Shot 2020-04-30 at 5 27 24 PM](https://user-images.githubusercontent.com/21990914/80765333-66dd4d80-8b08-11ea-9f1d-a3b66f815dc2.png)

![Screen Shot 2020-04-30 at 5 27 11 PM](https://user-images.githubusercontent.com/21990914/80765365-765c9680-8b08-11ea-8e7b-16a5a41e3b28.png)

it looks like .kwxiNF classname is overriding the media query. not sure why this happens.

If i wrap the tab with StyledBox instead of StyledTabs it fixes the problem.

![Screen Shot 2020-04-30 at 5 29 39 PM](https://user-images.githubusercontent.com/21990914/80765484-bface600-8b08-11ea-826d-0dc98d642481.png)

**Comment by ShimiSun** [comment]
The issue is fixed, thanks for reporting!
