### ISSUE TITLE
Tab titles don't appear if icon is present

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#4055]
### Expected Behavior
Both the icon and the title show on the tab.

### Actual Behavior

Only the icon appears.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-np8d7?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

See CodePen.

### Your Environment
Win10/Chrome

- Grommet version: 2.12
- Browser Name and version: Chrome, latest
- Operating System and version (desktop or mobile): Win10

**Comment by ShimiSun** [comment]
Hi buddy, the Tabs `icon` is a new feature and currently not officially released yet, your code is supposed to work after it will be released, [see a POC](https://v2.grommet.io/tabs?c=AQ0HgFQQwIwZ2AMwDYFMAeA+AUKP5oZgAXAS2LQF4AiQ4ARmuFIGMB7AO0oG8wBJdhzgA6AILFiAJygsynYAHpMAXxz51wMACE26JKWTJgABygATGsiiSA5qiZRkpG12otUHYqklMYMgNY2kmwArhwW1DLungC0jGoa6vyCIuJSMnIcwHCkAF6oNOhWtvaKCYkgYAo6WLgVVYTlGpCwJORUtK0ATEysnDzJnCIQkqioAPLGmWWqdRWaNfqGJuaW1nYOTi400V4+wH4sgcFhEVEexDE9TfODQsIjY5PTOfmFxRtlc-XVujf4DVg-zwLSIZAoBU6RAAzL1BAMBENhABhawzYEAxaIAxGUwRD6lRzOVy7by+AJBULhGjnWKwjFJRH3VGSbJ5SFFdalJTfRJVGoMzQKRq88DC2BwTBAA).
 You can always use the stable branch instead of an official release to enjoy grommet's latest and greatest, for more info https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
