### ISSUE TITLE
Box children don't get gap if wrapped in a fragment

### ISSUE THREAD

**Issue by arthurRbr** [grommet/grommet#4076]
If you have a component that returns an array mapped into a list:

```
// ListComponent
return (
   <>
        {[1, 2, 3, 4].map(n => (
          <Box>child</Box>
        ))}
   </>
)
```

A component that uses that list cannot set a gap between elements in the list.
```
<Box gap="large">
    <ListComponent />
<Box>
```

**Comment by MikeKingdom** [comment]
This issue would be difficult to resolve given how Box currently puts a div spacer between children when it renders. The problem is when Box renders, ListComponent is a single child and Box can't tell it renders a Fragment until after ListComponent renders which is way too late. If Box contained a direct Fragment child (rather than the Fragment being rendered by a child component) it could tell that and react accordingly, but that is much less useful than the example in this issue.

**Comment by ShimiSun** [comment]
@MikeKingdom, since I don't think we'll attempt to fix it or change how it behaves at this point, can you add a comment to the documentation of `gap` on fragment children?

**Comment by MikeKingdom** [comment]
I changed the Box gap documentation in #4338 to specifically mention it won't put gaps between children in a Fragment.
