### ISSUE TITLE
Text doesnt apply vertical margin as shown on documentation

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4093]
Apparently Vertical margin doesnt work on Text component.

### Expected Behavior

expect to see vertical margin

### Actual Behavior

Only work with horizontal margin

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/text-margin-12ois?file=/index.js

**Comment by ShimiSun** [comment]
Hi @jjalonso, thanks for reporting, a quick solution for the sandbox you described is to have a joint parent container for the two Text components https://codesandbox.io/s/text-margin-2siqs?file=/index.js.

**Comment by jjalonso** [comment]
Yeah it work but I though it was a bug since the doc talk about you can apply vertical margin to text.

Is that a bug or only I'm using it wrong?
 cc @ShimiSun

**Comment by ShimiSun** [comment]
we'll need to see why doesn't work without the Box parent. I'll keep this issue open for now.

**Comment by taysea** [comment]
The reason this is happening is because Text is rendered as `span` in the DOM and `span` by default has display inline which only takes up horizontal margins. That is why the vertical margin is having no effect. However, once Text is wrapped in a Box, it has display block, allowing the vertical margin to take effect. 

Applying `display: inline-block;` to StyledText seems to remedy this issue, but was there reasoning prior to leave Text as inline display by default?

**Comment by jjalonso** [comment]
In case it will not accept vertical margin.
Doc should be changed.

**Comment by ShimiSun** [comment]
An idea is to improve the documentation that the vertical `fill` will be applied when using the component within a Layout component such as Box.

**Comment by jjalonso** [comment]
It definitely need to be annotated on the margin section in the doc.
