### ISSUE TITLE
`gap` prop can be used with RadioButtonGroup and CheckBoxGroup but is not shown in documentation

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4183]
### Expected Behavior

Docs should show developers that `gap` is a prop they can set when implementing `RadioButtonGroup` or `CheckBoxGroup`.

### Actual Behavior

`RadioButtonGroup` in [ has `gap` prop](https://github.com/grommet/grommet/blob/6219ed0086c8673692ff78ca6a31d710f550ed79/src/js/components/RadioButtonGroup/RadioButtonGroup.js#L20), however it is not in Docs -- it is a Box, so perhaps the documentation simply mentions accepts all Box props (similar to how Header, Footer, etc. handle)
  - Same applies to CheckBoxGroup

### URL, screen shot, or Codepen exhibiting the issue

![Screen Shot 2020-06-12 at 12 22 52 PM](https://user-images.githubusercontent.com/1756948/84534616-7cb56500-aca7-11ea-817f-57f0edec1e0a.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by britt6612** [comment]
@ShimiSun would you want something similar in the docs as Header has or just add `gap` as a prop within `RadioButtonGroup` and `CheckboxGroup` Im not sure if you want to mention all the props of `box` or just `gap`
<img width="625" alt="Screen Shot 2020-07-06 at 11 45 31 AM" src="https://user-images.githubusercontent.com/42451602/86623094-34bff000-bf7e-11ea-846d-6f111a2cd9b3.png">

**Comment by ShimiSun** [comment]
@britt6612 Similarly to Header, and we usually mention only the props that have the default value set and not all the props the Box has to offer (since the list will be too long).
In the example you shared above you can see only the Box props that Header is is setting default values for, and the same should happen for RadioButtonGroup and CheckBoxGroup, which I think only setting the `gap` as a default, but it will be better if you can double-check that.

**Comment by britt6612** [comment]
linking PR 
https://github.com/grommet/grommet-site/pull/175

**Comment by ShimiSun** [comment]
Fixed on the website, closing issue! thank you all for reporting & solving!
