### ISSUE TITLE
Would like ability for RadioButton label font-weight to be specified via theme

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4186]
### Expected Behavior

Able to specify font-weight for RadioButton labels in my theme.

### Actual Behavior

I believe the label is inheriting the global font-weight.

Use Case: HPE Design System designs call for RadioButton label to be font-weight: medium/500, however the default label is [currently implemented](https://github.com/grommet/grommet/blob/6219ed0086c8673692ff78ca6a31d710f550ed79/src/js/components/RadioButton/RadioButton.js#L23) as a `span` inheriting global font weight

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jackjwilliams** [comment]
I'd like to take a stab at this as a first issue. Here is what I was thinking (after reviewing your component and theming system):

1. Modify the themes/base.js and add a `fontWeight: 500` property to radioButton.
2. Update src/js/components/RadioButton/doc.js to reflect this new property, following the guidelines of the other properties
3. Update src/js/components/RadioButton/RadioButton.js to handle using this fontWeight on the span

I'm a little unsure on number 3, I tried looking for other examples but haven't found many yet. Any guidance? Would I apply that directly to the span as a fontWeight: 500, or in some kind of wrapped, 'Styled' manner for the label?

**Comment by ShimiSun** [comment]
@jackjwilliams sounds like you are heading in the right direction! 
Regarding #1, please make sure that the default behavior stays intact for backward compatibility, and only if the user specifies new font-weight it will take place and will default to the inherent behavior otherwise.
Regarding #3, applying inline style will work but we rather maintain it cleaner and apply the style via StyledRadioButton.js. take a look and see if that works for you.

In your PR, please update base.d.ts file with the new type definition to support typescript users and add a test to RadioButton-test.js if possible.

Good luck and keep us posted!

**Comment by jackjwilliams** [comment]
@ShimiSun thanks for the info.

Regarding the backwards compatibility remark, are you saying that I should not augment base.js with the default font weight of 500, and only look for and apply a font weight if a user adds it?

**Comment by ShimiSun** [comment]
Yes. The standard is usually just adding a comment on base.js with the new key.
e.g 
```
// font: undefined
```

**Comment by jackjwilliams** [comment]
Ah, I see, thank you.

I misunderstood the request. I thought @halocline wanted it to DEFAULT to font-weight: 500, but he just needs the ability to set it according to the HPE Design System (otherwise it should keep its inherent behavior).

**Comment by jackjwilliams** [comment]
I created a PR for this @ShimiSun.
