### ISSUE TITLE
InfiniteScroll props.show only works when props.show < props.step IF replace = true.

### ISSUE THREAD

**Issue by valkenburg** [grommet/grommet#4334]
### Expected Behavior
```
<InfiniteScroll
                    replace
                    show={20}
                    step={10}
                    items={items}
                >
```
should scroll down to item at index 20 upon the first rendering.

### Actual Behavior
doesn't scroll, unless we set props.step to a value > 20, such that the item is anyway rendered, **or** we remove the flag `replace`. Only then, InfiniteScroll will scroll to it.

### URL, screen shot, or Codepen exhibiting the issue

[https://codesandbox.io/s/grommet-v2-template-zb62p?file=/index.js](https://codesandbox.io/s/grommet-v2-template-zb62p?file=/index.js)

### Steps to Reproduce

enable / disable 'replace' to see the effect.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): OS X 10.15.4

**Comment by halocline** [comment]
Upon initial investigation, I am finding a few oddities. Documenting for context:
- `show` behavior does not scroll to specified index: [Storybook Example](https://storybook.grommet.io/?path=/story/infinitescroll--show-118th-item) --> should contain index 117
- when `show` is specified, the result set does not render items past the show indexes page: [Storybook Example](https://storybook.grommet.io/?path=/story/infinitescroll--show-118th-item) --> replicate by attempting to scroll past index 150
- when `show` is specified, result set displays duplicated items at `step` index (default 50): [Storybook Example](https://storybook.grommet.io/?path=/story/infinitescroll--show-118th-item) --> replicate by scrolling to 'item 50', you will see two 'item 50' in the result set. Also result in a console warning for duplicate key of 'last'
- Was able to replicate case where `replace && show > step` only displays first page of results, does not display results page containing show index, replace page does not execute.

Because of these discreet behaviors, I will likely submit a PR/PRs addressing the first 3 scenarios. Then submit PR for the more complex scenario where `replace`, `show`, and `step` are potential factors.
