### ISSUE TITLE
Formfield Validation does not show up 

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#4375]
I have a use case where we need to show the error message returned from validation function of formfield. But when the error is returned via promise (backend API), it doesn't show up.

Created a codeSandBox replicating the same issue, https://codesandbox.io/s/fervent-ride-z1fdw?file=/src/App.js

Used setTimeout for simulating promise.

**Comment by novykh** [comment]
Hello @ypinneka , there are two reasons for this:
1. You are not returning the actual error string.
2. FormField validations do not work in async.

I kind of [updated](https://codesandbox.io/s/fast-mountain-pe999?file=/src/App.js) your codesandbox snippet, to validate on form change.

You can do the validation on other events (of the form or the formfield) as well, but in order to display them, you need to keep and update their state.

**Comment by ypinneka** [comment]
Hi @novykh 

I tried this solution prior, but it does nto cater to all use cases, please see the sndBox, https://codesandbox.io/s/boring-bird-kbkzt?file=/src/App.js
In here, if we pass errors via Form component & the specific formfield has a required already, then the error from Form does not show up.

Note: we have a very specific case where we are wrapping the validation function to create a custom error component.

**Comment by novykh** [comment]
`required` takes precedence over form `errors`. In such cases, pass the custom error directly to the formField. Hope it helps.
https://codesandbox.io/s/elastic-snow-khi2x?file=/src/App.js

**Comment by ypinneka** [comment]
Oh, I missed that there is an error prop for formfield as well. Will try and let you know ! Thanks !

**Comment by ShimiSun** [comment]
In addition to the great suggestion coming from @novykh, you can also use the new `onValidate` function provided on the stable branch. I'll be closing this issue. feel free to reopen or file a new one if needed.
