### ISSUE TITLE
Search component when used in header lacks padding between logo and search input

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#440]

**Comment by tearsofphoenix** [comment]
I prepare to use `Search` in the `Header`.

**Comment by ericsoderberghp** [comment]
Can you add a  CodePen illustrating this?

**Comment by L0ZZI** [comment]
Seems to have padding on the right side of the fields. but the logo doesn't seem to have pad.

![screen shot 2016-06-22 at 2 36 30 pm](https://cloud.githubusercontent.com/assets/1753301/16284703/4d41586c-3887-11e6-988d-8f9457c40223.png)

**Comment by jwijay** [comment]
@L0ZZI The missing header padding between the logo and search components is caused by the pad options being set on the Header component in Brand Central. I.e.
`<Header appCentered={true} size="large" pad={{horizontal: 'medium', vertical: 'none'}}>`

Pad defaults for the Header component have since been set to 
`{ horizontal: 'none', vertical: 'none', between: 'small'}`, which resolves the issue (https://github.com/grommet/grommet/commit/901ff1ccefd928228737598987b0ab93c25c6a66#diff-d5bba4fc125cca74ea565dd662d8ca44R116).

Removing the pad option from the Brand Central Header (i.e. `<Header appCentered={true} size="large">`) results in padding between the logo and header.

![screen shot 2016-06-22 at 3 24 35 pm](https://cloud.githubusercontent.com/assets/10161095/16289034/756135be-388d-11e6-8462-08543ccb91de.png)
