### ISSUE TITLE
adjustPad is only compatible with px values

### ISSUE THREAD

**Issue by jkkealii** [grommet/grommet#4496]
### Expected Behavior

Either expected:

1. `adjustPad` to work correctly with a `rem` value.
2. Note in documentation that `px` values are encouraged when defining a custom theme.

### Actual Behavior

1. `adjustPad` did not work correctly with a `rem` value. Found when using TextInput with an Icon and a custom theme with `global.control.border.width` set to `.125rem`. End result was the Icon being placed very far away from the edge of the TextInput, due to `adjustPad` using `parseMetricToNum` which converts `.125rem` to 125.
2. I was not able to find documentation that encouraged the use of `px` to avoid issues.

### URL, screen shot, or Codepen exhibiting the issue

[Code Sandbox](https://codesandbox.io/s/grommet-v2-template-forked-kpd44?file=/index.js)

### Steps to Reproduce

1. Use TextInput with an icon.
2. Use theme with `global.control.border.width` set to `.125rem`
3. Observe icon placement is incorrect.

### Your Environment

- Grommet version: 2.15.0
- Browser Name and version: Firefox Developer Edition 81.0b3
- Operating System and version (desktop or mobile): MacOS Catalina 10.15.6

**Comment by IanKBovard** [comment]
This isn't a problem with px or rem. If you change your example to px you'll still see your problem. The issue is that grommet uses the parsefloat function to calculate the position for the icon in textinput. A simple fix, you just need to add a leading 0 to your border width.

https://codesandbox.io/s/grommet-v2-template-forked-0oje2?file=/index.js

**Comment by ShimiSun** [comment]
Feel free to reopen with additional information if needed.
