### ISSUE TITLE
Not possible to select a date range from a previous month with DateInput

### ISSUE THREAD

**Issue by martinRoss** [grommet/grommet#4507]
### Expected Behavior
When a user goes back a few months in the DateInput, they should be able to select a start date and end date in that month, regardless of the existing range value. This is common behavior (e.g. when the page loads, show the current period but let the user select a date range in the past.)

### Actual Behavior
When you go to a previous month and click on a new start date it updates correctly. However, then selecting a new end date in that month only moves the start date forward. I think we need to keep track of the previous click and if a subsequent click is on a date later than the previous click's date, it should set the end date, not the start date.

### URL, screen shot, or Codepen exhibiting the issue

[https://storybook.grommet.io/?path=/story/dateinput--range](https://storybook.grommet.io/?path=/story/dateinput--range)

### Steps to Reproduce

1. Click the button to open the DateInput drop
2. Click the "<" previous month button, say 2 times for good measure
3. Click the first day of the that month
4. Click the last day of that month

### Your Environment

Seeing this locally and on the hosted storybook.

- Grommet version: 2.15
- Browser Name and version: Tested on Firefox 80 and Chrome 85.0.4183.83
- Operating System and version (desktop or mobile): macOS 10.15.5

**Comment by abnersajr** [comment]
@martinRoss I take a look on how this work.
Actually you can change the end date clicking on the `actual` end date. This will remove the end-date selected.

- Then if you click again in a date before the other selected date it change the order of start-end.

- Then if you click again in a date after the other selected date remains as start and adds the end date.

- If you click in a date after the `end` date it activate the change as `end` date mode. And you can change it without uncheck how I wrote above.

In case you have one website that has the behavior you suggest to put as reference I would appreciate it.

**Comment by martinRoss** [comment]
Hey @abnersajr thanks for getting back to me and I appreciate the explanation! I love and appreciate the new DateInput--my only thought is how can we make this intuitive so a user doesn't need an explanation on how to use it? And the above flow feels clunky when the end date is not in the current view.

One example to look at reports in Google Analytics. The date picker there is a bit different in that 1) they show two months at once and 2) they create distinct input boxes for the start_date and end_date. With those input boxes though, they can put the focus on which one is being edited. If you don't have access to Google Analytics I can do a screen recording or set up some time to chat if it's helpful!

**Comment by abnersajr** [comment]
Definitely the experience isn't the best one.
Having two different input's definitely would be a better option. But I'm not sure which path people would like to go.
I would like to have more people discussing about this to maybe update this.

**Comment by martinRoss** [comment]
For the UI, I was thinking something simple like this where you can click or focus on start vs. end date to indicate which is being updated.

<img width="488" alt="Screen Shot 2020-09-15 at 10 05 35 AM" src="https://user-images.githubusercontent.com/1999530/93221230-7d90e380-f73b-11ea-8743-877942751fdb.png">

It probably still needs smarter "switching" logic too, but this would provide the proper affordances to the user to let them know which date they are adjusting.

**Comment by taysea** [comment]
Thanks for opening this issue @martinRoss! It's a great point what you bring up around not being able to select an end date if you go back some months. This is based on how the logic is currently working in Grommet's calendar. The way it is currently implemented is that whichever date you just selected (for example start date) becomes the one that will be altered if you click a new date. This poses benefits for behaviors where you're choosing a start date and realize you clicked the wrong date, so now you want to correct that error. However, this same behavior is the one causing the issues with being able to choose an end date.

I am going to look deeper into the logic here to see how the details are working. I think even if the default behavior were to stay as it exists, the behavior you noted should still be supported for sure.

**Comment by IanKBovard** [comment]
@taysea best solution might be to check if the second selected date is before the first selected. If so, make the new selection the start date.

**Comment by taysea** [comment]
I think that makes sense @IanKBovard for a certain use case, but I don't think we can assume that grommet is in the mode of "selecting end date" depending on how the user has set up their dateinput.

Starting with the same set-up as Martin noted above, if we:
1. Go back 2 months
2. Click a date such as May 5 (selecting start date now)
3. Now, we want select an end date in this month (the previously selected end date is not visible, and grommet is thinking we want to select the start date again since the date we just selected is the start date) but can't

I did some exploration on other dateinput components/use cases and found that in cases where a range of dates is selected, while there may be a single calendar, there almost always 2 separate masked inputs controlling start and end date. Here's a summary of behaviors I found:
- User can control if they are adjusting `start` or `end` date by putting focus into either the start or end date input
- If `start` date > `end` date, set `start` date to this date and clear `end` date
- If `end` date < `start` date, set `start` date to this date and clear `end` date
- For booking sites (like AirBnb and Kayak):
    - after  `start` is selected, automatically switches user to select `end` date
    - once on `end` date, any new selection continues to affect `end` date (by this logic, each input is continuing to affect their respective date)
    - to adjust `start` date again, user needs to click into `start` date input

So the question is, does the Calendar continue to select the date mode it previously selected or does it switch to select the opposite (once I select a start, my next click will be end date)? I'm thinking about how we may be able to support both logic types for users, and some thoughts are:
1. Add prop called `dateSelectionMode` where the default would keep the logic we have but supplying value of `switch` would make the adjust date toggle from start to end automatically
2. Add prop called `activeDateSelector` or something which takes the values of `start` or `end` and indicates which date should change. User would be responsible for handling their own logic and would likely toggle `activeDateSelector` via their own state variable.

Not settled on these but they were some initial thoughts after exploring last week. Any thoughts @ericsoderberghp @IanKBovard ?

**Comment by IanKBovard** [comment]
I don't use the calendar component that much, but what makes most sense to me is not locking in start date until you select a date that proceeds it. 

Something like this:

- select a startDate - Sept 15th
- select another date - Sept 13th(this is the new start date)
- select another date - Sept 20th(start date is now locked in)
- now any selection we make in that range will change the endDate, startDate is locked in

to select a new range:

- select a new date Sept 5th
- endDate is cleared and new startDate is Sept 5th
- selection logic starts over

For fine tuned controls, I do agree that having two inputs would accomplish that. Airbnb is probably the best example of that. Once I have start and endDate locked in, I can change my startDate without having to reset the entire selection. There are a few things to think about though.

Control flow:
focus endDate input
once endDate is selected on the calendar i should automatically transition to the startDate selection without having to select the startDate input.

> So the question is, does the Calendar continue to select the date mode it previously selected or does it switch to select the opposite (once I select a start, my next click will be end date)? I'm thinking about how we may be able to support both logic types for users, and some thoughts are

My inclination is to not support both logic types. Having this logic and the controls mimics the more popular calendar interfaces, which seems sufficient enough to me.

**Comment by taysea** [comment]
Good responses, @IanKBovard. It does seem like a general behavior is to toggle from start --> end date. And so, maybe this is the logic that we should be employing as well in grommet's Calendar. Edge cases would be:
- if `end date` is the one being selected, but end date < start date, update start date instead
- if `start date` is being selected and end date is already selected, but start date > end date, update start date and clear end date.

I think at the least if we choose not to update Grommet's Calendar logic in this direction, an example should be provided that demonstrates how multiple inputs can be used with a dual Calendar to achieve the desired behavior. However, I'm not sure how much of Calendar's internal logic may get in the way here. I'd like to touch base with @ericsoderberghp again once he's back in office to see what he thinks.

**Comment by ShimiSun** [comment]
Thank you for reporting and for the great discussion, @taysea had contributed a fix and it will be available on our next official release and currently on the [stable-branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F). Stay tuned 💟
