### ISSUE TITLE
DateInput change year after UI dropdown displays results in incorrect value

### ISSUE THREAD

**Issue by trumanpurnell** [grommet/grommet#4535]
### Expected Behavior
When the UI date input dropdown is showing, changing the year manually should result in the calendar scrolling and date changing.

### Actual Behavior
The UI appears to change, but upon selecting a new date from that new year the value changes to that date but the old year.

https://storybook.grommet.io/?path=/story/dateinput--form

Steps to reproduce:

1) Pick any date from UI drop down
2) Open dropdown again and change year manually 
3) 
      a) If the UI scroll-animates its change, the new year will work
      b) If not, the stale year issue will occur

See link from grommet slack
https://slack-files.com/T04LMHMUT-F01BCJSTC5P-7792c8c3b6

### Your Environment
- Grommet version: latest
- Browser Name and version: All
- Operating System and version:  desktop and mobile

**Comment by leossantiago** [comment]
Sent a PR adressing that.
The issue occur when Calendar animate prop is true and you manually change the date to something over a year apart from the current one (usually today's date, because it defaults when the input is not valid).

**Comment by trumanpurnell** [comment]
Hey there! Thanks for all of your hard work, it is mostly fixed! There still persists a strange, harder-to-reproduce bug! Shall I create a new issue or should this one just be opened back up? 

Steps to reproduce:

1) Head over to the trusty storybook: https://storybook.grommet.io/?path=/story/dateinput--form
2) Select (not type) the date 11/04/2020
3) Change (by typing) the year to 2012. (Oddly you have to type fast, if you type slow it works)
4) Select what would be 11/04/2012
5) The date returns to 11/04/2020

Here's a screencast: 
https://slack-files.com/T04LMHMUT-F01CF7EG7J8-86b34e379c

Thank you!

**Comment by leossantiago** [comment]
Hey @trumanpurnell !
I'll take a look and try to solve it.

Tried your steps, and it looks like something I pointed in PR #4541 , but I thought it was fixed. It looks like the second change is being set before the transition (from november to october, as its < than a year) finishes. That's why it has to be done quickly. Also, if you take a close look, the days showed in calendar are from October 2020.

November 2020 page starts on 1st
October 2020 page starts on 27th
November 2012 page starts on 28th

But when you follow your steps, calendar says November 2012, but the page starts on 27th.

**Comment by ShimiSun** [comment]
Reopened the issue.
Thanks for taking the challenge @leossantiago, much appreciated 💟

**Comment by leossantiago** [comment]
hey guys! Had an epiphany before bed and had to test an idea. Ended sending another PR addressing the issue haha.
I'm confident that all bugs are solved now. But I'd love if you guys could check it and test DateInput behavior. Thanks :heart:
@trumanpurnell @ShimiSun @jcfilben
