### ISSUE TITLE
FormField or TextInput shows focus indicator even when focusIndicator prop is set to false on both

### ISSUE THREAD

**Issue by jaksm** [grommet/grommet#4567]
### Expected Behavior

Focus indicator borders defined in theme should not be visible when `focusIndicator` prop is set to `false`.

### Actual Behavior

Focus indicator borders are visible around: `<FormField>`, `<TextInput>` and label

![image](https://user-images.githubusercontent.com/30727082/94992955-dbbc2400-058d-11eb-8971-04a8bc93c64d.png)

Provided codesandbox example is broken for some reason so I will provide relevant code here:
```tsx
  const contentProps: FormFieldProps['contentProps'] = {
    focusIndicator: false,
    // Toggle background color & border
    background: isEditing || isHovered ? colors.backgroundBack : undefined,
    direction: 'row',
    gap: 'xsmall',
    border: {
      color: isEditing ? colors.brand : undefined,
    },
  }
```

```tsx
    <Form
      value={{ [name.current]: newValue }}
      onChange={handleTextInputChange}
      onSubmit={handleSubmit}
      ref={formRef as any}
    >
      <FormField
        {...formFieldProps}
        name={name.current}
        htmlFor={id.current}
        label={label}
        contentProps={contentProps}
        onClick={handleFormFieldClick}
        onBlur={handleFormFieldBlur}
      >
        <TextInput
          {...textInputProps}
          id={id.current}
          name={name.current}
          focusIndicator={false}
          color={colors.textStrong}
        />
        {isTouched && <Button type="submit" icon={<MdSend size="1.25em" />} plain />}
      </FormField>
    </Form>
```

### Your Environment

- Grommet version: `^2.14.0`
- Browser Name and version: `Brave@Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)`
- Operating System and version (desktop or mobile): Windows 10

**Comment by leossantiago** [comment]
Even without a working codesandbox example, would you mind providing the component code and custom theming (if there's any) used to reproduce your screenshot?
It might be helpful to anyone who tackles this issue. Thanks :)

**Comment by jaksm** [comment]
@leossantiago Sure, this is the full component code:
```tsx
import {
  Button,
  Form,
  FormField,
  FormFieldProps,
  FormProps,
  TextInput,
  TextInputProps
} from 'grommet'
import * as React from 'react'
import { MdSend } from 'react-icons/md'
import useHover from '../hooks/useHover'
import { useColors } from '../hooks/useTheme'

type AvailableFormFieldProps = Pick<
  FormFieldProps,
  'disabled' | 'error' | 'help' | 'info' | 'margin' | 'pad' | 'required'
>

type AvailableTextInputProps = Omit<
  TextInputProps,
  'value' | 'placeholder' | 'onChange' | 'onSelect' | 'onSuggestionSelect'
>

type AvailableFormProps = Omit<FormProps<unknown>, 'value' | 'onChange' | 'onSubmit'>

export interface EditableTextProps {
  label: string // e.g. User name
  value?: string
  onChange: (value: string) => void
  formProps?: AvailableFormProps
  formFieldProps?: AvailableFormFieldProps
  textInputProps?: AvailableTextInputProps
}

/**
 * Inline text edit component.
 * @TODO Fix focusIndicators, issue posted here https://github.com/grommet/grommet/issues/4567
 * @param props
 */
const EditableText: React.FC<EditableTextProps> = (props) => {
  const { label, formFieldProps, textInputProps, value, onChange } = props

  const name = React.useRef(label.toLocaleLowerCase().replace(/ /g, '-')) // e.g. user-name
  const id = React.useRef(`${name.current}-${makeId(10)}`) // e.g. user-name-s84dRASED4

  const [isEditing, setIsEditing] = React.useState(false)
  const [formRef, isHovered] = useHover()

  const handleFormFieldClick = () => setIsEditing(true)
  const handleFormFieldBlur = () => setIsEditing(false)

  const colors = useColors()
  const contentProps: FormFieldProps['contentProps'] = {
    focusIndicator: false,
    // Toggle background color & border
    background: isEditing || isHovered ? colors.backgroundBack : undefined,
    direction: 'row',
    gap: 'xsmall',
    border: {
      color: isEditing ? colors.brand : undefined,
    },
  }

  const [newValue, setNewValue] = React.useState<string>(value || '')
  const [isTouched, setTouched] = React.useState(false)

  const handleTextInputChange = (value: any) => {
    if (!isTouched) setTouched(true)
    setNewValue(String(value[name.current]))
  }

  const validate = (newValue: TextInputProps['value']) => {
    if (!newValue) return false
    if (newValue === '') return false

    return true
  }

  const handleSubmit = () => {
    const isValid = validate(newValue)
    if (isTouched && isValid) {
      onChange(newValue)
      setTouched(false)
      setIsEditing(false)
    }
  }

  return (
    <Form
      value={{ [name.current]: newValue }}
      onChange={handleTextInputChange}
      onSubmit={handleSubmit}
      ref={formRef as any}
    >
      <FormField
        {...formFieldProps}
        name={name.current}
        htmlFor={id.current}
        label={label}
        contentProps={contentProps}
        onClick={handleFormFieldClick}
        onBlur={handleFormFieldBlur}
      >
        <TextInput
          {...textInputProps}
          id={id.current}
          name={name.current}
          focusIndicator={false}
          color={colors.textStrong}
        />
        {isTouched && <Button type="submit" icon={<MdSend size="1.25em" />} plain />}
      </FormField>
    </Form>
  )
}

function makeId(length: number): string {
  let result = ''
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  const charactersLength = characters.length
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength))
  }
  return result
}

export default EditableText
```

And here are theme overrides which override the theme generated with [Grommet Themer](https://theme-designer.grommet.io/):
```ts
const overrides: ThemeType = {
  global: {
    control: {
      border: {
        radius: '0px',
      },
    },
    drop: {
      border: {
        radius: '0px',
      },
    },
    input: {
      weight: 'normal',
    },
  },
  anchor: {
    textDecoration: 'none',
  },
  button: {
    border: {
      radius: '0px',
    },
  },
  formField: {
    margin: {
      vertical: '0',
    },
    content: {
      pad: '0',
    },
    label: {
      weight: 'normal',
      size: 'small',
      margin: {
        horizontal: '0',
      },
    },
    round: false,
  },
  tab: {
    pad: { vertical: 'small', horizontal: 'medium' },
    color: 'text-strong',
    active: {
      background: 'brand',
    },
    border: {
      color: 'transparent',
      active: {
        color: 'brand',
      },
    },
  },
}

export const theme = deepMerge(baseTheme, overrides)
```

**Comment by leossantiago** [comment]
Taking into consideration the related expected behavior, even though `focusIndicator` conveys the idea of general use, this prop is intended to be used only when prop `plain` is set. `plain` prop has a few different implementations among grommet Components, but it usually removes `outline`, `border` and `padding` (or at least some of those), but the component still shows a `box-shadow` indicator when focused.

The best example of behavior I could give you is Button component.

```
<Grommet>
    <Button plain label="with focus box-shadow" />
    <Button plain label="without focus box-shadow" focusIndicator={false}  />
</Grommet>
```

When reproducing your code, two components have `box-shadow` style when focused: `FormField` and `TextInput`. This happens because you're setting `onClick` prop into `FormField`, which turns it into a clickable element and thus it can be focused. `TextInput` receives styling when focused by default.

After some tests, I discovered that components such as TextInput, TextArea, etc have the `focusIndicator` prop listed in docs but they don't seem to be working (remove focus indicator when plain). I'm working on that. But that doesn't include your related issue, as your components are not `plain` and I don't remember seeing any Grommet component prop that disables `box-shadow` focus in default mode (i.e. not `plain` etc). So, I'll tag @ShimiSun as she'd be able to give us some insight into this discussion.

My suggestions (of what should be done) are:

1. Fix `focusIndicator` in TextInput, TextArea (and any other) when `plain` + update docs for clarification. (I'm working on that);
2. Consider the possibility of creating a new prop for components such as FormField and inputs (that can be focused in general), to prevent focus effect. but I don't know if that is needed since it can be achieved using themes*. Maybe creating a `focus` prop inside theme would be easier to use?

*no focus box-shadow using themes. I guess the downside of this approach would be it affects all elements of that type.
```
  formField: {
    extend: {
      "box-shadow": "none",
    },
  },
  textInput: {
    extend: {
      "box-shadow": "none",
    },
  },
```

**Comment by IanKBovard** [comment]
looking into this now. I do agree that it could be more intuitive to control the border, and focus styles.

Here is a codesandbox with a workaround using theme. You could use themecontext to apply it to specific formfields. I'm not a huge fan of this though.

https://codesandbox.io/s/grommet-v2-template-clickable-box-forked-01m0e?file=/index.js

**Comment by IanKBovard** [comment]
Here's a sandbox thats a little more clear.

https://codesandbox.io/s/grommet-v2-template-clickable-box-forked-jseqp?file=/index.js

**Comment by leossantiago** [comment]
So, for a better explanation, I'll split this issue in two parts: FormField behavior and TextInput behavior.

- **FormField behavior**

This component is based on `<Box>`, thus it receives a focus outline when `onClick` prop is set. Box-kind components can also receive `focusIndicator` prop (differently of input components, those don't need `plain` prop to use `focusIndicator`), and it looks like it's working as expected.

FormField also has a child called `<FormFieldContentBox>`, which wraps the content passed by the user as children of `<FormField>` and is also based on `<Box>`. The prop `contentProps` you're using controls the properties of `<FormFieldContentBox>` and not, for instance, the props of `<TextInput>` nor `<FormField>` itself. Since this ContentBox is not receiving an `onClick` prop, it's no use passing `focusIndicator`.

To achieve what you're looking for, you should set `focusIndicator` as prop of FormField. Note that it'll still have a border outline when focused. This can be removed by manually styling it with `outline: 'none';`.

I don't think anything should be changed on grommet components regarding this part of the issue.

- **TextInput behavior**

TextInput alongside TextArea and MaskedInput make use of an internal styling called `inputStyle`. Right now, `focusIndicator` wasn't working as intended in those components. PR #4753 addresses that, fixing it. Note that `focusIndicator` prop on inputs should **only** work when using `plain` prop.

---
IMHO that resolves the issue, but let us know if you still have any unexpected behavior after this.

**Comment by jcfilben** [comment]
I think this issue can be closed
