### ISSUE TITLE
Global.colors.text affects Text only when deepMerged to grommet -theme

### ISSUE THREAD

**Issue by oskari** [grommet/grommet#4606]
### Expected Behavior
Global.colors.text should affect the color of Text component.

In the [theming documentation ](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation) it's not listed as affected component, but in the [component page ](https://v2.grommet.io/text) it's listed as a theming option.

### Actual Behavior

Global.colors.text only seems to affect Text when custom theme is deepMerged with grommet -theme

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/text-component-color-issue-9y52t

### Your Environment

Dependencies as listed in codesandbox:
grommet ^2.12.0 (2.15.1)
grommet-icons ^4.4.0 (4.5.0)
react ^16.6.1 (16.13.1)
react-dom ^16.6.1 (16.13.1)
styled-components 5.0.1

**Comment by taysea** [comment]
I've concluded that the issue here is if a theme does not have `theme.global.colors.background` defined, then the `theme.global.colors.text` will not be applied. It does not have to do with deepMerging with grommet, however the reason the CodeSandbox demonstrated this is because `grommet` theme is the first place that we have a predefined value for `theme.global.colors.background`. Currently, base.js does not have any defined value for background and neither did the custom theme. However, as soon as you define a value for background in the custom theme, the text color is applied as expected.

Two options here to resolve:
1. Leave code as is and document that users should define `theme.global.colors.background` in their theme.
2. Put a check in `StyledGrommet` for when a user does not define a background prop on Grommet or theme value, we can still provide a color value to CSS:
```
${props =>
  !props.background &&
  !props.theme.global.colors.background &&
  props.theme.global.colors.text &&
  `
color: ${normalizeColor(props.theme.global.colors.text, props.theme)};
`}
```
Any thoughts on preferred direction? @ericsoderberghp

**Comment by ericsoderberghp** [comment]
Good analysis. I think option #2 above would be a breaking change. Option #1 would reflect the implemented behavior.

The reason we behave this way is to allow grommet components to be used within a non-grommet outer context, where the outer context sets the background and text colors. But, we wanted a way to provide a reasonable default when a background theme color was provided. You could argue that we should also have not set a text color in the base theme. But, we cannot change that without that being a breaking change either.

**Comment by taysea** [comment]
You're right, option 2 could be a breaking change. So it seems like the best solution to avoid breaking changes is to adjust the documentation to note that the theme must have a `theme.global.colors.background` for the global text color to take effect?
