### ISSUE TITLE
backgroundIsDark (?) fails to detect values in linear-gradient background

### ISSUE THREAD

**Issue by oskari** [grommet/grommet#4609]
My experience with Grommet is still limited but I am under assumption that it does try to detect component background and adjust light or dark text usage based on it. If this is not the case, then my assumption on this issue is probably wrong.

### Expected Behavior

Text to have good contrast in dark linear-gradient background

### Actual Behavior

Text has bad contrast in dark linear-gradient background. This is probably almost impossible to make fool-proof due to the nature of linear-gradients, but maybe there is some other way to control the text in these cases?

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-background-linear-gradient-rgba-u3oi7

### Your Environment

Dependencies as listed by codesandbox: 
Package | Version
-|-
Grommet | ^2.12.0 (2.15.1)
grommet-icons | ^4.4.0 (4.5.0)
react | ^16.6.1 (16.13.1)
react-dom | ^16.6.1 (16.13.1)
styled-components | 5.0.1 
- Grommet version: 2.15.1
- Browser Name and version: FF Dev 82.0b
- Operating System and version (desktop or mobile): MacOS Catalina

**Comment by ericsoderberghp** [comment]
You are correct that grommet attempts to calculate the luminosity of a background to determine whether dark or light text color would provide better contrast. There are some situations that grommet is unable to detect though, such as images or gradients. The design intent is that you should be able to explicitly indicate via something like: `background={{ color: 'linear-gradient()', dark: true }}`. But, I tried that and it doesn't appear to be working. I think the starting place for this issue is to address using linear-gradient() via `background.color`.

**Comment by oskari** [comment]
I didn't notice the `dark: boolean` in `background` props, that seems logical option to solve this, just have to handle linear(&radial?)-gradient usage in color so the css property is formed correctly.

**Comment by ShimiSun** [comment]
Thank you for reporting, issue is fixed and available on the stable branch and will be available officially on the next release.
