### ISSUE TITLE
add `weight` to Anchor 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#4626]
Add `weight` property to the Anchor component, similar to how Text has it.

This is an ask from the CCS team.

**Comment by ShimiSun** [comment]
@MikeWalrath any idea why not to use the `fontWeight` theme prop as the theme suggests? 
Also, allowing this property might break the alignment of the Anchors look & feel in the applications.

**Comment by ericsoderberghp** [comment]
This approach allows the caller do something for particular Anchors, without it being applied theme-wide. Also, the font size remains the same, so the vertical alignment shouldn't be an issue.

**Comment by leossantiago** [comment]
Hey everyone! Just sent a PR addressing that.

Followed Text component behavior, as suggested by @MikeWalrath . 

I noticed that the way `font-weight` is modified is very  similar when it's hovered and when it's not, but since `theme : anchor > hover > fontWeight` is not set by default (considering grommet theme), it'll stay as defined by weight (prop or theme). Setting it in theme would be the only way to modify weight when hovered (without matching normal weight).

I'm okay with that behavior, but since this question popped in my mind before sending the PR, I'd like to ask you guys if that's okay leaving it as it is. What do you think?

**Comment by ShimiSun** [comment]
@leossantiago thanks for the PR buddy, nice work, I left a couple of comments so let me know what you think.

I think we should be OK with the behavior of weight+hover as long as the theme `hover.fontWeight` will still apply on top of the `weight` prop if defined. 
I'm OK if for now we won't set a specific weight mechanism on hover until the need arises, to keep the implementation simple.

**Comment by ShimiSun** [comment]
@leossantiago Thanks for the super quick fix! 
@MikeWalrath This new prop is now available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be officially released on the next grommet core release.
