### ISSUE TITLE
Header with "fixed={true}" and colorIndex is not working

### ISSUE THREAD

**Issue by JhansiSimma** [grommet/grommet#473]
When i add an attribute "fixed={true}" to Header with colorIndex, the color is not showing up. 

if i use below the color is coming fine:
<Header key="header" large={false} pad={{horizontal: "small"}} colorIndex="neutral-1" responsive={true}>

If i add "fixed" then color is going:
<Header fixed={true} key="header" large={false} pad={{horizontal: "small"}} colorIndex="neutral-1" responsive={true}>

I am using Grommet 0.5.3 version

**Comment by alansouzati** [comment]
good catch. I've created a codepen to illustrate the issue:

http://codepen.io/grommet/pen/VaMwdy

**Comment by genyded** [comment]
+1 - this is an issue if we need fixed headers and also need to control colors. I also spent about a half an hour trying to figure this out before I searched here in prep for opening an issue and found this one.

**Comment by genyded** [comment]
Any ETA on this? Have a client that is wanting us to pursue other UI framework for their projects just  because of this. We're using pre-compiled css for now and still learning intuitcss or we'd PR it. Seems like the offender in the compiled CSS is item in the `Styles` window of the screen shot below...

<details>
<summary>Browser Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/3081676/15271373/579ee18e-1a0b-11e6-8d4f-050b6e3b5a2b.png)
</details>

If that style is unchecked, the header stays fixed and the colors are correct. We tried overriding things with React inline styles, but apparently the Grommet components ignore those - so we cannot any effective way to work around this. Would hate to have to throw away our investment in this, but our client is not happy about it.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/c36f549b7f924a4304b1d160dfc70a7624333ee9

I'm really sorry about the long wait. We are getting busier and busier and we are counting on the community to send PRs for fixes like this. Thank you for investigating it further, I've basically applied your suggestion to actually fix the issue. So I would say you actually fixed this one. ✌️
