### ISSUE TITLE
aria-hidden toggled outside of application

### ISSUE THREAD

**Issue by joelachance** [grommet/grommet#4739]
I'm using the Select component inside of the Layer component. When Select is clicked, this toggles all aria-hidden labels outside of the application.

This application is a third-party app on a Shopify page, and the theme is toggling overlays based on the value of aria-hidden, causing some issues. 

### Expected Behavior

Only toggle aria-hidden labels associated with the focused components.

### Actual Behavior

All aria-hidden labels on the page are being toggled.

### URL, screen shot, or Codepen exhibiting the issue

NOTE: The bug doesn't work in CodePen. This code needs to be rendered locally to see the effect.

https://codepen.io/joelachance/pen/rNLQYZK?editors=1111

### Steps to Reproduce

Click select, and watch aria-hidden labels in parent elements toggle.

### Your Environment

- Grommet version: 2.15.1
- Browser Name and version: Firefox 81.0.2
- Operating System and version (desktop or mobile): Catalina 10.15.7

**Comment by jeferson-sb** [comment]
@ShimiSun I believe this somewhat related to this function 
https://github.com/grommet/grommet/blob/6e68e5039bf467eaababd42110e382da3cbe97a5/src/js/utils/DOM.js#L118

**Comment by ShimiSun** [comment]
@joelachance thanks for reporting. I'm guessing it is because you are using a modal Layer, have you tried `modal={false}` and see if it works for you?
Also, Select had gone through lots of changes on the last few releases, can you please verify that you still see the problem on grommet v2.16.2?

**Comment by joelachance** [comment]
I also thought it was also due to using a Layer, but moving it outside of the Layer didn't seem to change this behavior.
I'm currently using 2.16.2 and still seeing this issue.

@ShimiSun thanks for taking a look!

**Comment by taysea** [comment]
@joelachance Just to confirm I understand your scenario, the theme you're referencing is a Shopify theme that is relying on `aria-hidden` to decide the styling of certain things?

**Comment by joelachance** [comment]
Corret @taysea

**Comment by taysea** [comment]
Just summarizing my understanding of what is happening. The situation is centered around how Grommet toggles `aria-hidden` for elements in the DOM. Currently, `aria-hidden` values in the DOM are controlled by two functions: `makeNodeFocusable` (sets aria-hidden to false) and `makeNodeUnfocusable` (sets aria-hidden to true). These functions are called by `FocusedContainer` which is only used by Drop (and subsequently, any components built using Drop, like Select).

When FocusedContainer has `trapFocus={true}` (the default value for Drop and components like Select, meaning the keyboard should only be able to access elements within the Drop) which was introduced as a prop in [this PR](https://github.com/grommet/grommet/pull/4378), other body elements will have an `aria-hidden="true"`.

In the current implementation, Grommet loops through **all** body elements that are not an ancestor of the FocusedContainer:

https://github.com/grommet/grommet/blob/6e68e5039bf467eaababd42110e382da3cbe97a5/src/js/components/FocusedContainer.js#L34
https://github.com/grommet/grommet/blob/6e68e5039bf467eaababd42110e382da3cbe97a5/src/js/components/FocusedContainer.js#L35
https://github.com/grommet/grommet/blob/6e68e5039bf467eaababd42110e382da3cbe97a5/src/js/components/FocusedContainer.js#L36

In the issue filed, I am assuming that because Grommet is looping through all of the body elements (including those outside of what might be the grommet app and into the Shopify app it is contained within), the toggling of aria-hidden is causing issues with the Shopify theme.

@ericsoderberghp My main question is should Grommet only toggle `aria-hidden` values on elements inside of the Grommet tag?

A second question I have relates to my [comment on the trapFocus PR](https://github.com/grommet/grommet/pull/4378#discussion_r471794494). trapFocus is currently creating a different navigation experience for keyboard vs mouse users.

With Drop, mouse users can still interact anywhere on the page but keyboard users are restricted to the Drop. Is this behavior desired or would we want to align those interactions?

Asking that in context of this issue because it seems if `trapFocus` were not set to true (meaning both mouse users and keyboard users could interact with any part of the page when a Drop is open), then the `aria-hidden` issue filed here would not be seen.
