### ISSUE TITLE
Font appears bigger while the page is loading

### ISSUE THREAD

**Issue by ibhag** [grommet/grommet#474]
The fonts appear bigger and bolder when the page is loading and becomes normal once loaded. 
Though this appears on all browsers, its more prominent on IE. Please see attached screen shots. 
![image](https://cloud.githubusercontent.com/assets/17637919/14179490/e48982ea-f77c-11e5-8571-cd909f52c05f.png)

![image](https://cloud.githubusercontent.com/assets/17637919/14179458/c6fe5084-f77c-11e5-9cb2-94d9fb2c0823.png)

**Comment by bryanjacquot** [comment]
@ibhag, this is the classic, "Flash of unstyled text" (https://css-tricks.com/fout-foit-foft/) issue that is caused by the browser rendering the page before the fonts have been loaded.  Once the fonts are rendered, the page appears correct.  You can read about options to deal with this, but as of now what you're seeing isn't desirable, but is expected.
