### ISSUE TITLE
Unable to properly control Select when mapped from state array

### ISSUE THREAD

**Issue by benwainwright** [grommet/grommet#4744]
One of the pages on my app contains a number of `<Select />` components. Because there are six of them, they are identical, and they all draw from the same data source, I'm creating them programmatically by mapping a hardcoded array.

Problem is, when I do it like this, the component don't seem to be correctly controlled by the state array, no matter what I do.

### Expected Behavior

Clicking 'Clear' button after making some selections resets the selects to "empty"

### Actual Behavior

Clicking 'Clear' button after making some selections does nothing

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-o4ls9

### Steps to Reproduce

1. Click on first `<Select />`, choose "foo"
2. Click on second `<Select />`, choose "bar"
3. Click on the "Clear" button

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version:  Google Chrome 86.0.4240.183 (Official Build) (x86_64)
- MacOS 10.14.6

**Comment by ShimiSun** [comment]
I don't think this issue is a grommet issue. The issue you are introducing results from the way you are handling your data structure, states, and the overall react behavior.
Try to split up the code into two select components with a controlled value states that will be set to `undefined` when clicking on `Clear`.
