### ISSUE TITLE
DropButton / Drop getting background color from parent Box

### ISSUE THREAD

**Issue by cirdes** [grommet/grommet#4788]
After upgrading to grommet version 2.16.0, my DropButton content background changed to "black"

Code exemple: 

```
 <Box background="black" width="medium">
    <DropButton
          label="Fancy Selector"
          dropAlign={{ top: "bottom", right: "right" }}
          dropContent={<Box pad="large" />}
     />
</Box>
```

### Expected Behavior
With grommet version 2.15.2:
 
<img width="429" alt="Screen Shot 2020-12-01 at 4 45 44 PM" src="https://user-images.githubusercontent.com/727781/100789037-ab113300-33f4-11eb-87e5-30a018998f46.png">

### Actual Behavior
With grommet version 2.16.0:

<img width="414" alt="Screen Shot 2020-12-01 at 4 47 30 PM" src="https://user-images.githubusercontent.com/727781/100789216-e9a6ed80-33f4-11eb-8195-2bad8fa27e10.png">

https://codesandbox.io/s/background-theme-forked-yzio1?file=/index.js

### Your Environment

- Grommet version: 2.16.0
- Browser Name and version: Google Chrome  87.0.4280.67
- Operating System and version (desktop or mobile): macos big sur 11.1 Beta - desktop

**Comment by ShimiSun** [comment]
Hi buddy, thanks for raising this question, previously, grommet wasn't supporting dark/light mode for the background color of Drop & Layer components.
In grommet v2.16.0 we added an [enhancement](https://github.com/grommet/grommet/pull/4645) to support the adjustment of the background color according to light/dark modes. If this enhancement does not work for you you can always customize your theme to hard code the background color to `white` instead of considering the dark/light colors.
```
const theme = {
    ...
    drop: {
        background: '#ffffff',
    }
}
```

Let me know what you think.

**Comment by cirdes** [comment]
@ShimiSun, thanks! It did the job.
