### ISSUE TITLE
Tip component ignoring global theme text color

### ISSUE THREAD

**Issue by jlilly** [grommet/grommet#4950]
Text in the Tip component does not use the global theme text color, and simply uses black.

### Expected Behavior
Text in the Tip component should be the color specified in the theme.

### Actual Behavior
See above. It does not matter if you wrap the content in a Text tag.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-402ly

### Your Environment
- Grommet version: 2.16.3
- Browser Name and version: Firefox 85, Chrome 87
- Operating System and version (desktop or mobile): Desktop Ubuntu

**Comment by ericsoderberghp** [comment]
Hmm... something doesn't feel quite right here in setting the text color even though `plain` has been passed in to Drop. `plain` typically indicates that the caller will take care of any styling. I think we should instead revisit how Tip is behaving and ensure it is setting up the styling. I'm inclined to say that if Tip is called with `plain`, that works as it does today. If Tip is not called with `plain`, then the Box it wraps the content in should include background and text color styling. Although, since that's all that StyledDrop has removed due to `plain`, I'm wondering why we don't just call Drop with `plain={plain}`?
