### ISSUE TITLE
gulpfile.babel.js blocking grommet-toolbox "gulp dev" task

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#498]
The default "gulp dev" task in gulpfile.babel.js is blocking the groomet-toolbox "gulp dev" task. 
```
gulp.task('dev', () =>
  console.error(
    'Running "gulp dev" at Grommet root folder is not supported. If you want to start the website, run "gulp dev" at docs folder'
  )
);
```

**Comment by alansouzati** [comment]
This is the expected behavior. Just to clarify, what are you expecting by running gulp dev in grommet core?

**Comment by karatechops** [comment]
The 'gulp dev' task error is referring to the 'docs' folder which I don't see in this repo. I'm currently developing/extending Grommet components and am looking to streamline the development process. I'm presuming I should npm link a new Grommet project to my local distribution copy of Grommet, would this be the recommended path?

**Comment by alansouzati** [comment]
correct, we need to update the message. Can you craft a Pull Request to update the console message properly?

The grommet website has been moved to a separate repo:

`https://github.com/grommet/grommet-docs`

To test grommet components I usually use the website, so I'm glad you are going in the same direction.

If you clone `grommet-docs` at the same workspace as you have `grommet`, as in:

```
  /grommet-workspace
    - /grommet
    - /grommet-docs
```

Inside `grommet-docs` you can run `gulp dev --useAlias`. This command will start the website pointing to your grommet core instead of using the one from node_modules.

Hopefully this helps, the configuration to make this work is in here:

https://github.com/grommet/grommet-docs/blob/master/grommet-toolbox.config.js#L58

and here

https://github.com/grommet/grommet-docs/blob/master/gulpfile.babel.js#L35

**Comment by karatechops** [comment]
Thanks for the info, this works great. I'll spend some time today looking over Grommet Toolbox to get a better understanding of the tool as I'm not seeing hot reloading working properly out of the box. 

I submitted a PR regarding the console message.

**Comment by alansouzati** [comment]
Yeah I can experience the issue with hot reloading as well.
