### ISSUE TITLE
TextInput icon misaligned when used in box with direction=row-responsive

### ISSUE THREAD

**Issue by kariwhitcomb** [grommet/grommet#5045]
### Expected Behavior
TextInput's icon should be inside the TextInput's border even when parent box is using direction='row-responsive' and screen is small.

### Actual Behavior
The icon seems to be using much more vertical height (maybe equal to the width of the textinput) than needed when responsive mode is triggered.

### URL, screen shot, or Codepen exhibiting the issue

Codepen: https://codesandbox.io/s/summer-leaf-5ob5r?file=/src/App.js&resolutionWidth=446&resolutionHeight=675

![Screen Shot 2021-03-09 at 11 18 32 AM](https://user-images.githubusercontent.com/12547826/110518332-358ac200-80c9-11eb-8838-714b1f582af6.png)

### Steps to Reproduce

1. Create a structure like:
```
     <Box direction='row-responsive' justify='start' align='end'>
       <Box flex='shrink' basis='medium' direction='row' responsive={false}>
         <TextInput icon={<Search />} />
        </Box>
        <Box flex={false} margin={{ left: 'medium' }}>
          <Text>Fixed content</Text>
        </Box>
      </Box>
```
The scenario here is a search box that I want to shrink as needed to make room for the Fixed content on the same row.  But when the screen gets narrow, they should wrap to two lines - search box and the fixed content below. 

This works for large screens, but on the small screen size, the icon moves out of the search box and the textinput line is way to large.

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: Chrome  89.0.4389.82 
- Operating System and version (desktop or mobile):  MacOS 11.2.1

**Comment by ericsoderberghp** [comment]
I think this is an issue with how the parent Box of the TextInput is structured. Because it has a `basis="medium"`, that is being carried over to the responsive column layout case. This is causing the TextInput to fill the space of that Box. I think the right way to manage this is to not set the `basis` when the parent has `direction="row-responsive"`, because that isn't the desired behavior. I think just removing the `basis` from the Box that is a parent of the TextInput results in the correct behavior.

**Comment by kariwhitcomb** [comment]
makes sense.  thanks
