### ISSUE TITLE
Snapshots failing when upgraded to grommet v2.17.0

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#5103]
Reverted the below line in PR (https://github.com/grommet/grommet/pull/4959/files) & tests are passing as usual.
     
 Earlier: setResponsive(getBreakpoint(window.innerWidth, theme));
 Now: setResponsive(getBreakpoint(document.body.clientWidth, theme));

**Comment by ypinneka** [comment]
https://codesandbox.io/s/react-testing-library-demo-forked-2vzce?file=/src/__tests__/hello.js

**Comment by ShimiSun** [comment]
I think the PR you pointed out is a fix that is important for Grommet to support a better responsive behavior on mobile. So the snapshot changes might make sense and I don't think it is a bug at this point.

Please elaborate what are the snapshots changes you are experiencing on your end with more details.

**Comment by shen6653** [comment]
Is it the expected behavior if document.body.clientWidth is 0?

**Comment by ShimiSun** [comment]
@shen6653 I wouldn't know because I'm not sure how your tests have configured and build, and I'm not sure what you are trying to test so I can't tell.
Did anything on the actual app change? Are you actually seeing breaking changes on the app? Sounds like it might be the way you are taking the snapshots, and the way they are configured.

**Comment by shen6653** [comment]
@ShimiSun  our tests start failing because they are now being rerendered in mobile screen size. before picking up this new grommet version, our tests are rendered in desktop size. By default, testing library sets the window size to desktop size and sets document body size to 0. wondering if Grommet should try to compute app container size based on document body size only if it has been set to a non-zero value, and use window size if document body size is 0 ...

**Comment by ShimiSun** [comment]
@shen6653 In grommet we run comprehensive test suits, and we have not experienced this issue with any of our snapshot environments, so neither jest, react-testing, or chromatic identified a problem on Grommet v2.17.0.
Without technical details on how you are creating the snapshots and what are your configurations, I can't really understand the root cause of the problem or help further.

**Comment by shen6653** [comment]
@ShimiSun in our test library, if we explicitly set document body size to desktop window size for all our snapshot tests, the tests are all passing. the problem is with the default grommet container size. It was default to desktop size (window size), now it's default to mobile size.

**Comment by ShimiSun** [comment]
@shen6653 How can you ensure that your default window size for tests is desktop and not mobile? what is your configuration?

**Comment by shen6653** [comment]
@ShimiSun we didn't have any configuration. Looks like by default, jest sets the window size and leaves the document body size as 0? After experiencing this problem, we added test setup configuration to explicitly set document body size, and that has fixed the test regressions.

**Comment by ShimiSun** [comment]
Let's keep this issue open to see if any other users from the community are experiencing window size issues after upgrading and could share their context.

**Comment by ericsoderberghp** [comment]
In the ResponsiveContext PR we are adding, the snapshot shows that the jest environment indicates a "medium" size.
