### ISSUE TITLE
Validate/onChange Function on Formfield not getting trigger when used with Select

### ISSUE THREAD

**Issue by shreyashah7** [grommet/grommet#5122]
I have a select field which is wrapped with formfield. I have provided my function in validate prop of that formfield which validations happening onChange. My function is not getting triggered at all even when a select any of the option from select field.

### Expected Behavior

It should trigger validate function on formfield when selecting options from select field

### Actual Behavior

Not getting triggered

### URL, screen shot, or Codepen exhibiting the issue

```
<FormField
   dataTestId="formfield-select"
   label="test"
   name="myselect"
   required
   validate={[(value) => {
       console.log("value:", value);
   ]}
>
      <Select
         dataTestId="selectfield"
         name="myselect"
         options={["small", "medium", "large"]}
       />
</FormField>
```

### Steps to Reproduce

On the above code, you will not see console.log in developer tools when selecting any option from the Select Input field.

CC: @ypinneka @shen6653

**Comment by taysea** [comment]
Documenting what I have found so far. It seems that the `onChange` function being called in Select is being registered as an `click`/`keyDown` event type as opposed to `change` like other components such as TextInput or CheckBox. Because of this, the Form is not receiving any notice that the `onChange` happened and therefore does not run the validation.

Looking into how a `change` event may be able to be registered or the `click`/`keyDown` event may be able to trigger the validation.

**Comment by bbansalWolfPack** [comment]
I am also facing the same issue, do we have any ETA on the fix?
