### ISSUE TITLE
Enhance DataTable to support pinning multiple columns

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5130]
### Expected Behavior

If multiple columns are pinned, they will stay fixed to their position if there is horizontal scroll.

### Actual Behavior

Columns scroll to the left until they hit the left edge of the DataTable which causes multiple pinned columns to stack on top of each other.

### URL, screen shot, or Codepen exhibiting the issue

View when screen === 'small':

https://codesandbox.io/s/multi-pin-columns-e6758?file=/components/TableExample.js

### Steps to Reproduce

1.  View table when screen === 'small'
2. Scroll horizontally
3. Notice how the 3 left columns are pinned but they become stacked on each other.

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: Mac Chrome
- Operating System and version (desktop or mobile): Mac OS Mojave

**Comment by leossantiago** [comment]
Just opened a PR addressing that. Would love your review on that @taysea.
By the way, introducing multiple pinning also increases the chances of cases where pinned content will take the entire available space. I know this depends heavily on the user rather than Grommet, but still makes me wonder if we should worry about those situations. Should we also introduce, for instance, use cases where only one sticky column is visible at a time? Maybe replacing the previous one once it reaches the previous offset position. Of course, that would be optional and the default case would be displaying all pinned content. What do you think?

**Comment by taysea** [comment]
Thanks @leossantiago I've dropped some initial comments. I agree that pinning multiple columns could increase the chances that columns will take up the entire width, but I think that would be on the user to know their data table content and make a design decision around how many columns would be pinned.

Re: only show on sticky column at a time, I think we should leave that for a separate discussion if there seems to be a need arising for that functionality.
