### ISSUE TITLE
Layer component stays rendered in test suites

### ISSUE THREAD

**Issue by andrewthamcc** [grommet/grommet#5200]
### Expected Behavior

When testing the `Layer` component with React-Testing-Library each instance of test should render a new component.

### Actual Behavior

The Layer component remains rendered to the testing DOM despite providing a cleanup function `afterEach(cleanup)`. This causes tests to fail as duplicates of the component are found.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-66prc?file=/modal.test.js

CodeSandbox is having [issues running tests](https://github.com/codesandbox/codesandbox-client/issues/513) but this is an example.

### Steps to Reproduce

Create a component utilizing Grommet's Layer component, run test with React-Testing-Library, notice the Layer remains rendered across multiple tests.

### Your Environment

Only noticed after bumping to Grommet `2.17.2`

- Grommet version: 2.17.2

**Comment by jcfilben** [comment]
Hi @andrewthamcc I am wondering if you could reproduce this with a jest test within grommet since codesandbox is having issue with jest tests. I tried to reproduce using the tests from your codesandbox but the tests were behaving as expected. Also, I would think the Layer tests that we currently have wouldn't be passing if the Layer was persisting between tests.

**Comment by taysea** [comment]
Wondering if it has anything to do with this Layer change from `useEffect` to `useLayoutEffect` when we upgraded react versions? https://github.com/grommet/grommet/pull/5097

maybe if project is pointing to an older react version then this will cause issues in tests? @jcfilben any thoughts here?

**Comment by jcfilben** [comment]
In react-dom v17 `useEffect` is changed to run asynchronously, so we switched Layer to use `useLayoutEffect` which runs synchronously which is the old behavior of `useEffect`. This change fixed an issue with the Layer animation but it don't think it would be related to how the tests are being run and I don't think it would cause the Layer to persist between tests.

I did notice in the codesandbox that was shared above the versions for the `react` and `react-dom` are outdated so I think this is likely the cause of the problem

**Comment by taysea** [comment]
Hi @andrewthamcc I've checked our Layer test for 'Layer unmounts from DOM' and it is behaving correctly. I have also checked the Dev Tools in our storybook to confirm that Layer unmounts from the DOM.

Here is a screenshot of a jest test debug showing that the Layer is no longer present in the DOM after it has been set to not show:
```
  const [showLayer, setShowLayer] = React.useState(true);

  React.useEffect(() => setShowLayer(false), []);

  let layer;
  if (showLayer) {
    layer = <Layer data-testid="test-dom-removal">This is a test</Layer>;
  }
  return <Box>{layer}</Box>;
```
<img width="480" alt="Screen Shot 2021-05-06 at 1 59 25 PM" src="https://user-images.githubusercontent.com/12522275/117365843-c0432f80-ae74-11eb-8190-d0cd5d5389b4.png">

Additionally, in this video of https://storybook.grommet.io/?path=/story/layout-layer-center--center-layer, notice in the right panel how the div of the layer properly disappears when the Layer closes:

https://user-images.githubusercontent.com/12522275/117365945-ecf74700-ae74-11eb-9f6f-98d744bd66eb.mov

Can you confirm that you are using the same version of React and React Testing Library as grommet? If not, could you try upgrading to the same version and let us know if that resolves your issue?

**Comment by taysea** [comment]
Hey Andrew! Thanks so much for putting the repo together and documenting this so clearly. @jcfilben, @britt6612, and I have been looking into this today, and I wanted to summarize our findings for you here:

1. Since portals render outside of the root div in jest tests, we need to explicitly clear them beforeEach test involving them because the react testing library `cleanup` function doesn't handle it (https://stackoverflow.com/questions/67298821/jest-react-testing-library-portals-are-not-being-cleaned-up). Grommet does this in a function called `createPortal` which ensures that the DOM is cleared out before the test: https://github.com/grommet/grommet/blob/master/src/js/utils/portal.js#L4

Within our Layer-test file, we call `beforeEach(createPortal)` Because your testing setup doesn't include this `beforeEach` function, the portal is not being cleared out between tests. This is unrelated to grommet 2.17.2. I cloned your repo and reverted the dependency versions to match the react, react-dom, testing-library, and grommet versions that we used at grommet v2.16.3 and saw the tests failing with the same errors as you're experiencing here. However, once I added the `beforeEach` everything is working as expected.

<img width="1037" alt="Screen Shot 2021-05-10 at 3 22 49 PM" src="https://user-images.githubusercontent.com/12522275/117733058-c6534c00-b1a5-11eb-88a7-af530fd9a758.png">

WITH beforeEach:
<img width="401" alt="Screen Shot 2021-05-10 at 3 38 43 PM" src="https://user-images.githubusercontent.com/12522275/117733096-d703c200-b1a5-11eb-904d-f1b1598368bb.png">

It seems like the reason your project was passing prior but not with grommet v2.17.1 or 2.17.2 is because React 16 and lower treated `useEffect` differently (synchronously) than `useEffect` is treated in React 17 (asynchronously). Given this, we made an adjustment in grommet v2.17.1 to Layer to use `useLayoutEffect` (which runs synchronously like useEffect had in older versions of React). 

Recommendation: Add the following to your jest
```
beforeEach(() => {
  // make sure to remove all body children
  document.body.innerHTML = '';
  document.body.appendChild(document.createElement('div'));
})
```
