### ISSUE TITLE
selecting a suggestion in TextInput doesn't close the suggestions drop

### ISSUE THREAD

**Issue by idanhaviv** [grommet/grommet#5206]
### Expected Behavior
After selecting a suggestion, I expect no more suggestions will be presented.

### Actual Behavior
The selected suggestion is still presented in the suggestions drop, after selecting it for the 1st time.
Only after selecting that suggestion for the 2nd time, the drop closes.

### URL, screen shot, or Codepen exhibiting the issue
This can be experienced in the official Grommet Storybook https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions

### Steps to Reproduce

1. enter 'a' in the text input 
2. select 1st suggestion (it should still be displayed)
3. select it again

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: Chrome 90
- Operating System and version (desktop or mobile): desktop MacOS Catalina

**Comment by ShimiSun** [comment]
Toda @idanhaviv ! We'll take a look at the issue and will keep this issue up to date.

**Comment by MikeKingdom** [comment]
@idanhaviv Thanks for reporting this issue. 

What's happening is `<TextInput>` will pop up the suggestions drop if it the `suggestions` property changes and the input still has focus. (This was a change a couple months ago to improve how it behaves in general.) The Grommet Storybook example https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions does change the suggestions when the `value` changes as part of the `onSuggestionSelect` and this causes the drop to re-open even though it was just closed as part of selecting the choice.

A simple change to improve the storybook example is to set the suggestions based on `value` during the `onSuggestionsOpen` and `onSuggestionsClose` (as well as `onChange` which it already does) rather than in a `useEffect` which is dependent on value. This more closely models the intent and seems to work cleanly. For example:

```jsx
  const [suggestions, setSuggestions] = useState([]);
...
  const onSuggestionsOpen = useCallback(() => {
    setSuggestions(formatSuggestions(folks, value));
    setSuggestionOpen(true);
  }, [value]);

  const onSuggestionsClose = useCallback(() => {
    setSuggestions([]);
    setSuggestionOpen(false);
  }, []);
...
```

I'm proposing we change the Storybook example to do this instead.
