### ISSUE TITLE
Upgrade webpack devDependencies to ^5.37

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#5250]
### Expected Behavior
webpack devDependencies should point to the latest ^5.37

### Actual Behavior
```
"webpack": "^4.39.3",
"webpack-cli": "^3.2.3"
```

### Steps to Reproduce

1. Go to grommet/package.json
2. Upgrade webpack

### Your Environment

- Grommet version: 2.17.2

**Comment by jcfilben** [comment]
Storybook is currently only supporting webpack 5 experimentally and v6 of storybook is still trying to use webpack 4. Because of this we are holding off on the webpack upgrade until storybook fully supports webpack 5 (most likely in storybook v7).
Linking to https://github.com/storybookjs/storybook/issues/13893
More information about storybook's experimental support of webpack 5 https://storybook.js.org/blog/storybook-for-webpack-5/

**Comment by halocline** [comment]
"copy-webpack-plugin": "^5.0.4" should be upgraded when this work is done as well. v7+ only supports Webpack 5.
