### ISSUE TITLE
Any way to change the icon for clearing the Select search input ?

### ISSUE THREAD

**Issue by disbelief** [grommet/grommet#5257]
Is there any way to override/replace the "x" icon in the search input for the Select component? The icon's color and style do not match the style of my site.

I can't seem to find a theme setting to target it, and there's no prop for it in the Select component. 

Either a theme setting like `select.searchIcon = { color: string }` or a way to replace the actual icon component itself, perhaps a `searchIcon` prop on the `Select` component?

Always the same blueish "x" icon is displayed:

### URL, screen shot, or Codepen exhibiting the issue

<img width="298" alt="Screen Shot 2021-05-15 at 12 17 12" src="https://user-images.githubusercontent.com/295574/118358602-c7bbb480-b5a9-11eb-9d03-ea7d2d8de804.png">

### Steps to Reproduce

1. Render a `<Select />` component with search enabled, or play with the Playground: https://storybook.grommet.io/?path=/story/input-select-search--search
2. Open the select menu
3. Type some text in the search input
4. See the "x"
5. Try to figure out how to modify its appearance.

### Your Environment

- Grommet version: grommet@^2.16.3
- Browser Name and version: Chrome 90.0.4430.93 
- Operating System and version (desktop or mobile): macOS 11.3

**Comment by jcfilben** [comment]
The 'x' is being added and styled as blue by default because the search has the property `<input type="search">` in webkit browsers the 'x' is automatically added if `type="search"`. The css property to customize/change this is: `-webkit-search-cancel-button`. You can use the `select.searchinput` theme prop to create a custom react component for the search input of Select and then customize the css to change the appearance of the 'x'

**Comment by disbelief** [comment]
Thanks. I recently realized the blue "x" is browser-supplied when I created a vanilla search input and saw it appear there.

Sounds like a lot of work just to replace that x, and may possibly end up breaking something else in the process. But I suppose this isn't a Grommet bug so I'll close this ticket.
