### ISSUE TITLE
Range Format Error

### ISSUE THREAD

**Issue by andrewthamcc** [grommet/grommet#5261]
When clearing the text input of the Range Format `DateInput` component an error is generated: `TypeError: Cannot read property '0' of undefined`

### Expected Behavior

The user should be able to clear the Range Format input

### Actual Behavior

The user can clear the ending date value but clearing the start value will throw an error of: `TypeError: Cannot read property '0' of undefined`

### URL, screen shot, or Codepen exhibiting the issue

The error can be replicated on Grommet's storybook: https://storybook.grommet.io/?path=/story/input-dateinput-range-format--range-format

### Steps to Reproduce

clear the input in the storybook story

### Your Environment

NA

**Comment by andrewthamcc** [comment]
This error is due to the `buttonProps` in the storybook story:
```jsx
            buttonProps={{
              label: `${dateFormat.format(
                new Date(value[0]),
              )} - ${dateFormat.format(new Date(value[1]))}`,
            }}
```

When clearing the value `value` becomes undefined. When correcting this the use is still unable to clear the entire contents of the input field. When attempting the initial start date the value resets.

https://user-images.githubusercontent.com/45271739/118530273-7549d780-b712-11eb-8f79-785818b38e43.mov

**Comment by taysea** [comment]
I agree the whole date should be able to be cleared by keyboard. That is definitely an issue, maybe this issue could be reformatted to be focused on that bug.

However, I think the `buttonProps` error you documented is more an issue with the storybook implementation rather than an issue with grommet. The caller should add a check that value exists before trying to index an array index (value && value[0]). Additionally, this story is using a combination of format and buttonProps, but the docs say that "buttonProps" is only relevant when not using `format`, which this story is using: https://v2.grommet.io/dateinput?c=DwEQhgLgpgkgdgBwK4QFAAJ0CMUQPZwAKATnggM4C8A3tQDZhZR0Bc6A5ABYCW7AvnwzoAbmDpIoNABRwoAd3ThoUgJQqAdPhgBlAPLaIxbnADmqwZgIBhTmFOTqU6iLET0fFekoA+dNQGoAPTeQA#buttonProps
