### ISSUE TITLE
Remove DropButton border on hover

### ISSUE THREAD

**Issue by jayant246** [grommet/grommet#5268]
How to remove the border of DropButton , I have removed the button border by implementing style inside DropButton : `style={{ border: 'none', padding: 'none', background: 'none', outline : 'none' }}`
But, I also want to remove the border "on hover"

https://codesandbox.io/s/admiring-leakey-klgzg?file=/src/App.js

**Comment by halocline** [comment]
Hi @jayant246 - DropButton is using Button in its implementation, so for consistency it is applying the same styling as buttons throughout the rest of your app. DropButton will accept all [Button props](https://v2.grommet.io/button#props), as well as[ button styles defined in your theme](https://v2.grommet.io/button#theme).

My recommendation is to [use your theme](https://github.com/grommet/grommet/blob/master/src/js/themes/base.js#L397) to tailor your button styling to your desire. The theme has capabilities to style across all button states (e.g. active, hover, disabled, etc.). DropButton will inherit the styling you define.

If that approach doesn't work for you, please let us know. There are a couple of alternative approaches we can suggest, but recommend starting with the theme approach.

**Comment by jayant246** [comment]
Actually, I can't use theme for this button. Please suggest alternate approach.

**Comment by halocline** [comment]
> Actually, I can't use theme for this button. Please suggest alternate approach.

Bummer. So that I can better understand your situation, I'd appreciate if you could share why that's not an option.

In the meantime, if modifying theme is off the table, we have a couple options. Which approach to use somewhat depends on whether you will have a couple of instances of the DropButton vs. desiring re-use throughout your application and each has some pros/cons.

**Option 1** - Create a "StyledDropButton"
- Using styled-components, style your DropButton using CSS.
```
import styled from 'styled-components';
import { DropButton } from 'grommet';

const StyledDropButton = styled(DropButton)`
  // insert typical CSS styling here
  // or prop driven styling
`
```

- then you would call it by
```
<StyledDropButton ...drop props here />
```

**Option 2** - Use `<ThemeContext.Extend />`
- [ThemeContext.Extend](https://v2.grommet.io/themecontext)
- has a `value` prop which you pass an object with properties and values you want to override in your theme
- the object follow the shape of [theme object](https://github.com/grommet/grommet/blob/master/src/js/themes/base.js)
- The modified styling will apply to any children wrapped by the ThemeContext.Extend

```
<ThemeContext.Extend value={{ 
  button: { 
    hover: { 
      border: 'your border value', 
      color: 'your color value' 
    } 
  } 
}} >
   <DropButton ...your drop button props />
</ThemeContext.Extend>
```

Again, I highly recommend affecting your theme as primary course to maintain consistency and ensure your app scales easily over time.

**Comment by jayant246** [comment]
I solved it by targeting the button class which is responsible for _"focus" & "hover"_ . Thanks @halocline
