### ISSUE TITLE
Styling issues when a JSX Element (e.g., TreeView) is passed as an option to Select

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#5322]
Adding codeSandBox, https://codesandbox.io/s/dank-sea-t2onf?file=/src/App.js

In the above example when the JSX.Element is selected, the element's background is set to selected background. Do we have an option to overwrite this ?

**Comment by ShimiSun** [comment]
Here is a couple of theme settings you can try and keep us posted how it goes:
https://github.com/grommet/grommet-theme-hpe/blob/37bacaadce825fd9f1472fe855412d3252ea725a/src/js/index.js#L85
https://github.com/grommet/grommet-theme-hpe/blob/37bacaadce825fd9f1472fe855412d3252ea725a/src/js/index.js#L255

**Comment by taysea** [comment]
This seems to be related to [this PR](https://github.com/grommet/grommet/pull/5296) which added the selected styling to custom child elements. Any thoughts on this @jcfilben?

**Comment by jcfilben** [comment]
The above PR, #5296 changed Select so that custom children have the selected styling applied if the child is a string. For other types the selected styling is not applied, so I don't think it would be affecting this example. Also, if you go back to previous versions of grommet in the codesandbox example the selected styling is still being applied

**Comment by taysea** [comment]
Hey @ypinneka -- I'm looking more into the CodeSandbox you shared. The pattern of having a nested menu inside a Select option isn't a pattern we'd typically recommend because it doesn't create a great experience for keyboard navigation/screen readers.

I understand that this may be a simplified implementation from what your team has implemented in an application. Would you mind sharing a little more context on the use case/what you're implementing in the app? Maybe we can work on how to best implement in a way that supports better accessibility.

**Comment by ypinneka** [comment]
I could not share the screenshots as this is a public forum, but have sent them in chat depicting our use case.

Discussing with our team, and thinking of flattening the path, something which grommet supports. Will keep you updated !

**Comment by taysea** [comment]
I am going to close this issue since the offline discussion of flattening the path would work with current Select behavior. If needed, we can open this again in future.
