### ISSUE TITLE
Styled Anchor as Link Ignores Props

### ISSUE THREAD

**Issue by alphonso06** [grommet/grommet#5447]
Using Styled Components to style the `<Anchor />` component and then trying to use it as a Link from React Router ignores the default `<Anchor />` props.

### Expected Behavior

Props should still work as intended.

### Actual Behavior

They are ignored after being styled with Styled Components.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-styled-routed-anchor-bd2t8?file=/src/App.js

### Steps to Reproduce

Check out the sandbox for the demonstration.

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: Mozilla Firefox 89.0.2
- Operating System and version (desktop or mobile): Linux Mint 20.1 Ulyssa

**Comment by jlaluces123** [comment]
Happy Monday @alphonso06! 

I wanted to let you know that we're currently investigating the issue on why the combination of `styled(Anchor)` and `as={Link}` do not inherit the Anchor props despite inheriting the Anchor props when done separately. But as a solution for now to get you unblocked, any styling extensions needed for Anchor can be done through `anchor.extend` which I'll leave a quick example below:

```js
const myTheme = {
  anchor: {
    extend: () => `
      cursor: pointer;
    `
  }
}
```

If you want to see all available Anchor props provided, you can check them out [here](https://v2.grommet.io/anchor).

**Comment by jlaluces123** [comment]
Hey @alphonso06 ! I wanted to get back to you after diving into the issue a bit more and here is what I found. In the codesandbox example you wrote, we're wrapping a component (in this case, the `Anchor` component) inside a `styled()`. Since `Anchor` is a component that can take an `as` prop, we would actually want to use `forwardedAs` as a means to pass down the props we want. With this implemented in your codesandbox, the `StylishAnchor` is now able to use the available `Anchor` props from Grommet's end (ex. `margin`, `label`, etc.), props from `Link` (ex. `to=""`), and still retaining the stylings defined for `StylishAnchor`. You can view the example codesandbox [here](https://codesandbox.io/s/grommet-styled-routed-anchor-forked-vmroz?file=/src/App.js), and see the documentation for `forwardedAs` [here](https://styled-components.com/docs/api#forwardedas-prop).

I also wanted to leave [this discussion thread](https://github.com/styled-components/styled-components/issues/1981) that helped me learn more about `forwardedAs`. Please let me know if you run into further issues with this!

**Comment by jcfilben** [comment]
Hi @alphonso06 I'm going to go ahead and close this since @jlaluces123 provided an explanation and codesandbox above.
