### ISSUE TITLE
Unable To Make Updates To Masked Input

### ISSUE THREAD

**Issue by ggiller** [grommet/grommet#5466]
When using the Masked Input in the documentation, I am currently unable to make any updates to the input field

### Expected Behavior

When clicking into the masked input and selecting a number for hours, that number should then be added to the input field and the masked input should move on to the allowing me to select the minutes.

### Actual Behavior

The masked input is currently stuck on showing the hours dropdown and I am unable to select anything.

### URL, screen shot, or Codepen exhibiting the issue

https://v2.grommet.io/maskedinput

### Steps to Reproduce

1. Click on the masked input field
2. Try to select an hour from the dropdown that opens up
3. Notice that nothing gets selected

### Your Environment

- Grommet version: Whatever is used in the Grommet Documentation, assuming the latest, 2.17.3
- Browser Name and version: Chrome // Version 91
- Operating System and version (desktop or mobile): Desktop

**Comment by MikeKingdom** [comment]
This is because the example on that page always passes `value=""`.

This example needs to define value and onChange such that it's updated like the [storybook example](https://storybook.grommet.io/?path=/story/input-maskedinput-time--time)

Note that making it uncontrolled by removing the value (and onChange) properties doesn't quite work since the drop doesn't quite advance to the next field when you choose a value. This may be a separate issue.
