### ISSUE TITLE
Markdown italics causes linebreak

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5486]
### Expected Behavior

Italics should not cause a linebreak, should just be part of the text.

### Actual Behavior

When italics are used around some text in a sentence, it forces a line break at the end.

### URL, screen shot, or Codepen exhibiting the issue

https://designer.grommet.io/markdown-table?id=Demonstration-edgar-circenis-hpe-com

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.17.4
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS Mojave

**Comment by ecircenis** [comment]
It looks like the actual issue is with tables in markdown.  Our markdown processor is not handling markdown within table cells correctly and is inserting line breaks any time it runs across them.  This is true for hyperlinks, italics, bold text, etc.  Example markdown showing the issue:

| col1 | col2 |
| --- | --- |
| This is a sentence containing a [link]() that goes nowhere.   It is formatted incorrectly. | This is an example of *italics* in a table cell. It is formatted incorrectly. |

This is another example of  a [link](), but not inside a table. This one looks better.

And, here is an example of *italics* outside of a table.  Again, it looks correct.

**Comment by ecircenis** [comment]
Note that the GitHub markdown processor is displaying the content in the previous comment correctly.  Here's the same content in a code block so it can easily be tested in grommet:

`| col1 | col2 |
| --- | --- |
| This is a sentence containing a [link]() that goes nowhere.   It is formatted incorrectly. | This is an example of *italics* in a table cell. It is formatted incorrectly. |

This is another example of  a [link](), but not inside a table. This one looks better.

And, here is an example of *italics* outside of a table.  Again, it looks correct.`

**Comment by ecircenis** [comment]
Sigh...  Even in a code block, GitHub wants to process markdown (at least some markdown)

**Comment by MikeKingdom** [comment]
What seems to be causing this is Grommet's `Markdown` component uses its `TableCell` component for the `<td>` elements in the Markdown. `TableCell` by default uses a `Box` which is `display:flex` to wrap the cell content. For some reason, `display:flex` causes inline children like `<em>` to become `display:block`.
