### ISSUE TITLE
TextInput type=number, If we put '-' it gives required error

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#5522]
### Expected Behavior
Required error should only show up when field is empty

### Actual Behavior
Even when field is not empty required shows up under a specific usecase.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/awesome-dawn-5ycy0?file=/src/App.js

### Steps to Reproduce
1. Enter '2-' in the number field & required shows up !

### Your Environment
- Grommet version: latest
- Browser Name and version: Chrome, latest
- Operating System and version (desktop or mobile): desktop, Mac

**Comment by taysea** [comment]
I believe the "required" message is showing up because the native HTML input is set to automatically invalidate non-numberic values when type="number" is applied. Since "required" is our error text, it's triggering that validation. See MDN docs for reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#validation

Given this, I am going to look into how this string might be best customized to provide something more fitting to the user, such as "Value must contain only numbers." or something the caller can control.
