### ISSUE TITLE
Tip.dropProps styles applied to wrong element

### ISSUE THREAD

**Issue by barzto** [grommet/grommet#5574]
Styles set by `dropProps` attribute of `Tip` component are applied to wrong div (parent of content).

### Expected Behavior

`<Tip dropProps={{...}}>` works same way as `<DropButton dropProps={{...}}>` do.

### Actual Behavior

Style set by `dropProps` attribute like `background` is applied to wrong parent of content.

### URL, screen shot, or Codepen exhibiting the issue

<img width="132" alt="Tip componant sandbox example" src="https://user-images.githubusercontent.com/10025111/131923710-28ede649-8489-495c-a36f-6e76db4730f4.png">

### Steps to Reproduce

1. Open [Tip component page](https://v2.grommet.io/tip)
2. Set `dropProps={{ background: 'brand' }}` to Tip.
3. Observe the background is applied to wrong div (drop content shadow is drawn over set background)

Whole snippet for reference:

```
<Grommet theme={grommet}>
  <Box pad="medium">
    <Tip 
      dropProps={{ background: 'brand' }} 
      content={(
        <Box>
          <Text size="large">Hello</Text>
          <Text size="xsmall">World</Text>
        </Box>
      )}
    >
     <Button label="hover me" /> 
    </Tip>
  </Box>
</Grommet>
```

### Your Environment

- Grommet version: 2.17.5 (my project), reproducible in Grommet official Component sandbox (assuming there's the last varsion)
- Browser Name and version: Firefox 91.0.2 and Chrome 91.0.4472.114
- Operating System and version (desktop or mobile): OS X 10.15.6

**Comment by jcfilben** [comment]
Hi @barzto the dropProps are being correclty applied to the Drop as shown in the code below. The reason you are seeing the rounded box within the drop is because of the default styling coming from Tip. To get rid of this styling add the `plain` prop to Tip.

<img width="483" alt="Screen Shot 2021-09-03 at 1 40 24 PM" src="https://user-images.githubusercontent.com/54560994/132058172-2cff2e06-64da-4a47-8805-f633120fcc19.png">

Let me know if this helps solve the problem or if you have more questions

**Comment by barzto** [comment]
Thank you @jcfilben for quick response. Let me sum up my problem to this question:

What is minimal code to change (just) content area background of a single Tip instance while preserving the rest of styling (like elevation, round borders, etc.)?

If I get your point right, it should be something like this (styles in dropProps)

```javascript
<Grommet theme={grommet}>
  <Box pad="medium">
    <Tip 
      content="tip content"
      plain
      dropProps={{ 
        background: 'brand', 
        pad: 'small', 
        round: 'small', 
        elevation: 'small' 
      }} 
    >
     <Button label="hover me" /> 
    </Tip>
  </Box>
</Grommet>
```

or like this (styles in content Box)

```javascript
<Grommet theme={grommet}>
  <Box pad="medium">
    <Tip 
      content={
        <Box
          background="brand" 
          pad="small" 
          round="small" 
          elevation="small"
        >
          tip content
        </Box>
      }
      plain
    >
     <Button label="hover me" /> 
    </Tip>
  </Box>
</Grommet>
```

In both cases the elevation style is not applied (so still not working for me).

My confusion comes from the fact that doing the same thing (changing single instance content background or round corners) for DropButton works simply by setting `<DropButton dropProps={{ background: 'brand' }} ...` which makes me belive this should be the same case for Tip.

Anyway thank you for point to `plain` attribute, this almost fixes my problem (besides the not working elevation).

**Comment by jcfilben** [comment]
I believe in dropProps elevation doesn't apply when plain=true. However, I was able to get the elevation to work in the second example. The key is making sure you have some padding around the element so the elevation has room to show up. Here is a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-ljnq8?file=/index.js) showing examples. The first one doesn't work because it is setting elevation through dropProps with the plain prop applied. The second and third options show elevation working

**Comment by barzto** [comment]
Ah, that was that bit i missed: I have to set box margin to have elavation effect visibile.

Thank you very much, that resolved my issue! Let me close it.
