### ISSUE TITLE
TextInput loses caret position inside Tab controls

### ISSUE THREAD

**Issue by MLRichmond** [grommet/grommet#5682]
### Expected Behavior

If you move the caret to the center of a text string and type, the caret should remain at the position of the data entry.

### Actual Behavior

If you move the caret to the center of a text string and type, the new character is inserted correctly but the caret jumps to the end of the string.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-zssn2?file=/index.js

### Steps to Reproduce

1.  Enter text in a textInput that is inside a Tab control
2. Move the caret to the middle of the string
3. Enter additional characters

### Your Environment
- Grommet version: 2.18
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Desktop

**Comment by MLRichmond** [comment]
@jcfilben I've updated the code sandbox and believe I've found the difference. My solution uses a "theme" in the Grommet object.

https://codesandbox.io/s/grommet-v2-template-forked-zssn2?file=/index.js

**Comment by jcfilben** [comment]
Thanks for helping narrow down the issue! Looks like it is happing even with an empty theme.

**Comment by MikeKingdom** [comment]
@MLRichmond , @jcfilben 
This is basically happening because the `theme` object being passed in is technically a different object each render, causing the entire text input to get recreated in the DOM (losing any state not passed in.)

You can avoid this by either declaring the theme object outside the overall app component so it doesn't get re-created when something re-renders or use `useMemo` to memoize it.

**Comment by jcfilben** [comment]
Closing since a solution was provided above
