### ISSUE TITLE
Using JSX Element with Select component in value prop is distorting the height of Select element.

### ISSUE THREAD

**Issue by dipesh-sakharkar** [grommet/grommet#5835]
While using JSX element in Select component in value prop 
1. Height for Select element is distorting.
2. Placeholder is not showing.
3. After selecting the value, padding is missing.

Below is the sandbox link for the issue
https://codesandbox.io/s/hungry-dubinsky-lqc4r?file=/src/App.js

**Comment by jcfilben** [comment]
When displaying a JSX element within the Select Grommet doesn't add any additional padding. This allows the user more flexibility with displaying custom JSX. If you want padding you can add it in (see this [codesandbox](https://codesandbox.io/s/interesting-taussig-f94iy?file=/src/App.js) example). The placeholder is not showing because you are initially setting the value to "". The placeholder will only show when there is no value set.

**Comment by jcfilben** [comment]
Hi @dipesh-sakharkar I am going to go ahead and close this issue since an explanation & codesandbox was provided above. Feel free to reopen if you have more questions.
