### ISSUE TITLE
Select -- passing in a function to `labelKey` doesn't render the selected option

### ISSUE THREAD

**Issue by ruicaridade** [grommet/grommet#5904]
### Expected Behavior

A function in `labelKey` should render the options inside the dropdown AND the currently selected option. 

### Actual Behavior

As it stands, the `labelKey` works for the options in the dropdown, but in the selected option in prints out the `value` instead.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-bqyfr

### Steps to Reproduce

1. Create a Select component with a couple options.
2. Pass in a function to `labelKey`, for example: `labelKey={(option) => <Text color="red">{option}</Text>}`.

### Your Environment

- Grommet version: 2.20.0
- Browser Name and version: Tested on both Edge 97 and Firefox 97.
- Operating System and version (desktop or mobile): Windows 11

**Comment by ericsoderberghp** [comment]
`valueKey` and `valueLabel` are both available for custom rendering of the Select value. Would these be sufficient?
https://v2.grommet.io/select#valueLabel

**Comment by ruicaridade** [comment]
> `valueKey` and `valueLabel` are both available for custom rendering of the Select value. Would these be sufficient? https://v2.grommet.io/select#valueLabel

Apologies if I'm misunderstanding, but `valueLabel` seems to expect a node rather than a function? I'm looking to render options, like in the screenshot below. The options inside the dropdown are formatted, but the selected option isn't.

![image](https://user-images.githubusercontent.com/8092874/150174506-f67f6761-8e64-4f79-8873-42985c63e219.png)

**Comment by ericsoderberghp** [comment]
The `valueLabel` returns a node.

**Comment by ericsoderberghp** [comment]
Do you have a reference to the selected value, perhaps via `onChange`, that you can use via something like:
```
const [value, setValue] = useState();
...
<Select value={value} valueLabel={<Text color="red">{value}</Text>} ... />
...
```

**Comment by ruicaridade** [comment]
I suppose that's one way to do it, cheers. I'm just wondering if this is the intended way to do it? The docs make it sound like `labelKey` should also render the selected option.

**Comment by ericsoderberghp** [comment]
gotcha, we'll take a look

**Comment by Barnyclark** [comment]
It looks like there are a few issues here:
- If `labelKey` returns a react node then `inputValue` is a node, not a string. This is passed directly to the value prop of `<SelectTextInput>` (https://github.com/grommet/grommet/blob/8f390ff17e877da55de26f83931f1a7cf2db2f97/src/js/components/Select/Select.js#L386) but the value prop only accepts a `string` or a `number`. This causes a number of console errors as well as the rendering issues mentioned above.
- If `valueLabel` is defined, then `inputValue` is undefined and this is passed to the `<HiddenInput>` - (https://github.com/grommet/grommet/blob/8f390ff17e877da55de26f83931f1a7cf2db2f97/src/js/components/Select/Select.js#L356) - I think this makes the hidden input redundant.
- There are also some issues with the typings for `labelKey`. It is typed as: `string | ((...args: any[]) => any)` but it should probably only return a string or a number.

I am not sure what the intention is here because if `labelKey` returns a node for formating the options, that node can't be passed to `TextInput`. You would need to change the way the selected value is rendered and not use a `TextInput` - similar to what happens when you use `valueLabel`. In which case `labelKey` should only return a node if `valueLabel` is also specified. In that scenario it would also be helpful if `valueLabel` was a function that received the selected value as a prop - otherwise, you need to store the value outside the component and pass it back in as suggested above.
