### ISSUE TITLE
DateInput does not automatically drop down when input is entered; (behavior changed after 2.18.0)

### ISSUE THREAD

**Issue by sbytnar** [grommet/grommet#5907]
### Expected Behavior

          <DateInput format="yyyy-mm-dd" value={value} onChange={onChange} />

v2.18.0: As you enter input, the drop down calendar is shown.

Documentation: "inline": Whether the calendar should always be shown or via a Drop when interacting with the input. default: false.

### Actual Behavior

v2.19.0: As you enter input, the drop down calendar is not shown. (Just a note: The drop down calendar can't be pulled down by clicking the icon.)
v2.20.0:  As you enter input, the drop down calendar is not shown. (Just a note: The drop down calendar can be pulled down by clicking the icon. Glad to see that was fixed.)

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-74ml3?file=/index.js
Derive & choose v2.18 and v2.19 to see the difference.

### Steps to Reproduce

Click in date input field.
   This is the point where v2.18 and 2.19 diverge.
The calendar drops down.
The input changes to navigation in the calendar. (Which, by the way, is annoying if your intent was to type the date input, but right now I'm just talking about consistent behavior of the widget between versions. I'm not going to argue UX on this, but please take a second to think about it.)
Click again in the text box.
Start typing.

### Your Environment

- Grommet version: 2.18.0 works. 2.19.0 doesn't behave the same.
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Desktop Windows 10.

**Comment by LucasNeevs** [comment]
Good morning.

We're using Grommet in our platform (a courses platform based on Microsoft contents and associations) and we're having the same problem here. 

When someone clicks on DateInput and select a date, the event capture the date correctly but the calendar doesn't close automatically (being more specific, when we click on some date, the input closes and automatically reopens) and this is a problem for us, because the DateIput drop down cover other contents.

If someone clicks outside, the dropdown closes. But this is not the correct way for this, I think. Because, if we look here on Grommet DateInput story files, using for example, the European input (https://storybook.grommet.io/?path=/story/input-dateinput-european--european), if I click on some date, the input closes automatically. So, we cannot understand why doesn't work for us...

We've tried to reproduce this on Edge, on Chrome and Firefox. And the same problem persists on all.

Someone can help us?

![fail calendar](https://user-images.githubusercontent.com/52714448/150985345-f88bed48-6694-4bf6-947f-35f3fa4f0297.png)

**Comment by jcfilben** [comment]
Hi @sbytnar DateInput has been going through a few changes lately which causes some different behavior between versions. But I think with v2.20.0 we have achieved the behavior we want as far as opening and closing the drop. The DateInput doesn't open when you type a date but it will open when you click the calendar icon and then stay open until you click outside the DateInput, select a date, or click the calendar icon.

@LucasNeevs Can you try updating to the latest version of Grommet? After upgrading you should see the same behavior of DateInput that is shown in the storybook examples

**Comment by LucasNeevs** [comment]
Hi @jcfilben ! Your tip worked great for us. I've updated to 2.20.0 version and tried to open the calendar and when I select some date, the calendar closes automatically, exactly how we need. Thank you so much!

**Comment by sbytnar** [comment]
Thanks @jcfilben for the explanation on the behavior. I'll close this out because it looks like this is the expected behavior moving forward and 2.20.0 operates as @LucasNeevs expects.
