### ISSUE TITLE
Respect CLI parameters

### ISSUE THREAD

**Issue by goloroden** [grommet/grommet#594]
I have just started looking at grommet, and the very first contact already showed up some unwanted behavior. It would be very nice if the described behavior could be changed, as it

- comes quite surprisingly,
- leaves you with a state that is not *that* easy to get rid off again.

### Steps to reproduce

- `npm install -g gulp grommet`
- `mkdir ~/foo`
- `cd ~/foo`
- `grommet init --help`

### Expected result

- `grommet init` shows a help screen describing which options I may use.

### Actual result

- `grommet init` actually initializes an application in the directory `~/foo/--help`

**Comment by alansouzati** [comment]
Thanks for your feedback, this is terrible. I know how much `--help` is important in any CLI tool. 

We are in the process of creating `grommet-cli` as a separate project that you would install globally, instead of using grommet core for that. 

Right now, the init is as simple as a sample app, we are planning to enhance the CLI with other apps that are currently available in the Grommet showcase, but not as configurable as one would expect.

I'm sorry you are facing this issue and I will take that into account when designing/developing the new CLI tool.

**Comment by bryanjacquot** [comment]
Will address as part of issue #664.
