### ISSUE TITLE
DataTable Header cell hover indicator doesn't fill full cell height

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5968]
### Expected Behavior

The clickable and hover indicated region of a header cell should always be the full height of the row. So, if there are some header cells with single line text and others that wrap to multiple lines, the clickable and hover indicator should take up the height of the tallest cell.

### Actual Behavior

When you resize your window, causing text in header cells to wrap, the header cells whose text remains as a single line does not take up the full height of the cell. Then, when you hover on them, the hoverindicator isn't filling the whole cell.

### URL, screen shot, or Codepen exhibiting the issue

https://design-system.hpe.design/components/datatable#sorting

![Screen_Recording_2022-02-25_at_3_24_54_PM_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/12522275/155816853-d921db62-fbb4-4a2e-b7e1-521891bfd733.gif)

### Steps to Reproduce

1. Open the table in the link above ^^ so that the table header cells all render in a single line.
2. Hover over the cells (note how they take full height)
3. Shrink your window width until some of the cells wrap to two lines
4. hover over the header cells (note how the single line header cells do not take full height)

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Chrome 98
- Operating System and version (desktop or mobile): MacOS Monterey

**Comment by MikeKingdom** [comment]
Each of the `<Box>` components which contain the header labels get styled with `height: 100%`, and they are block components (`display: flex`) but because the `<table>` is `height: auto` the `height:100%` is ignored.

The heading labels correctly fill the heading cell in DataTables which are set to `fill` or have a specific height set. You can see an example of this in the first **Storage Pools** table in that page since it has `fill` set.

I'm not sure of a reasonable way to fix this since a container parent of the heading needs to have a defined height. Specifically setting a height for the header cells or row would be difficult to manage on resize, etc as would setting `position: absolute` for the heading contents.
