### ISSUE TITLE
DateInput submits wrong date

### ISSUE THREAD

**Issue by jonka5** [grommet/grommet#5989]
### Expected Behavior

The selected date should be set into the state.

### Actual Behavior

OnChange sets the day before into the state.

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/74107477/157843558-bb686ce9-ba1e-4b1d-9857-3e77361dcf66.mov

Bug occurred in UTC+1 in the storybook. (grommet 2.21.0?)

### Steps to Reproduce

Try the storybook example from UTC+1 like in the video

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: chrome latest

**Comment by ericsoderberghp** [comment]
So, I watched the video, and it appears that you select "March 1 2022" and then the value is set to "01/03/2022", which is the correct syntax for that date in regions where the day of the month comes first, european style. What were you expecting the value to look like?

**Comment by jcfilben** [comment]
@ericsoderberghp At the bottom left of the video the console is logging the incorrect date "22-2-28" instead of "22-3-1"

**Comment by ericsoderberghp** [comment]
I think this has been fixed on the #stable branch and will be available in the next release. The fix went in on February 24 and the 2.21.0 release occurred on February 23.

**Comment by jcfilben** [comment]
When you are in a UTC+ timezone the value logged is a day before the value selected because the same date and time at UTC 0 would be behind a UTC+ timezone.

Say for example you are in UTC+1 with the date March 1st 2022. Written in iso format this would be "2022-02-28T23:00:00.000Z" or February 28th 2022 with a time of 23 hours. The timezone UTC+1 means we are an hour ahead of UTC 0. When we add an hour to our iso time ("2022-02-28T23:00:00.000Z") we get "2022-03-01T00:00:00.000Z" or March 1st 2022, the date we selected.

To help clarify this I have filed a pull request that modifies the DateInput and Calendar stories that have log statements to log both the ISO ("2022-02-28T23:00:00.000Z") and UTC ("Tue Mar 01 2022 00:00:00 GMT+0100 (Central European Standard Time)") format of a date when it is selected.

**Comment by jcfilben** [comment]
> I'm still seeing this as an issue as well from the current 2.21.0 release. Interestingly the date works fine if I pick a date after DST change in the US - March 14 onwards. But if I pick a date prior like Jan 1-Jan15 2022 it jumps to the previous day.

This is a separate issue related to Daylight Savings, here is the associated pull request: https://github.com/grommet/grommet/pull/5997
