### ISSUE TITLE
Search select doesn't work on quick typing

### ISSUE THREAD

**Issue by djbarnwal** [grommet/grommet#6007]
### Expected Behavior

Select Search should show that value which is being typed by the user in the input box

### Actual Behavior

When quickly typed, the input box looses focus and a letter (sometimes two letters) gets skipped. This only happens when there is already an option selected

### URL, screen shot, or Codepen exhibiting the issue

When no option is selected. Typing the keyword 'india' shows the same value in the input box.
When some option from the list is selected, typing 'india' very quickly only shows 'idia' in the input box

![grommet_search_select_issue](https://user-images.githubusercontent.com/4402679/159293918-70523277-1110-47bf-99f1-93878e46c992.gif)

Looks like when the keyword being typed gets matched to any value in the option list (here 'i' matching to option 1, option 2...), the list is re-rendered with new set of options. During that change, the input field looses focus and regains is back after a small delay.

### Steps to Reproduce

1. Got to [search-select story](https://storybook.grommet.io/?path=/story/input-select-search--search)
2. Select any option
3. Type the keyword 'india' very quickly

The same is reproducible in a local project using the `Select` component with similar configuration.

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Tested on Firefox 98.0.1 and Chrome 99.0.4844.74
- Operating System and version (desktop or mobile): macOS Big Sur 11.2.1

**Comment by B-Esmaili** [comment]
I investigated the issue , the problem is in following line :
https://github.com/grommet/grommet/blob/40f7d2007d7bb1d5ffaea06bac3f324311dd0f45/src/js/components/Select/SelectContainer.js#L99
In this line focus is set to first selected item then in following like :
https://github.com/grommet/grommet/blob/40f7d2007d7bb1d5ffaea06bac3f324311dd0f45/src/js/components/Select/SelectContainer.js#L112
focus is set back to search input but with some delay. This is why earlier typed characters are omitted.
