### ISSUE TITLE
Pagination is making page prop as undefined when we do an action that removes all the items the last page

### ISSUE THREAD

**Issue by mahanthi-arun-kumar** [grommet/grommet#6010]
### Expected Behavior

When we do an action that removes all the items on the last page, the pagination component should fall back to the previous page! For example, if the total number of items is 12, items per page 5 then there will be 3 pages (5,5,2 items on page1,page2,page3 respectively). If I remove 2 items from the last page i.e page3, it should fall back to page2! 

### Actual Behavior
 But what's happening now is If I remove 2 items from the last page i.e page3, Pagination is making page prop _undefined_ due to which the **UI is broken**!

### Steps to Reproduce

1. Add pagination to a grommet data table
2. Give the total number of items as 12
3. Give the number of items per page as 5
4. Go to the last page i.e page3 in this example 
5. Delete all the items on page3
6. Then grommet pagination will return page prop as _undefined_  which causes the breaking of UI

### Your Environment

- Grommet version:2.18.0
- Browser Name and version: Version 99.0.4844.51 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): desktop

**Comment by jcfilben** [comment]
Hi @mahanthi-arun-kumar it looks like this issue has been fixed since v2.19.0 of Grommet. Pull request https://github.com/grommet/grommet/pull/5683 solved this issue.

You can also see in this [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-6gx0gq?file=/index.js) the issue is present if you switch grommet to 2.18.0 and if you switch Grommet to 2.19.0 or above the issue is resolved.

**Comment by mahanthi-arun-kumar** [comment]
THANKS @ericsoderberghp  @jcfilben
