### ISSUE TITLE
Calendar datetime selection issues.

### ISSUE THREAD

**Issue by novykh** [grommet/grommet#6023]
`Calendar` and `DateInput` do not handle timestamps correctly.
It looks like the suspected line is [this](https://github.com/grommet/grommet/blob/78eddaa4c8b064c49aa63581d1e169403c14699a/src/js/components/Calendar/utils.js#L189).

### Expected Behavior

1. Passing a date value `yyyy-MM-dd` should show the correct date on calendar.
2. Passing a datetime value `yyyy-MM-dd'T'HH:mm:ss.SSSxxx` should show the correct date on calendar based on the offset (timezone).
3. Selecting a date on Calendar `yyyy-MM-dd'T'HH:mm:ss.SSSxxx` should return the selected/correct datetime.

### Actual Behavior

1. Calendar shows the previous date as selected.
2. Calendar shows the previous or next date as selected when ISO datetime is before midnight or after midnight depending on timezone and time passed.
3. Returns the next day as selected, when the datetime passed as initial value is end of day.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/visualizations-calendar-simple--simple&globals=theme:base

### Steps to Reproduce

Selecting on the bottom calendar (of the above story link), it sets the value selected to the top calendar, you can see it shows the previous day as selected.

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Not relevant
- Operating System and version (desktop or mobile): Not relevant

**Comment by jcfilben** [comment]
Hi @novykh I believe this recent pull request https://github.com/grommet/grommet/pull/5997 should have fixed this issue. Note this fix hasn't been released yet but is available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F). If you are still experiencing the issue can you share what timezone you are seeing it in?

**Comment by novykh** [comment]
Hey @jcfilben thanks for the quick reply. Indeed I tried with the stable branch and looks good in most of the cases. The only issue I see has to do with daylight savings.
I'm on `GMT+0200 (Eastern European Standard Time)` and have a datetime selection `2022-04-01T00:00:00.000` that it will be with `+0300`. In this case I get the previous day as selected in calendar.

**Comment by novykh** [comment]
My 2 cents on this is that the calendar is tested with `-` offsets/timezones, thus:
```
valueOffset = hourDelta === 0 ? 0 : hourDelta * 60 * 60 * 1000;
localOffset = new Date().getTimezoneOffset() * 60 * 1000;
return new Date(new Date(v).getTime() - valueOffset + localOffset).toISOString();
```
works. But the logic is different for the `+` offsets/timezones:
```
valueOffset = hourDelta === 0 ? 0 : (24 - hourDelta) * 60 * 60 * 1000;
localOffset = new Date().getTimezoneOffset() * 60 * 1000;
return new Date(new Date(v).getTime() + valueOffset - localOffset).toISOString();
```

**Comment by jcfilben** [comment]
The reason the first calendar is showing a day before the date selects is that in GMT + timezones when the date is written in iso format it is behind what the actual date would be since a GMT + timezone is ahead of GMT 0.

Say for example you are in UTC+1 with the date March 1st 2022. Written in iso format this would be "2022-02-28T23:00:00.000Z" or February 28th 2022 with a time of 23 hours. The timezone UTC+1 means we are an hour ahead of UTC 0. When we add an hour to our iso time ("2022-02-28T23:00:00.000Z") we get "2022-03-01T00:00:00.000Z" or March 1st 2022, the date we selected.

So the second calendar (where we selected the date) knows that we selected March 1st 2022 and we are in UTC+1 timezone. The actual date that it stores is in iso format ("2022-02-28T23:00:00.000Z"). This is what is passed through the date variable to the first calendar. The first calendar sees that it was given a date with a timestamp. It takes this date and displays it as is assuming that we are telling it that the date we want is February 28th with a time of 22 hours in the local timezone (GMT +2).

I think this behavior makes sense. If we pass a date with a timezone to a calendar we would expect it to show that date and time in our local timezone. I get how when viewing the story this is confusing and it seems like it should show the same date on both calendars. I am wondering if we should change the story so that it is not causing confusion.

If we were to change utc+ timezones to use this logic: `valueOffset = hourDelta === 0 ? 0 : (24 - hourDelta) * 60 * 60 * 1000;` this would cause the iso date to be ("2022-03-01T23:00:00.000Z") when we select March 1st 2022 and then when we translate this into a utc date we would actually get March 2nd 2022.
