### ISSUE TITLE
Provide a way to style select dropdown option text

### ISSUE THREAD

**Issue by nxp2910** [grommet/grommet#6126]
**Problem**
When using Select component, dropdown options are rendered under Button components. If a custom theme is created with global button styles, the options in the Select component inherit those global button styles. Further, the font size of the dropdown options seem to be always 18px, and I haven't found a way to override it yet.

You can see this behavior below:
[https://codesandbox.io/s/bold-poincare-118f9k?file=/src/App.js](https://codesandbox.io/s/bold-poincare-118f9k?file=/src/App.js)

**Expected Behavior**
Users should be able to create a theme that can target options in a Select component.

An ideal way to allow this would be to add ability to theme the Select as following:

`select: {
    options: {
      text: {
        margin: "0px",
        fontsize: "10px",
        textTransform: "none"
      }
    }
  }`

**Comment by jcfilben** [comment]
Hi @nxp2910 I think I see the source of confusion... you are trying to pass css props to `select.options.text`.  `select.options.text` can be passed any [Text props](https://v2.grommet.io/text) that the grommet Text component accepts, so to change the size of the font the `size` prop should be used instead of the css prop `fontsize`. Here is a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-tjwz1y?file=/index.js) showing how to adjust the size of the text for the select options.

Let us know if you think the wording in the docs for `select.options.text` should be adjusted or if we can do anything to make this a little clearer.

**Comment by jcfilben** [comment]
Closing, I think the above solution solves this issue. Feel free to comment with any suggestions of how we can make the docs clearer to avoid confusion on this.
