### ISSUE TITLE
MaskInput clearing the whole value when entering some invalid data like below

### ISSUE THREAD

**Issue by venkatesh-elchuri** [grommet/grommet#6151]
### Expected Behavior
Mask Input should not clear the whole input value, 
My scenario 

1. I would like to allow only numbers in the input  by passing regex in mas options.
2. Entered number like 123
3. After I came to initial position and entered some spl characters like +,_,),( , Then the whole input value becomes empty .
4. Actually it should be display +123 or _123 like that , if need some invalid entry message. 

### Actual Behavior
If it was a invalid we can show the invalid entry message , But clearing whole value making consumer confuse.

### URL, screen shot, or Codepen exhibiting the issue
![CPT2205261449-942x517](https://user-images.githubusercontent.com/30321668/170458736-2ddda2b5-bf90-4b7e-8fe5-f0b7fb0a53e0.gif)

https://codesandbox.io/s/grommet-text-input-forked-rp8u8p?file=/src/App.js:173-193

In example , I entered 123, After that i came to initial position and tried to enter  "+", Then it become empty

**Is This expected behavior ?**

- Grommet version: Latest
- Browser Name and version: Chrome Latest
- Operating System and version (desktop or mobile): desktop

**Comment by venkatesh-elchuri** [comment]
@ericsoderberghp Can you please look into it ?

**Comment by ericsoderberghp** [comment]
The issue is arising because the component in `parseValue()` gives up as soon as it encounters something that doesn't match the mask. Trying to think about how to more gracefully handle situations like this. Another scenario to consider is entering "12" and then attempting to add a "." between the "1" and "2". Currently, this causes the value to change to "1 ".
