### ISSUE TITLE
Disabled items should not be re-orderable in the List Component

### ISSUE THREAD

**Issue by jeffcap1** [grommet/grommet#6229]
### Expected Behavior

When a List component is provided both an onOrder function and an array of disabled itemKey's the disabled items should not be re-orderable.

### Actual Behavior

The disabled items are still able to be re-ordered through both Drag 'n Drop as well as clicking the up/down arrow to re-order the item.

### URL, screen shot, or Codepen exhibiting the issue

Codepen example: [https://codesandbox.io/s/grommet-v2-template-forked-82ogqc](https://codesandbox.io/s/grommet-v2-template-forked-82ogqc)

### Steps to Reproduce

1. Create a list component with an onOrder function
2. Create an array of itemKeys to disable
3. The list will appear and be re-orderable with some items disabled
4. Click the up/down arrow on any disabled item or Drag 'n Drop a disabled item and the list will be re-ordered.

### Your Environment

- React version: 17.0.2
- Grommet version: 2.25.0
- Browser Name and version: Microsoft Edge 103.0.1264.51
- Operating System and version (desktop or mobile): macOS 12.4 (Desktop)

**Comment by jcfilben** [comment]
I'm thinking that disabled items could still be re-ordered but we could allow for a way to 'pin' items so that they couldn't be re-ordered in the list regardless of the item being disabled or not. One aspect of this that I am not sure about is if we should make all the pinned items appear at the top of the list? Otherwise if we have a pinned item in the middle of the list and the other items around it can be re-ordered, the pinned item could end up anywhere in the list based on the re-odering of the other items around it.

**Comment by ericsoderberghp** [comment]
Thanks for the detailed ideas! Do you have a real world example that would help us understand the usage better? What does your list contain and what does pinning an item signify?

**Comment by jeffcap1** [comment]
@ericsoderberghp, yea I would definitely be interested in contributing this change to the project.

**Comment by ericsoderberghp** [comment]
Great! Here's a place to get started: https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md
Let us know if you have any questions :)

**Comment by jcfilben** [comment]
Marking this as closed since #6249 has been merged. @jeffcap1 Thanks for contributing to Grommet!
