### ISSUE TITLE
Meter type="circle" doesn't always render all values

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6287]
### Expected Behavior

Meter type="circle" should render all data points. Functionality was fine in `v2.24.0` but broken in `v2.25.0`.

### Actual Behavior

Circle meter doesn't render all the data points and instead only renders the last one. 

### URL, screen shot, or Codepen exhibiting the issue

Code
```
 <Meter
        type="circle"
        values={[
          { value: 904436, color: "graph-0" },

          { value: 692866, color: "graph-1" },

          { value: 642068, color: "graph-2" },

          { value: 512772, color: "graph-3" },

          { value: 5032870, color: "graph-4" }
        ]}
        aria-label="meter"
        size="small"
        thickness="small"
      />
```

CodeSandbox (v2.24.0, working):
<img width="1340" alt="Screen Shot 2022-08-19 at 4 04 20 PM" src="https://user-images.githubusercontent.com/12522275/185717674-3dc909f9-fa60-498d-9154-5338a2fa7e99.png">

Stable:
<img width="1354" alt="Screen Shot 2022-08-19 at 4 03 04 PM" src="https://user-images.githubusercontent.com/12522275/185717602-ca4b7f4f-1668-4d24-beb2-1d94fc915a99.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Mac Chrome
- Operating System and version (desktop or mobile):

**Comment by MikeKingdom** [comment]
This was caused by https://github.com/grommet/grommet/commit/9de09e47dd0f912b76c7f2308ef71b3b0408a639
![image](https://user-images.githubusercontent.com/12054362/186022392-132c7550-9657-4fa1-86bb-9ad5ff43c4cc.png)
Basically if the data values add up to something near or larger than the scaling factor (10000) Then then `anglePer` comes out to 0. We can probably make this a little more scalable by dynamically calculating the scaling factor based on `max`. In this example, a scaling factor of 1000000000 works (and is still safely below Number.MAX_SAFE_INTEGER)
