### ISSUE TITLE
"Clear" option limits options in "Select" component.

### ISSUE THREAD

**Issue by smiksiukhpe** [grommet/grommet#6304]
When clear option is not undefined user cannot see all options in Select dropdown.

### Expected Behavior

User should see all options in dropdown whenever clear is "true", "false", {position: "top"}, etc.

### Actual Behavior

When "clear" is enabled user can see only first several options.
![image](https://user-images.githubusercontent.com/81712383/187257319-e89bdb97-462c-4cc8-ad40-3ac66793a776.png)
![image](https://user-images.githubusercontent.com/81712383/187257367-4ae820a9-f85e-4e46-b424-521611a1e292.png)

### Steps to Reproduce

Create Select dropdown with many options (more than 100) and make "clear={{position: 'top}}"

### Your Environment

- Grommet version: 2.17.5
- Browser Name and version: Chrome Version 104.0.5112.101 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): MacOS Big Sur 11.6.7

**Comment by jcfilben** [comment]
Hi @smiksiukhpe I believe this issue was fixed in this pull request: https://github.com/grommet/grommet/pull/6285. The fix is available currently on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be included in the next release of grommet

**Comment by jcfilben** [comment]
Closing, a fix for this is included in v2.25.2 of Grommet
