### ISSUE TITLE
Scroll Position Getting Reset On Hover with DropButton 

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#6334]
https://user-images.githubusercontent.com/60210530/190706941-6ddc8eaf-36d6-4d0f-bc66-f5e95815e67f.mov

When we want specific styles on a row in drop content, we monitor it using useState. When we update the background color for a row based on hover, the component re-renders (as bg color changes) & the scroll position gets reset.

Attached a recording where I reproduced the issue.

We could apply styles via pseudo class `:hover` but as per our UX requirement we have complex states to maintain which can only be handled using useState & its related hooks.
eg., 
`
    const chooseBackground = () => {
      if (item.selected && !newOptionSelected && !item.disabled) {
        return internalColors.lightSlate;
      }
      if (selected === index && hover) {
        return internalColors.solitude;
      }
      if (activeIndex === index || (item.active && activeIndex === -1)) {
        return internalColors.lightSlate;
      }
      return 'none';
    };
`

**Comment by jcfilben** [comment]
Hi @ypinneka thanks for reporting this, can you share the link to the codesandbox you created?

**Comment by ypinneka** [comment]
https://codesandbox.io/s/busy-euclid-qzfnej?file=/src/DropButton.js

**Comment by jcfilben** [comment]
Thanks for sharing the codesandbox. In react whenever you have a `useState` hook, changing the state will cause a re-render. So the best solution would be to handle styling within the css, in the issue I see you mentioned needing to handle hovering with useState. Obviously I don't know the context of your application but I would look into this and see if there are any alternatives to this. As a last resort you could try to capture the scroll position of the drop before the state change and reset to that scroll position once the component re-renders, but not something I would recommend doing.

**Comment by ypinneka** [comment]
Hi @jcfilben ,
We have a specific design which cannot be plainly written in css over styled comps. We have a specific background color to maintain on hover & when not in focus the previously hovered element has a different background color. 

https://user-images.githubusercontent.com/60210530/191788111-15e00e65-5bd8-435a-958e-3c3cc3979762.mov


The ask is to check if it's possible to expose a styling prop for this sort of a requirement ? Managing the scroll state or going via useRef etc will not be a viable solution.

**Comment by jcfilben** [comment]
I'm going to add this to our backlog so we can look into this a bit more

**Comment by Isaac-alencar** [comment]
Hi, @jcfilben still need to fix this? I can take this one

**Comment by jcfilben** [comment]
Hey @Isaac-alencar this issue does still need fixed, feel free to work on this!

**Comment by jcfilben** [comment]
@Isaac-alencar Hey! just wanted to check in on this issue and see if this is something you are still interested in working on or if you had any questions

**Comment by Isaac-alencar** [comment]
Yup, I was just finishing a issue on `FileInput` haha, now I'll grab to this one!

**Comment by Isaac-alencar** [comment]
I was trying to reproduce the error and I don't think it is necessary to do some changes on code, because the component is behaving  as expect. 
The problem is: @ypinneka is passing a component with a lifted up state. 
quoting @jcfilben:
>_In react whenever you have a useState hook, changing the state will cause a re-render._

In this case, you are handling the state of a component by it's parent, so when you update you update the state here:
```jsx
// component passed in dropContent prop
 <Box
    onMouseOver={() => setHover(true)}
    onMouseLeave={() => setHover(false)}
    justify="between"
    align="center"
 >
          // ....
```
since the parent element it is holding the variable `hover` your entire component will render. 
So my suggestion is create a separated component with his own state and handle your desired behavior with css. Also, if you take a look on [storybooks file ](https://github.com/grommet/grommet/blob/master/src/js/components/DropButton/stories/Simple.js#L41) you gonna see that we create a component outside and then pass it to `dropContent`

cc: @jcfilben wdyt?

**Comment by jcfilben** [comment]
@Isaac-alencar Good notes here, thanks for looking into this! I agree I think he ideal solution is to use css, that would take out a lot of the complexity. However, I think it could be argued that since when we have a regular Drop we can scroll through and the state changes, our scroll position remains (see [this codesandbox example](https://codesandbox.io/s/quizzical-tom-fd7p0e?file=/src/DropButton.js)) DropButton should behave similarly. So maybe this is something we are missing that we could be doing differently in DropButton to allow us to preserve the scroll position.

@ypinneka a quick workaround could be to use `Button` and `Drop` instead of `DropButton` as demonstrated in the codesandbox above.

**Comment by Isaac-alencar** [comment]
@jcfilben I found this on our codebase. I switch the value passed on `place` to `true` we can avoid these bug

![image](https://user-images.githubusercontent.com/58452911/200042612-94a85b04-b608-4986-92e9-ee81d761282c.png)
However, I have a concern about this change:
- `<DropContainer />` it is being used in many other places, I can't measure if it will broke other components

Also, this value `true` is a boolean related to a variable `preserveHeight`, can we specify this as a prop and let users define if they want to? (but assuming true, as default)

FYI: this is what `preserveHeight` does:
```js
    // We try to preserve the maxHeight as changing it causes any scroll
    // position to be lost. We set the maxHeight on mount and if the window
    // is resized.
```

**Comment by jcfilben** [comment]
Nice investigation here, I agree we should be cautious with changing this to true since as you mentioned it has the potential to affect other areas that we aren't anticipating. I'll take a closer look into this

**Comment by jcfilben** [comment]
Above the `place function there is a comment that makes me think that place should only be called onMount and when the window is resized. If you add a console.log within place you can see that with DropButton it is getting called more frequently. If we can ensure that the function is really only called onMount and onResize then I think that will solve our problem. Another potential route is calling `place(true)` only when using Drop within a DropButton. However the first option seems to better align with the original intent of the code and may be a better solution.

**Comment by Isaac-alencar** [comment]
Hi, @jecassis do you have any clue on how to ensure that will be called only on resize and on mount? I'm a bit confuse about how to do

**Comment by jcfilben** [comment]
I would start by looking at the useEffect dependencies and determine which dependency is causing the useEffect to re-run so frequently when we use DropButton. Then it might make sense to break up the useEffect into smaller chunks to ensure that each part is being run only when it needs to be.
