### ISSUE TITLE
[IE11] The grommet table can't be scrolled, no scroll bar

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#648]
Reproduce steps:
1. login oneview global dashboard appliance 16.125.107.167 
2. Switch to dashboard page, search string "bay", press button "enter"
3. it will jump to search page, there are many rows, but the vertical scroll bar doesn't appear, it should be.
4. Switch to "Search" page, search string "bay", press button "enter"
5. there are many rows, and the vertcal scroll bar appears.
![image](https://cloud.githubusercontent.com/assets/16797825/16269619/a2f9d73c-38c5-11e6-9d08-66b5af673674.png)

**Comment by christinHP** [comment]
Chrome and firefox has no such issue.

**Comment by epilande** [comment]
@christinHP I was able to test & reproduce your issue. I don't think this is a grommet defect. It seems like the problem is how the app is handling the search submit.

When I search from the dashboard page, I get redirected to the search page. I don't see the scrollbar until I click on the search input (See attached gif below). The scrollbar also appears when clicking on the filter & question mark icon. I think it may have something to do with how the page is rendering. 

![648-scrollbar](https://cloud.githubusercontent.com/assets/3210082/16290238/746a2e40-3897-11e6-9cdc-a32d12d8a2fd.gif)

**Comment by christinHP** [comment]
@epilande Manny, you are very familiar with ovgd code, do you have some suggestion for the render to fix this issue?

**Comment by epilande** [comment]
Hi @christinHP can you confirm this issue still exists with latest grommet & OVGD code. I just tried it with latest grommet & OVGD, it seems to be working now.

**Comment by christinHP** [comment]
@epilande I also can't reproduce it in ovgd.

**Comment by christinHP** [comment]
@epilande  I can't reproduce it.
