### ISSUE TITLE
[IE 11] The grommet table row display is wrong

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#653]
Description
When view virtual id reports via IE11, the report display is wrong

Steps to Reproduce
1. Add at least two OV appliances to OVGD. Make sure there are virtual id conflict between the two appliances. (Add these two appliances: 16.125.107.81 administrator/hpvse123   16.125.107.86 administrator/hpvse123)
2. Switch to Reports, Virtual ID conflict.
3. View Reports-Virtual ID via IE11, verify that the report layout is wrong.

IE:
![image](https://cloud.githubusercontent.com/assets/16797825/16292742/cc15737a-3946-11e6-850a-60e10310a3f5.png)

Chrome and Firefox:
![image](https://cloud.githubusercontent.com/assets/16797825/16292747/d505a176-3946-11e6-9a94-257275eb6a4f.png)

**Comment by epilande** [comment]
Hi @christinHP I'm not able to reproduce this issue. Do you have a OVGD testing/staging site I could access?

**Comment by christinHP** [comment]
@epilande Manny, I have sent a mail to you manny.pilande@hpe.com
You can use the environment in this mail to reproduce the issue

**Comment by epilande** [comment]
Hi @christinHP I was able to test & debug what was causing the extra space in IE. The table is displaying correctly, the problem is the Bar SVG has a height of `100%` which is being rendered differently in IE. Setting the Bar SVG height should fix this issue. 

In `src/js/components/reports/VirtualIdValidateReports.js`
```javascript
  <Bar height="32" a={target} b={appliance} format ={format}/>
```
