### ISSUE TITLE
DropButton loses drop target location when badge changes while the menu is open

### ISSUE THREAD

**Issue by Greg117** [grommet/grommet#6539]
### Expected Behavior
When the badge state gets modified with the dropdown menu activated, the expectation is that the component stays anchored to the drop target

### Actual Behavior
When the menu is open and the badge state changes, the drop down menu gets moved to the start of the document.

### URL, screen shot, or Codepen exhibiting the issue
Here is an example.  Open the drop down menu and click on one of the items.  The item will change the badge state and the dropdown menu will be moved away from the original location.
(https://codesandbox.io/s/awesome-allen-ygcdnq?file=/src/App.js)](https://codesandbox.io/s/awesome-allen-ygcdnq?file=/src/App.js)

### Steps to Reproduce
Add a DropButton to the page with kind = 'toolbar' to match other toolbar icons
Change badge state while the dropdown is selected

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chromium 108.0.5359.71
- Operating System and version (desktop or mobile): Mac (desktop)

**Comment by JonasTeixeira42** [comment]
Hello guys! @jcfilben , can I take this issue?

I've been investigating this issue and I think I have found the problem. Inside the `DropButton` component the `buttonRef` value is passed as a parameter to the target prop. You can see it here:

```
  <Drop
    id={id ? `${id}__drop` : undefined}
    onAlign={onAlign}
    restrictFocus
    align={dropAlign}
    target={dropTarget || buttonRef.current}
    onClickOutside={onDropClose}
    onEsc={onDropClose}
    {...dropProps}
  >
    {dropContent}
  </Drop>
```

For some reason, the `hpe` theme that comes from `grommet-theme-hpe` is changing the component ref. When this happens, the component re-renders but the value of `buttonRef` keep the old ref. That's why the dropdown menu gets moved to the start of the document because de old ref does not exist anymore and `getBoundingClientRect` returns 0.

One way to solve this issue is to pass the `buttonRef` itself instead of its value. This way we pass the latest value to the `Drop` component like this snippet below:

```
DropButton.js

  <Drop
    id={id ? `${id}__drop` : undefined}
    onAlign={onAlign}
    restrictFocus
    align={dropAlign}
    target={dropTarget || buttonRef}
    onClickOutside={onDropClose}
    onEsc={onDropClose}
    {...dropProps}
  >
    {dropContent}
  </Drop>
```

And we can use the value like this:

```
DropContainer.js

const target = dropTarget.current;
```

What do you guys think? Do you think it's a good idea?

**Comment by JonasTeixeira42** [comment]
If you guys think it's a good idea I could work and open a PR for this

**Comment by jcfilben** [comment]
Hey @JonasTeixeira42 thanks for looking into this! If we change target to expect buttonRef instead of buttonRef.current we could run into backwards compatibility issues. It might be worth looking into why `badge` is causing a re-render when certain button theme options are set.

**Comment by britt6612** [comment]
Update 1/27
Notes from the investigation:
As another data point, if I forget badge entirely and instead set tip via the toggle, I see the same problem. So, the problem seems to be tied to Button re-rendering itself by wrapping styledButtonResult with either Tip or Badge.

place(false) inside DropContainer’s useEffect() inside a 2 second timer, the Drop starts placed in the right place after adding the badge but then after the timer goes off, the Drop gets re-placed and jumps to the top right corner. So, something seems to be going on with the dropTarget . It seems odd to me that waiting for 2 full seconds isn’t enough to ensure everything is stabilized.

 I commented out the clear prior styles portion of the code in the place function.
          container.style.left = '';
          container.style.top = '';
          container.style.bottom = '';
          container.style.width = '';
and then was console logging on line 276 console.log('target drop in place function', targetRect);
then also doing the following on line 59
console.log(dropTarget.getBoundingClientRect());
First screen shot is when its working and the second screen shot is when its not working which its getting reset to 0 but not sure how or why since I commented out

Another thing I tried was putting an id on the Button and then checking it inside place. The id is still there. If I do this inside place():
const t = document.getElementById('xyz');
const r = t.getBoundingClientRect();
then r.height shows the correct value even though targetRect.height does not.

**Need to find what is causing the `dropTarget` to be returning 0 for the bounds.**

**Comment by ericsoderberghp** [comment]
Re-rendering the Button when adding a `badge` or `tip` causes the DropButton's `buttonRef.current` to change. DropButton passes the initial `buttonRef.current` to DropContainer but doesn't pass the new one when the Button re-renders for the `badge` or `tip`.  It seems like the initial value for the ref is being remembered. As @JonasTeixeira42 suggested, if we change DropButton to set the Drop's `target` via: `target={dropTarget || buttonRef}` instead, and then change DropContainer to check for the target being a ref inside place() via `const target = dropTarget?.current || dropTarget;`, then everything seems to be working OK. I'm inclined to proceed in this manner at this point.

**Comment by ericsoderberghp** [comment]
I also think we should change DataContainer.js to use `useForwardedRef()` instead of doing `(ref || dropRef)` in various places.

**Comment by JonasTeixeira42** [comment]
Glad I could help to solve this issue. Thank you for the opportunity!
