### ISSUE TITLE
[OVGD] No space between picture and login form, the svg icon before title is gone.

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#672]
wrong layout with grommet 0.6.9
![image](https://cloud.githubusercontent.com/assets/16797825/16483614/c61ee6f8-3ee7-11e6-8c4c-6f5225f6d1e8.png)

right layout with grommet 0.6.7
![image](https://cloud.githubusercontent.com/assets/16797825/16483862/cdad89f0-3ee8-11e6-8a3d-2742686cc961.png)

**Comment by epilande** [comment]
Hi @christinHP you're receiving these issues from the recent namespace change to grommet classes. `grommetux-` has been prepended to the classes. https://github.com/grommet/grommet/blob/master/src/js/utils/CSSClassnames.js

Since OVGD is using a custom `LoginForm` component, you'll need to change the class root from 
`const CLASS_ROOT = "login-form";` to `const CLASS_ROOT = "grommetux-login-form";`

As for the SVG icon, it's still there, but it's missing a stroke.
Also I noticed the logo icon is much larger now in the sidebar. The class has been changed in the `Logo` component (`'logo-icon'`) & doesn't match the CSS (`.logo`).
