### ISSUE TITLE
remove defaultProps from Grommet

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet#6741]
Current version of React throws this error:
`Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

This occurs in over 100+ Grommet components because they're still using `defaultProps`

### Expected Behavior
Convert defaultProps to JavaScript default parameters instead.

### URL, screen shot, or Codepen exhibiting the issue
![Screenshot 2023-04-11 at 3 28 16 PM](https://user-images.githubusercontent.com/2007084/231280909-9eec7215-f84f-49f9-8021-f72bb93da078.png)
![Screenshot 2023-04-11 at 3 28 29 PM](https://user-images.githubusercontent.com/2007084/231280931-c451921c-cc0b-4642-bab3-df09d92f0e37.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
I think the main source of this is the use of `defaultProps` within the Styled* components as a means of at least passing the base theme in when there is no theme context. This happens when grommet components are used outside of a `<Grommet />` context. I am hoping we can find an alternative to deliver the base theme in these contexts as it would break backward compatibility to require an outer Grommet context.

**Comment by chrisphillers** [comment]
I am getting the same issue and it is crashing my Next.js 13.5 app.
Wondered if this was likely to be resolved? Thanks

**Comment by undeletable** [comment]
@ericsoderberghp I've started working on this, and I think I'll have a PR in a few days

**Comment by britt6612** [comment]
@undeletable thank you looking forward to your PR
