### ISSUE TITLE
Split 0.6.9

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#676]
Besides a lot of style changes in 0.6.9 It looks like i will have to modify a lot of things in my app. Split does not work any more as before. It does not show both panels at all. What could be the issue?

**Comment by primozs** [comment]
my mistake with Split component

**Comment by alansouzati** [comment]
Sorry about the css changes. We had to add a `grommetux-` namespace to avoid conflicts with apps that are using grommet with other frameworks.

As it was an internal change, we decided to stay in the `0.6.X` range. I'm assuming you are facing issue with that because you are somehow accessing the grommet classes in your scss.

**Comment by primozs** [comment]
Hi @alansouzati yes its true, I will solve it.
Cheers
