### ISSUE TITLE
Select Options Issue

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#6807]
### Expected Behavior

The ability to utilise the full container width when setting the `labelKey` property to a function returning a React Node.

### Actual Behavior

Due to the React Node provided to `labelKey` being wrapped in a `span`, it cannot utilise the full width of the container.

### Your Environment

- Grommet version:  2.32.0

**Comment by jcfilben** [comment]
Hi @versoworks in addition to setting the `labelKey` can you also try setting the `valueLabel` prop to customize how the option is display. I believe this should allow you to utilize the full width of the container.

**Comment by versoworks** [comment]
@jcfilben apologies as I should have mentioned it in the OP; I'm using both `labelKey` and `valueLabel`, hence the raising of this issue. I'm simply wanting to use the full container width of the `drop` component when rendering an `option`.

Currently, `labelKey` is being set with a `Box` node that has 2 child `Box` nodes. The parent node has the `justify` property set to `between`. The expected result is the 1st child node set at the start of the `drop` container and the 2nd child node be at the end of the `drop` container. This is not the result I'm experiencing due to the parent node being the child of a `span` node. See the images below;

<img width="572" alt="Screenshot 2023-05-25 at 5 24 03 am" src="https://github.com/grommet/grommet/assets/16771879/1976a3bb-9fe8-4fb5-b59a-6442f1722bd4">
<img width="572" alt="Screenshot 2023-05-25 at 5 24 49 am" src="https://github.com/grommet/grommet/assets/16771879/d88d2fa7-7df4-400a-9add-e0b4029bedba">

**Comment by jcfilben** [comment]
Ah gotcha, I think I misunderstood your original question. I thought you were trying to customize the display at the input level rather than the options within the drop. So `valueLabel` is used to customize how the selected option displays at the input level when the drop is closed. If you want to control how the options within the Drop are displayed you can pass a function as a child to the Select component. Here is a codesandbox example: https://codesandbox.io/s/grommet-v2-template-forked-2ik3gh?file=/index.js.

**Comment by versoworks** [comment]
That did it. Thank you, @jcfilben
