### ISSUE TITLE
Customized Brand color options

### ISSUE THREAD

**Issue by sahil28v** [grommet/grommet#684]
Is there a way to change colorIndex color options or use my own random colors options for component backgrounds ?
Say,  colorIndex="#343434" ----> Can something like this be done... 

Looks like an easy thing but I couldn't find any related documentation.

**Comment by alansouzati** [comment]
we dont support color index with HEX, all the colors should come from your SASS files.

For example: `neutral-1` is the first color for the neutral array. If you want to customize it you need to create a new theme and use it in your project.

Please see the HPE, HPinc and all themes available inside grommet core:

https://github.com/grommet/grommet/blob/master/src/scss/hpe/_hpe.defaults.scss#L7

**Comment by sahil28v** [comment]
Got it, thanks.
Btw... great work with the framework.I just started exploring it & so far I'm liking it a lot.
Among other solely react-based component frameworks I've used, this is really looking like a great option.(kudos to the team) --- Hope there is a plan to add more cool components & features like autosuggest.

**Comment by alansouzati** [comment]
Thanks for the kind words. 

When you say autosuggest do you mean autocomplete in a search input?

We are constantly evaluating the need for more components, please let us know if you feel the need for a component that is yet not available today. FYI, there are some components that are intentionally not supported because it does not fit to your design philosophy and accessibility requirements.

**Comment by stonecold123** [comment]
How can I create a custom theme? 
Directly modifying  **_hpe.defaults.scss**?

**Comment by sebasalvarado** [comment]
I would do +1 for autocomplete component! Also loving the framework.
