### ISSUE TITLE
Data - complex story range filter

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7037]
### Expected Behavior
On the Data/Complex story when a range filter is applied a badge should show that a filter has been applied and the 'clear filters' button should appear.

### Actual Behavior
There is no indication a filter has been applied and the 'clear filters' button doesn't show up.

This issue seems isolated to the Data/Complex story, other stories with range filters don't have this issue.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/data-data-complex--complex

### Steps to Reproduce

1. Visit the story above
2. Filter by GDP

**Comment by MikeKingdom** [comment]
There are two problems here related to RangeSelectors in DataFilters.

1. For complex, hierarchical property names that we support in forms like 'economy.GDP', DataForm's `transformTouched` specially treats RangeSelector values since it's looking for `_range` in the value object, but how it finds this in `touched` assumes only 1 level of property name. This is easy to fix.
2. DataFilters decides whether to have a # of filters badge based on how many non-falsey things end up in `touched` as returned by `transformTouched`. But any property value in the form set back to it's initial value can be truthy if that initial value is something, especially true for RangeSelectors which will always have a value. Should DataFilters instead determine touched by comparing against initial/default values? Or is that something the badge calculation should do? I'm thinking the badge calc filter should compare against initial/default values for filters instead.
