### ISSUE TITLE
[IE 11] The select in FormField displays bad

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#710]
Please see the attached picture, the select in Chrome is shown under triangle icon, but the select in IE 11 is shown cover the triangle icon. The layout about select in ForField is wrong.

![ff53c7bc-49ce-11e6-8546-2638d409f05a](https://cloud.githubusercontent.com/assets/16797825/16946618/07ca9bfc-4ddd-11e6-89ca-8331754d89c5.png)

The code in one view global dashboard is 

        <Box direction="row" pad="medium" justify="start">
          <Form compact={true}>
            <FormField label="Select Baseline SPP Bundle" htmlFor="baseline">
              <select name="baseline" defaultValue=''
                      onChange={this._onChange.bind(this)} value={baseline} >
                <option value=""></option>
                {bundleList}
              </select>
            </FormField>
          </Form>
        </Box>

**Comment by epilande** [comment]
Hi @christinHP, we do not have control over where the dropdown options appear since that's using the default HTML5 select. I've tried it ([CodePen](http://codepen.io/epilande/pen/dXZLdJ)) in different browsers using Mac & Windows, & it's rendered differently.

For more info see: http://stackoverflow.com/a/18689790/3567750

Also I've created a CodePen with the code you've provided: http://codepen.io/epilande/pen/dXZLdJ

**Comment by bryanjacquot** [comment]
Thanks for the CodePen @epilande.  This interaction is intended as Grommet uses the browser's native dropdown to ensure proper behavior across platforms and when lists get long and require special handling for scrolling.  The lists are styled, but the behavior of where the menu appears is beyond the control of styling, currently.
