### ISSUE TITLE
DataSort - If Data `properties` defines labels these should be used

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7282]
### Expected Behavior
DataSort should use the labels defined in Data `properties`.

### Actual Behavior
The labels are ignored and the default name is used.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-5fr4lt?file=/index.js

**Comment by unamdev0** [comment]
Hi @jcfilben, small doubt regarding this ticket.

In the above sandbox instead of using `Name1` which is the defined header in columns array `properties.name.label` which is `new Name` should have been used as the column's header ? Is that the desired result

Additionally, if this change is made for data sorting, should it also be applied to other components related to the data?

**Comment by MikeKingdom** [comment]
> Hi @jcfilben, small doubt regarding this ticket.
> 
> In the above sandbox instead of using `Name1` which is the defined header in columns array `properties.name.label` which is `new Name` should have been used as the column's header ? Is that the desired result
> 
> Additionally, if this change is made for data sorting, should it also be applied to other components related to the data?

The column header in the DataTable does always come from the `columns` defined for the DataTable. That's intentional.
The `properties` prop to `Data` is intended to control what appears in any DataFilter, DataSort, DataColumns drops/layers. It's independent of the DataTable's `columns` attribute and does not override it. `properties` is especially useful for children of Data which are not DataTables (like List, Cards, Map, etc.)

With that said, I believe there is an issue here that needs to be fixed on DataSort. DataSort needs to use the labels from `properties` for it's `sort by` select.
