### ISSUE TITLE
Search onSelect does not fire when inline={true}

### ISSUE THREAD

**Issue by heyjared** [grommet/grommet#734]
Pressing enter in a Search component does not fire the onSelect function.

### Expected Behavior
Search should execute onSelect when `inline={true}`

### Actual Behavior
onSelect function is not executed.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/yJqzgO?editors=0010

### Steps to Reproduce
 1. Type something in the inline search box and press enter. Search is not executed.
 2. Type something in the noInline search box and press enter. Search is executed.

**Comment by alansouzati** [comment]
Thanks for the detailed information. it really helps to triage the root cause. 👏

**Comment by alansouzati** [comment]
hi @heyjared it turns out that "no inline" search box should not trigger the onSelect.

As per the docs page here: http://www.grommet.io/docs/hpe/develop/search

`onSelect` is a callback used for search suggestions only.

I've fixed the noInline calling the onSelect callback in here: https://github.com/grommet/grommet/commit/84fb2c5210e3950522eeb3ddd081ab6d2592939e

In your case I believe you are looking for the `onDOMChange` event.

I've updated your codepen, you can find it here:

http://codepen.io/alansouzati/pen/BzOjBk?editors=0010

If you want to save requests to the backend with the Search, I recommend applying a debounce strategy. There is a really good article about it here:

https://john-dugan.com/javascript-debounce/

While it is tempting to add the debounce inside the Search component itself, some users may want to have access to the change immediately. So, delaying the requests on search needs to be done in the callers side.

Feel free to reopen the issue if you are still facing issues.

**Comment by heyjared** [comment]
I actually want to execute something onEnter, without selecting any of the suggestions, but I still want to save the user input value. What would be the best way to capture that input?

**Comment by primozs** [comment]
I would also need something like this:
```
  onKeyDown(e) {
    const searchActions = this.props.searchHistoryActions;
    switch (e.keyCode) {
      case 13:
        // enter - search
        break;
      case 38:
        // arrow up - previous search in history
        break;
      case 40:
        // arrow down - next search in history
        break;
    }
  }
```

Currently I am using modified version of Search component.
```
<input key="input" id="search-drop-input" type="search"
         ...
         onKeyDown={this._onKeyDown}/>
```

**Comment by alansouzati** [comment]
This is related to passing props to a Grommet component. We are doing it on a need basis.

It seems that Search needs passing props to the input element. Similar to the way we did for the Calendar:
https://github.com/grommet/grommet/pull/718/files

would any of you be willing to write a PR for the Search component?

**Comment by primozs** [comment]
I can check in a few days.
