### ISSUE TITLE
datepicker usability

### ISSUE THREAD

**Issue by acornejo** [grommet/grommet#786]
The datepicker component has terrible UX for changing months.
### Expected Behavior

I would expect to be able to change months without having to chase a moving target.
### Actual Behavior

As the months change the size of the dialog changes, and so does the positioning of the UI elements.

https://youtu.be/2OCBRhle138

**Comment by bryanjacquot** [comment]
@acornejo thanks for the input.  This only happens when there's not room for the calendar to display in the default position which is below the input box.  But when the calendar is displayed above the form field, you're right, it's not fun.

We'll add another row to calendar so there's always 5 weeks of days show, sometimes the days will extend into the following month, but the month arrows won't move.

If you're up for a PR, we'd gladly accept.

**Comment by cherih** [comment]
Modified the DateTImeDrop component to always display 6 weeks. This prevents the date change controls from jumping around:
![datetimedrop-screenshot](https://cloud.githubusercontent.com/assets/25066338/23562975/f21e2b34-0001-11e7-9317-3dd09f0170db.PNG)

Concerns:
1. It's hard to tell the difference between days in the selected month and those that aren't in the month. The styling for the other-month is being applied correctly, but the contrast between the secondary text color and the primary text color is not great enough for me to readily see. Can we change the stylings to increase the contrast between the text colors?

2. For some months, there are a lot of extra days shown at the end that aren't in the selected month. Is this OK, or should we create a new styling to hide these extra days?
