### ISSUE TITLE
Add display time zone option to "Timestamp"

### ISSUE THREAD

**Issue by tomtosi** [grommet/grommet#835]
Add time zone option to "Timestamp"
### Expected Behavior

For circumstances where it is not feasible to display the date/time in user's time zone but instead must use a global reference, need the option to display the time zone (e.g. "UTC") in the time stamp.
### Actual Behavior

There is currently no option to indicate (_within_ the timestamp) what time zone is being referenced.
### URL, screen shot, or Codepen exhibiting the issue

http://grommet.github.io/hpe/docs/timestamp
### Steps to Reproduce

NA
### Your Environment

NA

**Comment by dgennetten** [comment]
This thread illuminates the difficulty of this requesthttps://github.com/moment/moment/issues/162

**Comment by dgennetten** [comment]
@alansouzati #1353 does not address this timezone issue

**Comment by alansouzati** [comment]
sorry github closed it automatically.

**Comment by alansouzati** [comment]
this would require another package that handles timezones with names like `America\Los_Angeles` which seems very vendor specific. 

It is likely the timestamp will be removed in 2.0 as it is just a tiny wrapper around moment-js.

I don't see ourselves adding much more support for timestamp as it stands today. I'm going to close this issue because of this reason.
