### ISSUE TITLE
Meter value offset not updated when omitting the size property.

### ISSUE THREAD

**Issue by tobias-flitsch** [grommet/grommet#856]
Meter value not displaying correctly if not specifying the size property.

### Expected Behavior
If the size property is not passed to the Meter component it should pick the default value of 'small' and position the value label at 50%,50%, in the middle of the circle.

### Actual Behavior
The value is positioned as with the size "medium", so it is outside of the circle.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/tobias-flitsch/pen/ORNbpJ?editors=0010

![image](https://cloud.githubusercontent.com/assets/4466053/18523584/baeb6154-7a69-11e6-98b2-b6c675e60c44.png)

### Steps to Reproduce
 1. Create Meter component with a value and property `type="circle"`
 2. Set `size="small"` --> will render correctly.
 3. Remove property `size` --> will render value outside of the Meter.

### Your Environment
* Grommet version: 0.6.11
* Browser Name and version: chrome 52.0.2743.116 (Official Build) m (32-bit)
* Operating System and version (desktop or mobile): Windows 10 (desktop)

**Comment by alansouzati** [comment]
Thanks for reporting this.

Fixed in https://github.com/grommet/grommet/commit/6d992b6cbc0b5e55410abcece7fac612e1a7f68c

Moving forward the meter will require a label, please refer to the Meter examples for the updated way to implement meters:

https://grommet.github.io/docs/meter-examples#2
https://grommet.github.io/docs/meter-examples#7
