### ISSUE TITLE
RadioButton component has no indication in HTML which button is checked

### ISSUE THREAD

**Issue by ToddBarkalowHPE** [grommet/grommet#962]
Using RadioButton component, there is no way to determine which radio button is checked.  This is required by our automation team for automated testing.

img1.png: Code to reproduce issue
img2.png: HTML with missing checked flag

Thank you,
Todd

### Expected Behavior
A way to determine (scanning HTML result) which radio button is checked.  checked flag.

### Actual Behavior
Per img2.png, no indication which radio button is selected

### URL, screen shot, or Codepen exhibiting the issue

See img1.png and img2, png

### Steps to Reproduce
 1. Create RadioButton components in group (at least 2 buttons)
 2. run
 3. inspect HTML output

### Your Environment

* Grommet version: 0.6.11
* Browser Name and version: Chrome Version 53.0.2785.143 m
* Operating System and version (desktop or mobile): Windows 10 desktop
![img1](https://cloud.githubusercontent.com/assets/22778995/19287964/3163a4ec-8fc1-11e6-84b6-971b7f70066d.png)
![img2](https://cloud.githubusercontent.com/assets/22778995/19287971/3673f9fa-8fc1-11e6-846b-708592e42378.png)

**Comment by alansouzati** [comment]
After investigating this I found out that the problem is also present in regular HTML radio buttons.

See the w3c site for radio html:

http://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio 

Also see a related issue on React regarding this:

https://github.com/facebook/react/issues/7051

My recommendation is the same as @syranide, use the query selector `:checked` option.

I've created a codepen that illustrates how you can retrieve the checked checkbox.

http://codepen.io/alansouzati/pen/WGJgAx?editors=0010

In my opinion this is not a problem with React or Grommet.
